/* Revision notes for Physics */
window.NOTES = window.NOTES || [];
window.NOTES.push(
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Measurement',
    qt: ['Units and measurement'],
    title: 'Units, dimensions and significant figures',
    body: 'Measurement questions open nearly every Physics paper, because every later topic depends on a number being attached to the right unit and the right number of figures. Units, dimensions, scalars and vectors, significant figures and simple unit conversions all come from the first section of the examination and can be answered in seconds once you know what to look for.\n\nHere\'s the idea: a physical quantity is only a number once you have fixed three things, namely its unit, its dimension and how precisely it is stated, and every unit in the syllabus is either one of the seven base units or built out of them.\n\nStep 1 - Fix the unit from the quantity: metre for length, kilogram for mass, second for time, newton for force, joule for work, watt for power, pascal for pressure and hertz for frequency.\nStep 2 - Fix the dimension by writing length as L, mass as M and time as T, so force is MLT^-2 and work is ML^2T^-2; if the two sides of an equation do not match dimensionally, the equation is wrong.\nStep 3 - Count significant figures carefully: leading zeros never count, so 0.00450 has three, and round rather than chop when a question asks you to correct a value.\nStep 4 - Convert units before substituting, using 1 km/h = 1000/3600 m/s, so a speed in km/h is divided by 3.6 to get m/s.\n\nExample: Correct 4.5678 to three significant figures: The options are 4.56, 4.57, 4.58 and 4.568. The significant figures are 4, 5, 6, 7 and 8, and we must stop after the third, which is the 6. The next digit is 7, which is 5 or more, so the 6 is rounded up to 7 and the answer is 4.57. Option 4.56 simply drops the 7, 8 and truncates instead of rounding, so it understates the value. Option 4.58 rounds twice, pushing the 7 up as well, which changes a number you were asked to correct to three figures. Option 4.568 keeps four figures and is not a correction to three at all.\n\nWatch out: counting the leading zeros in 0.00450, which gives four or five instead of three, and treating the final zero as insignificant. That trailing zero sits right next to the 5, so it is a significant figure and is kept.\n\nIn short: a number alone is not a measurement, so always attach the unit, the dimension and the correct number of significant figures.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Linear motion',
    qt: ['Motion and forces'],
    title: 'Acceleration, graphs and projectiles',
    body: 'Linear motion covers the equations of motion, the slope and area of the two graphs you must know, and projectile motion, and it forms the largest block of marks in the Physics paper. Speed, velocity and acceleration are distinguished carefully, and almost every numerical question can be solved with one of three equations.\n\nHere\'s the idea: for uniform acceleration the three quantities u, a, t, v and s are locked together by v = u + at, s = ut + 1/2 at^2 and v^2 = u + 2as, so you only need to recognise which pair of them the question gives you and which one it asks for.\n\nStep 1 - List what you are given and what you want, writing u, a, t, v and s explicitly, and remember that from rest means u = 0 while stopping means the final v = 0.\nStep 2 - Pick the equation that contains exactly the quantities you have plus the one you need, rather than the one you remember best.\nStep 3 - Substitute with g = 10 m/s^2, square the speed or time rather than doubling it, and keep the units on every line.\nStep 4 - Sanity check the direction of the answer: a body thrown up slows to zero and then comes down, and a graph question is read from slope for distance-time graphs and from area for velocity-time graphs.\n\nExample: A runner covers 100 m in 10 s and another 100 m in 20 s. The average speed for the whole journey is: The options are 15 m/s, 5 m/s, 6.7 m/s and 10 m/s. Average speed is total distance divided by total time, never the average of the two separate speeds. Total distance is 100 + 100 = 200 m and total time is 10 + 20 = 30 s, so the average speed is 200 / 30 = 6.67 m/s, that is 6.7 m/s. Option 10 m/s is the speed of the first half alone, option 5 m/s is the speed of the second half alone, and option 15 m/s comes from adding 10 + 5 instead of averaging them.\n\nWatch out: adding the two stage speeds, or dividing the distance of one stage by the time of the other. Average speed is always total distance over total time, so if the two stages take equal times the answer is exactly the average of the speeds, but never if the times differ.\n\nIn short: total distance over total time, and choose the one equation of motion that contains your unknowns.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Forces',
    qt: ['Motion and forces', 'Work energy and power'],
    title: 'Resultants, friction and pressure',
    body: 'Forces is the second largest block in the Physics paper, covering Newton laws, friction, pressure, moments, momentum, upthrust and circular motion. The ideas are tightly linked: pressure is a force spread over an area, friction is a force that depends on the normal reaction, and centripetal force is the net force pointing at the centre of a circle.\n\nHere\'s the idea: every force question is Newton\'s second law in disguise, so find the resultant of the forces first, and then apply F = ma with the mass expressed in kilograms and the acceleration in m/s^2.\n\nStep 1 - Draw a free body diagram and list every force on the body, including weight, normal reaction, upthrust and friction, so that nothing is silently missing.\nStep 2 - Resolve into perpendicular directions, or work along the direction of motion if it is a straight line, and add the components with their signs.\nStep 3 - Apply the matching formula: F = ma, pressure = force / area, liquid pressure = density x g x depth, moment = force x perpendicular distance, and limiting friction F = mu x R.\nStep 4 - Use P = mg for the weight, remembering that R is the normal reaction and is not automatically equal to the weight, and check that the answer carries a unit and the right size.\n\nExample: A body of mass 5 kg rests on a rough horizontal surface. If the coefficient of friction is 0.4 and g = 10 m/s^2, the minimum force needed to just move it is: The options are 50 N, 25 N, 10 N and 20 N. The pull must just balance the limiting friction, so F = mu x R. On a horizontal surface the normal reaction R equals the weight mg = 5 x 10 = 50 N, hence F = 0.4 x 50 = 20 N. Option 50 N is mg, the weight of the body, which is what you get if you forget friction altogether. Option 10 N uses mu x g = 0.4 x 10 and leaves the 5 kg mass out. Option 25 N comes from adding the 5 kg to the 20 N instead of multiplying by it.\n\nWatch out: assuming the normal reaction equals the weight when the question gives an accelerating or angled situation, and forgetting that the friction force is the force needed to just move the body, so the answer is the limiting friction and not the motion.\n\nIn short: find every force, resolve, then F = ma with the mass in kilograms and the acceleration in m/s^2.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Work energy and power',
    title: 'Work, energy, power and machines',
    body: 'Work, energy and power are the questions that ask what has been transferred and how fast, and they cover work done, kinetic and potential energy, conservation of energy, power, efficiency, Hooke law and elasticity. Many of them are a single substitution once you have identified which quantity the question wants.\n\nHere\'s the idea: work is force multiplied by distance measured along the force, energy is the capacity to do that work, and power is the rate at which the work is done, so the three sit in a chain of W divided by t.\n\nStep 1 - Identify the quantity asked for: work needs F and s, kinetic energy needs m and v, potential energy needs m, g and h, and power needs work and time.\nStep 2 - Substitute with everything in SI units, so masses in kilograms, distances in metres and times in seconds, and use g = 10 m/s^2.\nStep 3 - For power, remember that work must be found first: 500 N lifted through 3 m is 1500 J, and 1500 J in 10 s is 150 W.\nStep 4 - For a machine, divide useful output by input: efficiency = useful work / energy in x 100, which also equals mechanical advantage / velocity ratio x 100.\n\nExample: An engine lifts a load of 500 N through a height of 3 m in 10 s. The power developed is: The options are 1.5 W, 15 W, 150 W and 1500 W. The work done against gravity is force x distance = 500 x 3 = 1500 J, and power is the rate of doing work, so P = 1500 / 10 = 150 W. Option 1500 W is the work in joules with no division by time, and it is the single most common slip in this topic. Option 15 W divides by 100 instead of by 10, or moves the decimal once too far. Option 1.5 W moves it twice.\n\nWatch out: reporting energy in joules when the question asked for power in watts. Power always carries a division by time, and 1 W = 1 J/s, while the answers in the options differ only by a factor of 10, which tells you exactly where the decimal point went wrong.\n\nIn short: work is force times distance, energy is what is stored, and power is that energy divided by time.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Heat and temperature',
    qt: ['Heat and thermodynamics'],
    title: 'Temperature, heat and gas laws',
    body: 'Heat and temperature questions mix definitions with two formula families: Q = mc delta T for a change of temperature and Q = mL for a change of state, together with the transfer of heat and the gas laws. Temperature scales and expansion questions are definition marks and appear in the first section, while the calculations run through the middle of the paper.\n\nHere\'s the idea: temperature measures average kinetic energy while heat measures energy transferred, so a rise in temperature needs mc delta T and a melting or boiling needs mL with no change of temperature at all.\n\nStep 1 - Identify the process: warming or cooling uses Q = mc delta T, melting or boiling uses Q = mL, and a temperature conversion uses K = degrees Celsius + 273.\nStep 2 - Substitute in SI units with c in J/kg K and L in J/kg, so a mass in kilograms, and remember the delta T is a difference so it may be negative.\nStep 3 - For the gas laws convert every temperature to kelvin first, then choose P1/T1 = P2/T2 at constant volume, V1/T1 = V2/T2 at constant pressure, or P1V1 = P2V2 at constant temperature.\nStep 4 - Check the direction: heating a gas at constant pressure must increase its volume, and heating a gas at constant volume must increase its pressure.\n\nExample: The quantity of heat needed to raise the temperature of 2 kg of water through 10 degrees C (specific heat capacity 4200 J/kg K) is: The options are 8400 J, 4200 J, 84000 J and 21000 J. Here Q = mc delta T = 2 x 4200 x 10 = 84000 J. Option 8400 J is the calculation for 1 kg, so it forgets the mass and leaves out the factor of 2. Option 4200 J is just c on its own, using delta T = 1. Option 21000 J is what you get for 1 kg of a substance whose specific heat capacity is 2100 J/kg K, so it forgets the 2 kg and borrows the wrong constant.\n\nWatch out: dropping the mass when the specific heat capacity is used, and using degrees Celsius in a gas law. For a gas at constant volume with 100 kPa at 27 degrees C, the pressure at 127 degrees C is 100 x 400 / 300 = 133.3 kPa, and using 27 and 127 directly gives a nonsense answer.\n\nIn short: mc delta T for a temperature change, mL for a change of state, and kelvin in every gas law.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Waves',
    qt: ['Waves and sound'],
    title: 'Wave language and superposition',
    body: 'Wave questions test the language of waves, the wave equation, superposition and diffraction, and they are the easiest marks in the Physics paper once the definitions are secure. A wave moves energy without carrying matter with it, and almost every numerical question is v = f x wavelength rearranged.\n\nHere\'s the idea: frequency, wavelength and speed are locked by speed = frequency x wavelength, and when a wave changes medium the frequency is fixed by the source while the speed and the wavelength change together.\n\nStep 1 - Decide which of the three you are given and which you want, then rearrange v = f x wavelength into the form you need.\nStep 2 - Convert periods to frequencies with f = 1/T before substituting, so 0.05 s becomes 20 Hz.\nStep 3 - Identify the type of wave: transverse waves vibrate at right angles to the direction of travel as light does, longitudinal waves vibrate along it as sound does, and only electromagnetic waves cross a vacuum.\nStep 4 - Read the definitions exactly, because they are asked verbatim: wavelength is the distance between two consecutive points in phase, frequency counts complete waves per second, and superposition says the resultant displacement is the algebraic sum.\n\nExample: A wave has a frequency of 50 Hz and a wavelength of 4 m. Its speed is: The options are 5 m/s, 20 m/s, 12.5 m/s and 200 m/s. The wave equation gives speed = frequency x wavelength = 50 x 4 = 200 m/s. Option 12.5 m/s is 50 / 4, so it divides where it should multiply, and it is the classic trap in this question. Option 20 m/s uses a frequency of 5 Hz instead of 50 Hz. Option 5 m/s comes from dividing 20 by 4 as well.\n\nWatch out: dividing instead of multiplying, and forgetting that frequency never changes when a wave crosses a boundary. When a wave passes from air into glass the frequency stays fixed while the speed increases, so the wavelength must increase in the same proportion.\n\nIn short: speed = frequency x wavelength, frequency is fixed by the source, and wavelength changes with the speed.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Sound',
    qt: ['Waves and sound'],
    title: 'Echoes, beats and resonance',
    body: 'Sound is the wave topic that comes with a medium requirement, so its questions mix wave ideas with applications: echoes and SONAR, beats, resonance, pitch, loudness and quality, and the audible range. Almost all of it is conceptual, and the echo question is the one calculation you must get exactly right.\n\nHere\'s the idea: sound is a longitudinal mechanical wave, so it needs matter to travel through and it travels fastest in solids and slowest in gases, and any echo calculation must count the round trip, not the one-way journey.\n\nStep 1 - Fix the speed of sound in air at about 340 m/s, and remember that it is a longitudinal wave needing a medium, which is why it cannot cross a vacuum.\nStep 2 - For an echo, multiply speed by the elapsed time to get the total distance travelled, then halve it to get the distance to the reflecting surface.\nStep 3 - Separate the three hearing ideas: pitch comes from frequency, loudness comes from amplitude, and quality or timbre tells two instruments playing the same note apart.\nStep 4 - Apply the special facts: beat frequency is the difference of the two frequencies, resonance occurs when the driving frequency equals the natural frequency, and intensity obeys the inverse square law.\n\nExample: An observer hears an echo 2 s after shouting at a cliff. The distance of the cliff (speed of sound = 340 m/s) is: The options are 680 m, 340 m, 170 m and 34 m. In 2 s the sound travels 340 x 2 = 680 m, but that is the round trip, out to the cliff and back to the observer. The one-way distance is therefore 680 / 2 = 340 m. Option 680 m forgets the round trip and is the standard trap. Option 170 m divides by 4, halving twice. Option 34 m moves the decimal one place instead of dividing.\n\nWatch out: reporting the total distance travelled by the sound rather than the distance of the reflecting surface. The same halving applies to every echo, SONAR and depth question, and 2 seconds is also the minimum delay before the ear distinguishes an echo as a separate sound.\n\nIn short: sound needs a medium, an echo doubles the journey, and pitch is frequency while loudness is amplitude.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Light and optics',
    qt: ['Optics'],
    title: 'Reflection, refraction and lenses',
    body: 'Light and optics covers reflection, refraction, refractive index, critical angle and total internal reflection, plane and spherical mirrors, lenses, optical defects and dispersion. Questions mix definitions, sign-free calculations such as lens power, and reasoning about where an image forms, and the units of focal length are the usual trap.\n\nHere\'s the idea: lenses and mirrors are described by two numbers, the focal length and the power, and the power is simply the focal length in metres turned upside down, so a short focal length always means a powerful lens.\n\nStep 1 - Identify whether the object or the medium is denser, because light bends towards the normal when going from rarer to denser and away from the normal in the reverse direction.\nStep 2 - For refractive index use n = c / v with c = 3 x 10^8 m/s, and for the critical angle use sin C = 1 / n.\nStep 3 - For a lens convert the focal length to metres before dividing: power P = 1 / f in dioptres, so 20 cm becomes 0.2 m and gives 5 D.\nStep 4 - Check the type of image against the device: a plane mirror gives a virtual, erect, same-size image, a real image needs a convex lens or a concave mirror, and short sight needs a concave lens while long sight needs a convex one.\n\nExample: A convex lens of focal length 20 cm has a power of: The options are 0.2 D, 2 D, 5 D and 20 D. Power is the reciprocal of the focal length expressed in metres, so 20 cm = 0.2 m and P = 1 / 0.2 = 5 D. Option 0.2 D is simply the focal length in metres with no division, and it is the trap for anyone who forgets the reciprocal. Option 2 D results from reading 20 cm as 0.5 m. Option 20 D leaves the focal length in centimetres.\n\nWatch out: leaving the focal length in centimetres inside the formula, which is wrong by a factor of 100. On the same idea, two lenses of 2 D and 3 D in contact give 5 D because powers simply add, whereas focal lengths must be combined as 1/f = 1/f1 + 1/f2.\n\nIn short: convert the focal length to metres, invert it for power, and let the denser or rarer medium decide which way the ray bends.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Electricity',
    qt: ['Electricity and magnetism'],
    title: 'Current, resistance and circuit rules',
    body: 'Electricity questions cover current, potential difference, resistance, series and parallel arrangements, electrical power and energy, and the purpose of fuses. The definitions are easy marks, while the series and parallel rules account for a good share of the numerical questions in the second half of the paper.\n\nHere\'s the idea: everything follows from Ohm law V = IR together with two arrangement rules, that series resistances add and that parallel resistances combine so the result is always smaller than the smallest branch.\n\nStep 1 - Write the quantity you want and rearrange Ohm law for it: V = IR, I = V / R, R = V / I.\nStep 2 - Decide whether the components are in series or in parallel, then apply the rule: in series R = R1 + R2 + R3 with the same current everywhere, in parallel 1/R = 1/R1 + 1/R2 with the same voltage across each branch.\nStep 3 - For power use P = VI = I^2 R = V^2 / R, and for energy use energy = power x time, converting hours to seconds or using watts and kilowatt hours as the units require.\nStep 4 - Sanity check the size: a parallel combination must be less than either branch, a series combination must be greater, and a fuse rating must sit just above the normal current from P = VI.\n\nExample: The effective resistance of a 2 Ohm resistor connected in parallel with a 3 Ohm resistor is: The options are 5 Ohm, 1.2 Ohm, 6 Ohm and 0.6 Ohm. Adding the reciprocals gives 1/R = 1/2 + 1/3 = 3/6 + 2/6 = 5/6, so R = 6 / 5 = 1.2 Ohm. Equivalently the product over the sum is 2 x 3 / (2 + 3) = 6 / 5 = 1.2 Ohm. Option 5 Ohm is the series answer, obtained by adding, and it is the trap for anyone who ignores the word parallel. Option 6 Ohm is the product 2 x 3, which is larger than either resistor and so impossible for a parallel pair. Option 0.6 Ohm comes from dividing 6 by 10 instead of by 5.\n\nWatch out: adding instead of combining in parallel, and quoting a parallel result that is larger than the smallest branch, which is impossible because the branches share the current. Mixing series and parallel rules inside one question is the usual cause.\n\nIn short: series adds and parallel divides reciprocally, then use V = IR and P = VI with everything in volts, amperes and ohms.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Magnetism',
    qt: ['Electricity and magnetism'],
    title: 'Fields, motors and induction',
    body: 'Magnetism covers magnetic field patterns, the motor and generator effects, electromagnetic induction, the transformer, and the choice of materials for cores. The questions are mostly definition and reasoning, with a small number of force and transformer calculations that follow from two formulas.\n\nHere\'s the idea: the motor effect turns current in a field into force and the generator effect turns motion in a field into current, and both are remembered by their hand rules rather than by any calculation.\n\nStep 1 - Fix the field pattern: outside a bar magnet the lines run from north to south, inside the magnet from south to north, a straight current gives circular field lines around itself, and a long solenoid gives a uniform field along its axis.\nStep 2 - Use the correct hand rule: Fleming left-hand rule gives the direction of force in a motor, and Fleming right-hand rule gives the direction of induced current in a generator or dynamo.\nStep 3 - Calculate the motor force with F = BIL when the conductor is at right angles to the field, multiplying flux density, current and length in that order.\nStep 4 - Use the transformer ratio Vs/Vp = Ns/Np, and choose soft iron for electromagnet cores because it magnetises and demagnetises easily, while steel keeps its magnetism for permanent magnets.\n\nExample: A conductor of length 0.2 m carrying a current of 4 A is placed at right angles to a uniform field of flux density 0.5 T. The force on it is: The options are 0.4 N, 4 N, 0.04 N and 2 N. At right angles F = BIL = 0.5 x 4 x 0.2 = 0.4 N, since 4 x 0.2 = 0.8 and 0.5 x 0.8 = 0.4. Option 2 N is B x I on its own, 0.5 x 4 = 2, with the length left out. Option 4 N is the current on its own, and option 0.04 N comes from dividing by ten where you should multiply.\n\nWatch out: dropping a factor of ten by leaving the length in centimetres, and using the right-hand rule for a motor. Left hand is for motors where current in a field gives force; right hand is for generators where motion in a field gives current.\n\nIn short: field lines run north to south outside the magnet, left hand gives motor force, right hand gives generator current.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Nuclear physics',
    qt: ['Radiation'],
    title: 'Radioactivity, half-life and energy',
    body: 'Nuclear physics covers the structure of the atom, the three types of radiation, half-life and the uses of isotopes, and it also includes fission, fusion and nuclear energy. Most of the marks are for precise definitions and for knowing which property belongs to which type of radiation.\n\nHere\'s the idea: radioactive decay is random and spontaneous at the level of each nucleus, so you cannot predict when one particular nucleus will decay, but you can predict how the total count falls over many half-lives because the activity halves each time.\n\nStep 1 - Name the quantities: the atomic number counts protons and the mass number counts protons plus neutrons, so neutrons = mass number minus atomic number.\nStep 2 - Match each radiation to its properties: alpha particles are helium nuclei, strongly ionising but stopped by paper; beta particles are fast electrons, stopped by a few millimetres of aluminium; gamma rays are uncharged electromagnetic radiation, stopped only by thick lead.\nStep 3 - Use the half-life by halving the remaining amount each time: an 80 g sample is 40 g after one half-life, 20 g after two, 10 g after three and 5 g after four, and it never reaches zero.\nStep 4 - Separate the two nuclear reactions: fission splits a heavy nucleus such as uranium and sustains a chain reaction, while fusion joins light nuclei as in the Sun and needs an extremely high temperature.\n\nExample: The half-life of a radioactive substance is the time taken for: The options are half of the nuclei present to decay, its activity to fall to zero, all of its nuclei to decay, and its nuclei to double in number. The correct one is half of the nuclei present to decay, because after each half-life the remaining amount is divided by two, so a sample that is halved twice has a quarter left and one that is halved three times has an eighth left, never nothing at all. Its activity to fall to zero is wrong because the activity falls by half at every step and so approaches zero without reaching it. All of its nuclei to decay is wrong on the same grounds, since even after four half-lives one sixteenth still remains. Its nuclei to double in number describes the opposite process, which is what happens in a fusion chain rather than in decay.\n\nWatch out: thinking decay can be sped up or slowed down. No change of temperature, pressure or chemical combination affects it, and the activity, not the time, is halved each half-life.\n\nIn short: alpha is a helium nucleus, beta an electron, gamma an electromagnetic ray, and half the nuclei decay every half-life without ever reaching zero.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Electronics',
    qt: ['Electronics'],
    title: 'Semiconductors, diodes and logic gates',
    body: 'Electronics covers semiconductor materials, doping to produce n-type and p-type material, the p-n junction diode, the transistor, rectification, sensors, logic gates and the use of capacitors for smoothing. It is the newest topic on the syllabus and its questions are short recall or simple reasoning.\n\nHere\'s the idea: a semiconductor conducts between an insulator and a metal, and doping decides whether the free charge carriers are electrons or holes, while a diode uses that two-type structure to let current pass in one direction only.\n\nStep 1 - Classify the impurity: a pentavalent impurity has five outer electrons and donates a free electron, giving n-type material, while a trivalent impurity has three outer electrons and leaves a hole, giving p-type material.\nStep 2 - Recall the rest of the building blocks: the semiconductor diode conducts in one direction only, rectification is the conversion of AC into DC, and a transistor has three terminals and works as an amplifier or a switch.\nStep 3 - Work through the logic gates: an OR gate gives output 1 when at least one input is 1, an AND gate gives output 1 only when all inputs are 1, and a NOT gate always gives the opposite of its input.\nStep 4 - Use the sensors: the resistance of an LDR falls as light intensity increases and the resistance of a thermistor falls as temperature rises, so either can switch a lamp on automatically when it gets dark.\n\nExample: The majority charge carriers in a p-type semiconductor are: The options are electrons, protons, neutrons and holes. The answer is holes. Silicon has four outer electrons, and doping it with a trivalent impurity such as indium or aluminium leaves one electron short at each doped site, and each of these vacancies behaves as a mobile positive carrier called a hole. Electrons are the majority carriers only in n-type material made with a pentavalent impurity. Protons and neutrons are nuclear particles that are not free to move through the lattice, and a semiconductor is always electrically neutral overall, so there is no excess of either sign, only a difference in which carrier is more numerous.\n\nWatch out: confusing the two kinds of doping and the two carriers. N-type means pentavalent and electrons, p-type means trivalent and holes, and the resistance of an LDR falls as the light gets stronger rather than weaker.\n\nIn short: pentavalent gives n-type and electrons, trivalent gives p-type and holes, and the diode passes current one way only.'
  },
  { subject: 'Physics', type: 'sheet', topic: 'Formula sheet', title: 'Formulas worth memorising', body: '- Force: F = ma\n- Work: W = F s cos(theta); 1 J = 1 N m\n- Kinetic energy: KE = 1/2 mv^2; potential energy: PE = mgh\n- Power: P = W/t = Fv, in watts\n- Equations of motion: v = u + at, s = ut + 1/2 at^2, v^2 = u^2 + 2as\n- Projectile range: R = u^2 sin(2 theta)/g; time of flight: t = 2u sin(theta)/g\n- Momentum: p = mv; impulse = Ft = change in momentum\n- Pressure: P = F/A; liquid pressure: p = density x g x h\n- Efficiency: useful output / input x 100 = mechanical advantage / velocity ratio x 100\n- Heat: Q = mc delta T; change of state: Q = mL\n- Wave speed: v = f lambda; period: T = 1/f\n- Mirror formula: 1/f = 1/u + 1/v (real quantities positive)\n- Lens formula: 1/f = 1/v - 1/u; magnification = image height / object height\n- Lens power: P = 1/f, with f in metres, in dioptres\n- Ohm\'s law: V = IR; series: R = R1 + R2 + R3; parallel: 1/R = 1/R1 + 1/R2\n- Electrical power: P = VI = I^2 R = V^2/R; energy = power x time\n- Refractive index: n = c/v; critical angle: sin C = 1/n\n- Simple pendulum: T = 2 pi sqrt(L/g); SHM acceleration: a = -(omega^2) x\n- Circular motion: F = mv^2/r, a = v^2/r, time for one revolution = 2 pi r / v\n- Gravitation: F = G m1 m2 / r^2; weight: W = mg\n- Transformer: Vs/Vp = Ns/Np; force on a conductor: F = BIL' },
  { subject: 'Physics', type: 'sheet', topic: 'Units and constants', title: 'SI units and standard values', body: '- SI base units: metre, kilogram, second, ampere, kelvin, mole, candela\n- Derived units: force N, work and energy J, power W, pressure Pa, frequency Hz, charge C, resistance ohm, magnetic flux density T, activity Bq, lens power D\n- Speed of light in vacuum: 3 x 10^8 m/s\n- Acceleration due to gravity: g = 10 m/s^2, about 9.8 m/s^2; on the moon g = 1.6 m/s^2\n- Speed of sound in air at room temperature: about 340 m/s; fastest in steel, slowest in air\n- Atmospheric pressure at sea level: about 1 x 10^5 Pa\n- Density of water: 1000 kg/m^3\n- Specific heat capacity of water: 4200 J/kg K; specific latent heat of fusion of ice: 3.36 x 10^5 J/kg\n- Heat capacity of a sample has unit J/K; specific heat capacity has unit J/kg K\n- Normal near point of the human eye: 25 cm; audible range: 20 Hz to 20,000 Hz\n- 1 horsepower = 746 W; 1 kWh = 3.6 x 10^6 J; 1 W = 1 J/s\n- 72 km/h = 20 m/s (divide by 3.6); K = degrees Celsius + 273\n- Escape velocity from the earth: about 11.2 km/s; g is greatest at the poles\n- Weight on the moon is about one sixth of the weight on the earth; mass never changes\n- Carbon-14 half-life: about 5730 years; after 2 half-lives one quarter of the sample remains\n- Useful numbers: pi = 22/7, sin(45 degrees) = 0.707, sqrt(2) = 1.414' },
  { subject: 'Physics', type: 'sheet', topic: 'Definitions', title: 'Definitions to learn word for word', body: '- Scalar: a quantity with magnitude only. Vector: a quantity with magnitude and direction\n- Speed: distance travelled per unit time. Velocity: displacement per unit time\n- Acceleration: the rate of change of velocity, a = (v - u)/t\n- Inertia: the tendency of a body to remain at rest or to continue uniform motion unless a resultant force acts\n- Momentum: mass x velocity, unit kg m/s. Impulse: force x time, unit N s\n- Work: force x distance moved in the direction of the force, unit J\n- Power: the rate of doing work, unit W\n- Efficiency: useful work output divided by energy input, expressed as a percentage\n- Pressure: force per unit area, unit Pa. Density: mass per unit volume\n- Specific heat capacity: heat needed to raise 1 kg of a substance by 1 degree Celsius\n- Specific latent heat: heat needed to change the state of 1 kg of a substance with no change in temperature\n- Frequency: complete vibrations per second, unit Hz. Period: time for one vibration\n- Wavelength: distance between two consecutive points in phase. Amplitude: maximum displacement from equilibrium\n- Refractive index: ratio of the speed of light in vacuum to the speed in the medium\n- Critical angle: the angle of incidence in the denser medium that gives an angle of refraction of 90 degrees\n- Magnification: image height divided by object height\n- Half-life: the time taken for half of the nuclei present in a radioactive sample to decay\n- Rectification: the conversion of alternating current into direct current' }
);