/* Revision notes for History */
window.NOTES = window.NOTES || [];
window.NOTES.push(
  {
    subject: 'History',
    type: 'note',
    topic: 'Ancient kingdoms',
    title: 'Kingdoms before the Europeans arrived',
    body: 'Long before European ships appeared on the coast, the lands that now make up Nigeria and their neighbours held a crowd of well-organised states, each with its own titles, army and trade. Examiners rarely ask for narrative here; they ask which state did what, so attach every title to its people.\n\n- The Oyo Empire had the Alaafin as political head, checked by the Oyo Mesi council under the Bashorun, with the Are-Ona Kakanfo as commander-in-chief; its cavalry was the source of its strength.\n- Kanem-Bornu, which traded salt and cloth with North Africa across the Sahara, was ruled by kings titled Mai, and from the 15th century its capital was Birni Ngazargamu.\n- The seven Hausa states, the Hausa Bakwai, are traditionally said to have been founded by descendants of Bayajidda; Kano grew famous for textile dyeing and its dye pits, while Gobir later became the stronghold from which the Sokoto Jihad was launched.\n- In the Yoruba heartland, Ile-Ife is regarded as the cradle of Yoruba civilisation and is linked to Oduduwa; the first Oba of Benin was Eweka I, Oba Ewuare I is credited with building the great walls, and the palace plaques were made by the lost-wax casting technique.\n- Igbo society was acephalous and democratic, with Nri holding priestly authority and the Aro Chukwu oracle at Arochukwu; the Igbo-Ukwu bronzes were excavated in 1959 by Thurstan Shaw in present-day Anambra State.\n- The Jukun of Kwararafa sat along the Benue valley, the Nupe along the Niger, and the Ekpe secret society belonged to the Efik and Ibibio.\n\nTitles such as Alaafin, Mai, Shehu, Ooni and Obi are favourite options; know the people before you pick one.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'Trans-Saharan trade',
    title: 'Caravans, gold, salt and the empires',
    body: 'The Sahara shaped trade rather than stopping it. For centuries camel caravans carried salt south and gold north, and the states that straddied the crossings grew wealthy on tolls, taxes and the towns that served the caravans.\n\n- The Ghana Empire of the Soninke stood in present-day Mauritania and western Mali and derived its wealth mainly from the gold and salt trade.\n- The Mali Empire was founded in the 13th century by Sundiata Keita, and Mansa Musa\'s 1324 pilgrimage to Mecca displayed Mali\'s wealth so vividly that it brought the empire to world attention.\n- The Songhai Empire of the Middle Niger was founded by Sunni Ali Ber, was reorganised and given a firmer Islamic administration by Askia Muhammad, and was destroyed by the Moroccan invasion of 1591 launched by Ahmad al-Mansur of Morocco.\n- Timbuktu became a great centre of learning because of the Sankore scholars, while the Tarikh al-Sudan and Tarikh al-Fattash preserve the written history of the western Sudan.\n- Kanem-Bornu carried on long-distance trade in salt and cloth with North Africa across the Sahara, and the dyed cloth of Kano fed those same desert markets.\n\nThe pattern is simple: whoever controlled a well or a crossing controlled the trade, and whoever controlled the trade built an empire.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'Sokoto Caliphate',
    title: 'How the caliphate began and ran',
    body: 'The Sokoto Jihad of 1804 began as a religious and social reform movement. Usman dan Fodio had preached for years that the Hausa rulers were corrupt and unjust, and a quarrel with the ruler of Gobir turned teaching into war.\n\n- The immediate trigger was the conflict between Usman dan Fodio and Sarki Yunfa of Gobir in 1804, and Gobir was the stronghold from which the movement was launched.\n- Abdullahi dan Fodio was the chief ideologue who wrote the treatises justifying the jihad, while Muhammad Bello organised the administration of the new state.\n- The jihadists conquered the Hausa states of Kano and Katsina in 1804-1805, and the movement is classified as a religious and social reform movement rather than a war for trade routes or an anti-colonial war.\n- The supreme ruler of the caliphate bore the title Shehu, whose seat at Sokoto later passed to a line of sultans, and the conquered lands were organised into provinces known as emirates, each run by an appointed emir.\n- With Sokoto as its capital, the caliphate became the largest state in West Africa, blending Islamic law with the existing emirate structures.\n- The British conquest was completed in 1903 when Sultan Attahiru I was defeated at Burmi, ending independent caliphate rule.\n\nThe sequence to recall is preach, quarrel with the emir, conquer the Hausa states, then govern through emirs.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'British colonialism',
    title: 'From the Lagos bombardment to Lugard',
    body: 'British rule in Nigeria was assembled in pieces between the 1850s and 1914, first along the coast, then up the rivers and finally across the savannah, and each stage has a date attached to it.\n\n- The bombardment of Lagos in 1851 was justified by the British as an effort to suppress the slave trade, and Lagos was formally annexed in 1861.\n- The Royal Niger Company, originally promoted by George Taubman Goldie, held chartered trading rights over the lower Niger before the Crown took over the territory.\n- The Berlin Conference of 1884-1885, attended only by European powers and the United States, laid down the rules for the European partition of Africa, and King Leopold II personally owned the Congo Free State.\n- The punitive expedition against Benin in 1897 exiled Oba Ovonramwen and removed the Benin bronzes to Europe, and the Sokoto Caliphate finally fell in 1903.\n- Lord Lugard\'s policy of indirect rule was carried out through native authorities and traditional rulers. It worked most successfully in the Northern Region, where the emirate system was intact, but met stiff resistance in Eastern Nigeria, where imposed warrant chiefs lacked local legitimacy and provoked the 1929 Women\'s War against the proposed taxation of women.\n- On 1 January 1914 the Northern and Southern Protectorates were amalgamated into a single country.\n\nIndirect rule is the theme examiners return to again and again: it fitted strong traditional structures and failed where they had to be invented.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'Nationalism',
    title: 'Parties, the press and protest',
    body: 'Nigerian nationalism was carried by newspapers, associations and parties, but it never fully escaped the regions in which each leader was rooted, and that weakness shaped everything that followed.\n\n- The elective principle of the Clifford Constitution of 1922 created elected African seats on the Legislative Council, and the Nigerian National Democratic Party, founded in 1923 under Herbert Macaulay, dominated those Lagos elections.\n- The Nigerian Youth Movement, founded in 1938, counted Ernest Ikoli and Nnamdi Azikiwe among its founders and gave southern professionals a national platform.\n- The National Council of Nigeria and the Cameroons was founded in 1944 by Herbert Macaulay and Nnamdi Azikiwe, and Azikiwe\'s newspaper, the West African Pilot, became a powerful voice of nationalism.\n- The Action Group was founded in 1951 by Obafemi Awolowo in the Western Region, and the Western Region government he led introduced the first free primary education scheme in 1955; the Northern People\'s Congress was dominated by Ahmadu Bello and Tafawa Balewa; the Northern Elements Progressive Union, led by Aminu Kano, attacked the feudal emirate establishment.\n- Anthony Enahoro moved the 1953 motion demanding self-government by 1956, and the Kano riots of 1953 exposed northern suspicion of southern politicians.\n- Labour added pressure: Michael Imoudu led the general strike of 1945, and the Iva Valley massacre of coal miners in Enugu in 1949 hardened opinion against colonial rule.\n\nThe weakness examiners look for is strong regional and ethnic loyalties, which turned a single national cause into three regional ones.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'Independence',
    title: 'The road to 1 October 1960',
    body: 'Independence came to British West Africa in the 1950s, and Nigeria\'s own date was fixed by constitutional conferences abroad rather than by armed confrontation at home.\n\n- The Gold Coast gained independence as Ghana on 6 March 1957 under Kwame Nkrumah, whose Convention People\'s Party was founded in 1949 and whose Positive Action campaign of 1950 used boycotts, strikes and civil disobedience.\n- The Big Six, detained after the 1948 Accra riots, were led by Nkrumah, and the Fifth Pan-African Congress in Manchester in 1945 had demanded immediate self-government.\n- Guinea gained independence in 1958 under Ahmed Sekou Toure after voting against remaining in the French Community, while Leopold Sedar Senghor led Senegal to independence as a celebrated poet of the Negritude movement.\n- In Nigeria the London constitutional conference of 1957 produced the Lyttleton Constitution, which introduced ministerial government at the centre.\n- Nigeria gained independence on 1 October 1960 as a federation within the Commonwealth, with Tafawa Balewa as prime minister under a parliamentary system.\n- The Republican Constitution of 1963 made Nigeria a sovereign republic, and Nnamdi Azikiwe became the first President of Nigeria.\n\nTwo dates carry most of the marks: 6 March 1957 for Ghana and 1 October 1960 for Nigeria.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'Post-independence',
    title: 'The First and Second Republics',
    body: 'The First Republic lasted barely six years, and everything that went wrong in it was visible before 1966: regional parties, disputed elections and a centre that no region fully trusted.\n\n- The 1962 crisis in the Western Region began with the split in the Action Group between Awolowo and Akintola, and Chief Obafemi Awolowo was convicted of treasonable felony in 1963.\n- The 1964 federal election was widely criticised for widespread malpractice and manipulation, and the disputed census counts of the early 1960s deepened the quarrel between the regions.\n- Government rested on alliances between the Northern People\'s Congress and the NCNC, while the Action Group and later smaller parties sat in opposition, so every issue became a regional one.\n- The coup of 15 January 1966 ended the Republic and began long years of soldier rule, broken only by the Second Republic from 1979.\n- The 1979 Constitution returned the country to a presidential system, and Shehu Shagari of the NPN won that election and was re-elected in 1983, only to be overthrown on 31 December 1983.\n\nThe link examiners want you to make is between weak national party organisation and the ease with which the army repeatedly took power.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'Military rule',
    title: 'Coups, civil war and junta rule',
    body: 'From 1966 onwards Nigeria was governed by soldiers for all but a few years, and the pattern repeated itself: a coup, a promise of reform, then an exit forced by crisis.\n\n- The first military coup took place on 15 January 1966 and installed Johnson Aguiyi-Ironsi as head of state; the counter-coup of 19 July 1966 killed him and installed Yakubu Gowon.\n- Gowon reorganised Nigeria into twelve states in 1967, and on 30 May 1967 Chukwuemeka Odumegwu Ojukwu proclaimed the Eastern Region the Republic of Biafra.\n- The Aburi meeting of January 1967, held in Ghana, failed to settle the dispute; the Nigerian Civil War began in July 1967 and ended in January 1970, and the naval blockade of Biafra caused mass starvation.\n- Gowon adopted the slogan no victor, no vanquished, was overthrown in 1975, and Murtala Mohammed was killed in the attempted coup of 1976.\n- Muhammadu Buhari ruled from 1983 to 1985, then Ibrahim Babangida seized power on 19 August 1985 and introduced the Structural Adjustment Programme in 1986 on the advice of the IMF and World Bank.\n- Babangida annulled the presidential election of 12 June 1993, believed won by Moshood Abiola, and handed power to Ernest Shonekan\'s Interim National Government; Sani Abacha took over in November 1993 and died in June 1998.\n- Abdulsalami Abubakar handed over in 1999 under the 1999 Constitution, opening the Fourth Republic.\n\nLearn the sequence and the years together; the order of the coups is itself a syllabus theme.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'Constitutions',
    title: 'Every Nigerian constitution in order',
    body: 'Nigeria has been governed under a long parade of constitutions, and examiners usually ask what each one introduced, how many regions existed and who criticised it.\n\n- The Clifford Constitution of 1922 introduced the elective principle, giving elected African members seats on the Legislative Council in Lagos.\n- The Richards Constitution of 1946 divided Nigeria into the Eastern, Western and Northern Regions while keeping a strong centre.\n- The Macpherson Constitution of 1951 provided for elections to the House of Representatives, but it was criticised mainly because it made the centre too strong and lacked popular consultation.\n- The Lyttleton Constitution of 1957 introduced ministerial government at the centre, preparing the way for self-government.\n- The Independence Constitution of 1960 established Nigeria as a federation within the Commonwealth, and the Republican Constitution of 1963 made it a sovereign republic with an elected president.\n- The 1979 Constitution introduced a presidential system and required a presidential candidate to score at least 25 percent of the votes in two-thirds of the states, a threshold repeated in later elections.\n- The 1999 Constitution, promulgated by the military government, ushered in the Fourth Republic.\n\nMatch constitution to year first, then to the single feature each one is famous for.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'Economy and development',
    title: 'Cash crops, oil and adjustment',
    body: 'Nigeria\'s economy was shaped first by colonial export demands and later by petroleum, and each phase left behind a different problem that governments then had to manage.\n\n- Under colonial rule the hinterland was linked to the ports by railway so that cash crops and minerals could be exported: cocoa, groundnuts, palm produce and cotton went abroad, while tin was mined on the Jos plateau.\n- Groundnut pyramids in Kano and cocoa heaps in the West were the visible signs of a peasant export economy in which taxes were paid out of farm proceeds.\n- Oil was struck at Oloibiri in 1956, and by the 1970s petroleum dominated both exports and government revenue.\n- The indigenisation decrees of the 1970s increased Nigerian ownership of companies, while the civil war years had shown how vulnerable a blockaded region could become.\n- When oil earnings fell, the Structural Adjustment Programme of 1986 was introduced on the advice of the IMF and World Bank, bringing devaluation, cuts in subsidies and a long spell of hardship for ordinary households.\n- The lesson examiners want is that dependence on a single export leaves the whole economy at the mercy of one world price.\n\nLink each policy to the problem it was meant to solve, and the chronology holds itself together.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'International relations',
    title: 'Nigeria and the wider world',
    body: 'Nigeria entered world politics as a newly independent state in 1960 and tied itself quickly to African and Commonwealth institutions, while officially refusing to join either Cold War bloc.\n\n- Nigeria pursued non-alignment, keeping clear of both the Western and the Soviet camps while dealing with each of them.\n- The Organisation of African Unity was founded in 1963 at Addis Ababa, where its headquarters has remained; it upheld respect for inherited colonial boundaries and, during the Nigerian Civil War, mediated while accepting Nigeria\'s unity.\n- The Economic Community of West African States was established by the Treaty of Lagos in 1975 to promote free trade and economic cooperation among West African states.\n- The United Nations was founded in 1945, replacing the League of Nations, which had been formed after the First World War to preserve world peace.\n- Pan-Africanism fed this outlook: the first Pan-African Conference met in London in 1900, W.E.B. Du Bois organised congresses in 1919, 1921, 1923 and 1927, and the Fifth Pan-African Congress in Manchester in 1945 demanded immediate self-government.\n\nExaminers like pairs, so fix each body to its founding year and city: OAU 1963 Addis Ababa, ECOWAS 1975 Lagos, United Nations 1945.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'Historical sources',
    title: 'Where history comes from and how',
    body: 'Every history answer depends on evidence, and the syllabus expects you to classify a source before you use it, because classification decides how far it can be trusted.\n\n- A primary source comes from someone who actually witnessed the event, such as a diary, a speech or an eyewitness report, while a secondary source interprets primary material, so a textbook is secondary.\n- Oral tradition carries the history of societies that left no written records, and a praise-poem such as the oriki, which recounts a king\'s achievements, is one form of it.\n- Its weaknesses are the marks examiners reward: a praise singer exaggerates his king\'s exploits in order to gain rewards, which is bias, and meaning may also be distorted in the course of transmission.\n- Indigenous written sources include the Kano Chronicle and the Chronicle of Borgu, while the Tarikh al-Sudan and the Tarikh al-Fattash cover the western Sudan and Timbuktu.\n- Ibn Khaldun\'s Muqaddimah is regarded as a landmark in the scientific study of history, and Herodotus is called the Father of History because he systematically collected and recorded the accounts of the peoples he studied.\n- Archaeology supplies hard dating: stratigraphy reads the layers of earth to establish the sequence of occupation, radio-carbon dating measures carbon-14 in organic material, numismatics studies ancient coins, and palaeography examines old manuscripts.\n\nClassify the source first, then judge its reliability; most wrong answers come from skipping that first step.'
  },
  {
    subject: 'History',
    type: 'sheet',
    topic: 'Key dates',
    title: 'Nigerian dates to recall cold',
    body: '- 1804 — Usman dan Fodio launches the Sokoto Jihad\n- 1851 — British bombardment of Lagos\n- 1861 — Lagos formally annexed by Britain\n- 1884-1885 — Berlin Conference lays down the rules for the partition of Africa\n- 1897 — Benin Expedition; Oba Ovonramwen exiled\n- 1903 — Sultan Attahiru I defeated at Burmi, Sokoto Caliphate falls\n- 1 January 1914 — amalgamation of the Northern and Southern Protectorates\n- 1922 — Clifford Constitution introduces the elective principle\n- 1929 — Women\'s War of the Eastern Region\n- 1945 — general strike led by Michael Imoudu; United Nations founded\n- 1946 — Richards Constitution divides Nigeria into three regions\n- 1951 — Macpherson Constitution provides for elections to the House of Representatives\n- 1953 — Anthony Enahoro moves the self-government motion; Kano riots\n- 6 March 1957 — Gold Coast becomes Ghana\n- 1957 — Lyttleton Constitution introduces ministerial government at the centre\n- 1 October 1960 — Nigeria gains independence as a federation in the Commonwealth\n- 1 October 1963 — Nigeria becomes a sovereign republic\n- 15 January 1966 — first military coup; Aguiyi-Ironsi takes over\n- 19 July 1966 — counter-coup installs Yakubu Gowon\n- 30 May 1967 — Ojukwu proclaims the Republic of Biafra\n- January 1970 — Nigerian Civil War ends; no victor, no vanquished\n- 1975 — Treaty of Lagos establishes ECOWAS\n- 1979 — Second Republic opens under the presidential constitution\n- 31 December 1983 — Shehu Shagari overthrown\n- 19 August 1985 — Babangida seizes power\n- 1986 — Structural Adjustment Programme introduced\n- 12 June 1993 — presidential election annulled\n- June 1998 — Sani Abacha dies in office\n- 1999 — 1999 Constitution opens the Fourth Republic'
  },
  {
    subject: 'History',
    type: 'sheet',
    topic: 'Wars and treaties',
    title: 'Wars and treaties worth naming',
    body: '- Sokoto Jihad, 1804-1805 — Kano and Katsina fall to the jihadists\n- British abolition of the Atlantic slave trade, 1807; Emancipation Act in the colonies, 1833\n- Asiento granted to Britain, 1713 — right to supply slaves to Spanish colonies\n- Anglo-Asante wars — fought over control of the Gold Coast hinterland\n- Hut Tax War, 1898, Sierra Leone — led by Bai Bureh\n- Anglo-Zulu War, 1879 — defeat of the Zulu Kingdom\n- Yaa Asantewaa War, 1900 — Asante resistance after Prempeh I was exiled to Seychelles\n- Maji Maji Rebellion, 1905-1907 — against German rule in Tanganyika\n- Herero and Nama rebellion — against German rule in German South West Africa\n- Battle of Adwa, 1896 — Menelik II\'s Ethiopians defeat the Italians\n- Samori Toure founded the Wassoulou Empire and was captured by the French in 1898\n- Benin Expedition, 1897 — bronzes removed to Europe, Oba exiled\n- Berlin Conference, 1884-1885 — rules for the European partition of Africa\n- Treaty of Versailles, 1919 — ends the First World War and penalises Germany\n- Aburi meeting, January 1967, Ghana — Gowon and Ojukwu fail to agree\n- Nigerian Civil War, July 1967 to January 1970\n- Treaty of Lagos, 1975 — establishes ECOWAS\n- Battle of Burmi, 1903 — Sultan Attahiru I defeated by the British'
  },
  {
    subject: 'History',
    type: 'sheet',
    topic: 'People and offices',
    title: 'People and offices to match',
    body: '- Usman dan Fodio — founder of the Sokoto Caliphate in 1804\n- Abdullahi dan Fodio — chief ideologue who wrote treatises justifying the jihad\n- Muhammad Bello — son of Usman and organiser of the caliphate\'s administration\n- Sarki Yunfa of Gobir — ruler whose quarrel with Usman triggered the jihad\n- Shehu — title of the supreme ruler of the Sokoto Caliphate\n- Alaafin — political head of the Oyo Empire\n- Bashorun — head of the Oyo Mesi council that checked the Alaafin\n- Are-Ona Kakanfo — commander-in-chief of the Oyo army\n- Mai — title of the kings of Kanem-Bornu\n- Emir — governor of a province of the Sokoto Caliphate\n- Eweka I — first Oba of Benin; Oba Ewuare I built the great walls\n- Oba Ovonramwen — exiled after the British expedition of 1897\n- Queen Amina of Zaria — warrior queen who expanded Zazzau by conquest\n- Thurstan Shaw — excavated the Igbo-Ukwu bronzes in 1959\n- Kenneth Onwuka Dike — author of Trade and Politics in the Niger Delta\n- Herbert Macaulay — founded the NNDP in 1923 and co-founded the NCNC in 1944\n- Nnamdi Azikiwe — founder of the West African Pilot and first President of Nigeria\n- Obafemi Awolowo — founded the Action Group in 1951 and the 1955 free primary scheme\n- Anthony Enahoro — moved the 1953 self-government motion\n- Aminu Kano — led the Northern Elements Progressive Union against the emirate establishment\n- Kwame Nkrumah — founded the CPP in 1949 and led Ghana to independence in 1957\n- Lord Lugard — pioneer of indirect rule and the 1914 amalgamation'
  }
);
