/* Revision notes for Biology */
window.NOTES = window.NOTES || [];
window.NOTES.push(
  {
    subject: 'Biology',
    type: 'note',
    topic: 'Cell biology',
    title: 'Reading a cell the way UTME asks',
    body: 'Every living thing is built from cells, and the cell is the smallest unit that shows all the features of life. UTME tests cell structure constantly, usually by describing a job and asking you to name the organelle that does it, so the fastest way to score is to link each organelle to its single function. Prokaryotic cells such as bacteria have no membrane-bound nucleus, while eukaryotic cells keep their DNA inside a nucleus.\n\nHere\'s the idea: a UTME cell question is a question about function wearing a question about structure. Name the job first, and the organelle follows; the list of organelles on its own is worth nothing in the exam hall.\n\nStep 1 - Read the question for the job being described, not for the names sitting in the options.\nStep 2 - Compress the job into one label: aerobic respiration, photosynthesis, protein synthesis, digestion inside the cell, control of entry and exit.\nStep 3 - Name the organelle that does that job: mitochondrion, chloroplast, ribosome, lysosome, cell membrane.\nStep 4 - Strike out options that name a structure rather than an organelle, such as cell wall or cytoplasm, unless the question is plainly asking for a structure.\n\nExample: The question reads, "Which organelle is commonly called the powerhouse of the cell?", with options Nucleus, Ribosome, Mitochondrion and Vacuole. Mitochondrion is correct, because aerobic respiration runs on its inner membrane and traps the released energy as ATP. Nucleus fails: it holds DNA and directs cell activities but releases no energy. Ribosome fails: it assembles proteins, and protein synthesis is not respiration. Vacuole fails: it stores cell sap and keeps the plant cell turgid. Notice that the question never mentions respiration at all, so you have to recognise the nickname and then verify it against the function.\n\nWatch out: chloroplast and mitochondrion get swapped more than any other pair. A chloroplast traps light energy and builds glucose, giving out oxygen; a mitochondrion breaks glucose down with oxygen, giving out carbon dioxide, water and energy. One stores energy in, the other releases energy out, and a plant cell has both.\n\nIn short: read the function, name the organelle that performs it, and keep photosynthesis and respiration on opposite sides of the same equation.'
  },
  {
    subject: 'Biology',
    type: 'note',
    topic: 'Classification',
    title: 'The ladder and the two-part name',
    body: 'Classification groups organisms so that they can be identified and studied, and the system in use today was set up by Carolus Linnaeus, who also introduced binomial nomenclature. UTME asks two kinds of question here: which rank is the largest or smallest, and which word of a scientific name carries which rank. Both are quick once the ladder is fixed in memory.\n\nHere\'s the idea: the ranks run from kingdom down to species, and every step down shares more features, so the species is the only rank defined by what its members can do to each other. In the two-part name, the first word is the genus and the second, in lower case, is the specific epithet.\n\nStep 1 - Write the ladder from the top: kingdom, phylum, class, order, family, genus, species.\nStep 2 - For a "largest group" question, answer kingdom; for a "smallest taxonomic unit" question, answer species.\nStep 3 - For a binomial name, split it into two words and give the first word to the genus and the second to the species.\nStep 4 - Check the capital letters: the genus always starts with a capital and the specific epithet is always in lower case.\n\nExample: The question reads, "In the name Escherichia coli, the word Escherichia represents the:", with options Genus, Species, Family, Order. Genus is correct, because it is the first word and carries the capital letter. Species is the trap, since species is also part of the name, but the name ends with coli, so Escherichia is one rank higher. Family and Order are further up the ladder and are never written into the binomial name at all. A second question from the same family of ideas reads "The taxonomic group whose members can interbreed to produce fertile offspring is the:", where Species is right and Genus, Family and Phylum all fail because interbreeding fertility is a species-level test.\n\nWatch out: students reverse the direction of the ladder and call phylum the largest group. Phylum sits second from the top, below kingdom, and Chordata is only a phylum. Another common slip is writing the binomial in the wrong case, as Escherichia Coli; the capital belongs to the genus alone.\n\nIn short: kingdom is the top and species the bottom, the first word of a binomial is the genus, and the specific epithet is always in lower case.'
  },
  {
    subject: 'Biology',
    type: 'note',
    topic: 'Nutrition',
    title: 'Nutrients, enzymes and deficiency',
    body: 'Food supplies energy and the raw materials for growth, repair and maintenance, and UTME asks about it in two ways: which food class does which job, and which deficiency disease follows which shortage. The classes are macronutrients needed in large amounts and vitamins and mineral salts needed in tiny amounts, and confusing the two is the commonest loss of marks.\n\nHere\'s the idea: every deficiency disease has exactly one cause, so you do not need to memorise the whole table separately. Learn each disease as a single fixed pair, vitamin C with scurvy and vitamin D with rickets, and the pair cannot drift apart under pressure.\n\nStep 1 - Decide the size of the need: large amounts means macronutrient, tiny amounts means vitamin or mineral salt.\nStep 2 - Decide the function: energy-yielding, body-building, or regulating.\nStep 3 - Convert a deficiency question into a fixed pair, scurvy with C, rickets with D, night blindness with A, beriberi with B1, anaemia with iron, kwashiorkor with protein.\nStep 4 - Eliminate any option whose paired disease belongs to a different nutrient.\n\nExample: The question reads, "Rickets in children is caused by a deficiency of:", with options Vitamin A, Vitamin D, Vitamin B1 and Vitamin K. Vitamin D is correct, because rickets is the defective mineralisation of bone and cartilage in growing children, and vitamin D controls calcium and phosphate absorption. Vitamin A fails, because its deficiency gives night blindness, where the retina cannot respond in dim light. Vitamin B1 fails, because its deficiency gives beriberi, with nerve and heart involvement. Vitamin K fails, because its deficiency gives bleeding that does not clot. Only one of the four is paired to rickets, and the other three are all real vitamins carrying real diseases, so recognising each pair is what decides the answer.\n\nWatch out: the energy question is baited by giving fat the wrong label. Fat yields the most energy per gram, roughly twice that of carbohydrate or protein, so when the question asks for the class supplying the most energy per gram the answer is Fat, not Carbohydrate even though carbohydrate is the commoner fuel.\n\nIn short: fix each deficiency disease to its one nutrient, and remember that fat is the most concentrated energy source in the diet.'
  },
  {
    subject: 'Biology',
    type: 'note',
    topic: 'Transport systems',
    title: 'Blood, vessels and the plant pipeline',
    body: 'Diffusion alone cannot supply a large organism fast enough, so transport systems move materials actively. In humans the blood does the work, and in plants xylem and phloem divide the job between water and food. UTME draws freely on both, so keep the human system and the plant system clearly separate in your head.\n\nHere\'s the idea: every transport structure is defined by one thing it carries and one thing it does, so learn blood components as functions. Plasma carries dissolved food, urea, salts and carbon dioxide; red cells carry oxygen on haemoglobin; white cells fight infection; platelets clot.\n\nStep 1 - Name what is being carried: oxygen, dissolved food, urea, or a hormone.\nStep 2 - Choose the component: red cells for oxygen, plasma for dissolved substances, white cells for defence, platelets for clotting.\nStep 3 - For a vessel question, remember that arteries carry blood away from the heart and veins carry blood back, whatever the oxygen content.\nStep 4 - For a plant question, fix the two pipelines: xylem for water and mineral salts upward, phloem for dissolved food in either direction.\n\nExample: The question reads, "The blood group regarded as the universal donor is:", with options AB, A, B and O. O is correct, because group O red cells carry neither A nor B antigen, so a recipient of any group has no antibodies against them. A and B fail because their red cells each carry one antigen that a recipient without that antigen will attack. AB fails, because its red cells carry both antigens, so it can only be given to AB recipients. Now work the companion question, "A person with blood group O has which antigens on the red blood cells?" and the answer is No antigens, which is the same fact seen from the other side.\n\nWatch out: universal donor and universal recipient get reversed under pressure. Group O is the donor to everybody; group AB is the recipient from everybody, because AB plasma carries no anti-A or anti-B antibodies. Also remember an artery is defined by direction of flow away from the heart, not by carrying oxygen, which is why the pulmonary artery carries deoxygenated blood.\n\nIn short: learn each blood component by the job it does, fix O as universal donor and AB as universal recipient, and never judge a vessel by its oxygen content.'
  },
  {
    subject: 'Biology',
    type: 'note',
    topic: 'Respiration',
    title: 'Aerobic, anaerobic and the gas question',
    body: 'Respiration is the breakdown of food in living cells to release the energy that every life process needs, and it happens whether or not an animal is breathing. UTME asks two things about it: which gas is taken in and given out, and what the products are when oxygen is short. Aerobic respiration needs oxygen and yields carbon dioxide, water and energy in the mitochondrion; anaerobic respiration needs none and yields far less energy.\n\nHere\'s the idea: aerobic and anaerobic respiration are the same pathway run to different ends. Oxygen decides where the process stops, so learn one equation and then learn the two alternative endings rather than three separate stories.\n\nStep 1 - Ask whether oxygen is present.\nStep 2 - With oxygen, write glucose plus oxygen gives carbon dioxide plus water plus energy, in the mitochondrion.\nStep 3 - Without oxygen, decide the organism: muscle gives lactic acid, yeast gives ethanol plus carbon dioxide.\nStep 4 - Check the products against the reactant you are given, and delete any option that pairs the wrong gas.\n\nExample: The question reads, "Anaerobic respiration in yeast produces:", with options Lactic acid, Alcohol and carbon dioxide, Water and carbon dioxide, and Proteins. Alcohol and carbon dioxide is correct, because yeast is a fungus that ferments sugar away from oxygen into ethanol and carbon dioxide. Lactic acid is the trap lifted from animal muscle, where anaerobic respiration gives lactate instead; a candidate who has memorised anaerobic respiration in general but not the yeast case chooses it. Water and carbon dioxide fail because water is the product of the aerobic route only. Proteins fail outright, since protein is a food substance and not a respiratory product.\n\nWatch out: question writers like to place the carbon dioxide of yeast fermentation next to photosynthesis, and the two are easy to merge. In bread making the gas that makes the dough rise is carbon dioxide produced by the yeast anaerobic respiration, not oxygen from a plant, and no plant is involved in raising the loaf.\n\nIn short: oxygen present gives carbon dioxide, water and energy, oxygen absent gives lactic acid in muscle and ethanol plus carbon dioxide in yeast.'
  },
  {
    subject: 'Biology',
    type: 'note',
    topic: 'Excretion',
    title: 'Removing waste, and the kidney route',
    body: 'Excretion is the removal of the waste products of metabolism from the body, and left to accumulate they would poison the organism. UTME tests it in two ways: which organ or vessel does which job, and excretion against egestion or defecation. The excretory organs in humans are the kidneys, the lungs, the skin and the liver.\n\nHere\'s the idea: excretion means getting rid of metabolic waste, so the route matters more than the waste. Learn the pathway kidney to bladder to outside by its vessels, and every organ question falls into place.\n\nStep 1 - Identify the waste: urea from protein breakdown, carbon dioxide from respiration, excess salts and water.\nStep 2 - Identify the organ: kidney for urea, lungs for carbon dioxide, skin for water, salts and a little urea.\nStep 3 - For a vessel question, name the destination: to the kidney for the renal artery, from the kidney for the renal vein, kidney to bladder for the ureter.\nStep 4 - Rule out any option that removes undigested food, because that is egestion and not excretion.\n\nExample: The question reads, "Urine is conveyed from the kidney to the urinary bladder by the:", with options Urethra, Ureter, Renal artery and Vas deferens. Ureter is correct, because it is the muscular tube carrying urine down from the kidney to the bladder. Urethra is the trap, since it carries urine from the bladder out of the body, one stage later. Renal artery fails because it brings blood to the kidney for filtration rather than carrying urine away. Vas deferens fails because it carries sperm from the testis to the urethra in the male.\n\nWatch out: urea is a nitrogenous waste, not a general one, and the liver is where it is made. In deamination the liver strips the amino group from amino acids and converts the nitrogen into urea, which the kidneys then excrete. If a question asks which organ produces urea, the answer is the liver, even though the kidney is the organ that removes it.\n\nIn short: excretion is removal of metabolic waste, the ureter carries urine kidney to bladder, and the liver makes urea while the kidney filters it out.'
  },
  {
    subject: 'Biology',
    type: 'note',
    topic: 'Reproduction',
    title: 'Where each step happens',
    body: 'Reproduction keeps a species in existence, and in humans it runs from ovulation through fertilization to implantation and birth. UTME builds its questions around one word per step: ovulation, fertilization, implantation, parturition, and each of those words belongs to a different structure. Getting the structure order right is the whole game.\n\nHere\'s the idea: name the event and the structure follows, so memorise the sequence rather than a scattered list. The ovary releases, the oviduct receives and fertilises, the uterus carries and delivers, and the vagina is the exit.\n\nStep 1 - Identify the event word in the question: ovulation, fertilization, implantation or parturition.\nStep 2 - Attach it to its structure: ovary for ovulation, oviduct for fertilization, uterus for implantation and development, cervix and vagina for birth.\nStep 3 - For the flower question, use the same method: the anther produces pollen and the stigma receives it, so the stamen is male and the carpel is female.\nStep 4 - Eliminate any structure that belongs to a neighbouring step of the sequence.\n\nExample: The question reads, "Fertilization in humans normally takes place in the:", with options Uterus, Ovary, Fallopian tube and Vagina. Fallopian tube is correct, because it is the oviduct whose upper region is the usual site where the sperm meets the ovum. Uterus fails, because it is where the zygote implants and the foetus develops, not where fusion happens. Ovary fails, because the ovary only releases the mature ovum in ovulation. Vagina fails, because it is the birth canal and the route of menstrual flow, and the sperm enters it but does not fertilise there. The word "normally" in the stem is the clue that implantation normally follows fertilisation.\n\nWatch out: ovulation and fertilisation are confused because both involve the ovum leaving somewhere. Ovulation is the release of a mature ovum from the ovary and involves no sperm at all; fertilisation is the fusion of that ovum with a sperm. If sperm is mentioned anywhere in the stem, the answer is the oviduct.\n\nIn short: ovary releases, oviduct fertilises, uterus carries, vagina delivers, and anther produces pollen while stigma receives it.'
  },
  {
    subject: 'Biology',
    type: 'note',
    topic: 'Growth and development',
    title: 'Mitosis, meiosis and where plants grow',
    body: 'Growth is a permanent increase in size or in dry mass, and it comes from cell division adding numbers, cell expansion adding size, and cell differentiation creating specialised tissues. UTME asks about growth in two settings: the mechanism of division and the region of the plant where growth happens, and both reward a single clear distinction.\n\nHere\'s the idea: mitosis keeps the chromosome number exactly as it was and meiosis halves it. Every growth, repair and gamete question in UTME turns on which of those two is happening, so decide that before anything else.\n\nStep 1 - Ask whether the outcome is more cells of the same kind or gametes.\nStep 2 - Choose mitosis for growth, repair and asexual reproduction, since the chromosome number stays constant at 46 in human body cells.\nStep 3 - Choose meiosis for gamete formation, since the number is halved to 23, and place it in prophase I when crossing over occurs.\nStep 4 - For a plant region question, fix the sites: apical meristem for length, vascular cambium for girth in a dicot stem, root cap as a shield only.\n\nExample: The question reads, "The type of cell division that produces gametes is:", with options Mitosis, Meiosis, Binary fission and Budding. Meiosis is correct, because a gamete carries half the chromosome number of the body cell, 23 instead of 46 in humans, and only meiosis halves it. Mitosis fails, because it produces two genetically identical cells with the full number, which is what growth and repair use. Binary fission and budding are both methods of asexual reproduction used by bacteria and yeast, so neither halves anything and neither makes a gamete.\n\nWatch out: the zone-of-maturation question baits you with the root cap. The root cap is only a protective cap that is continually worn away as the root pushes through soil; the increase in length happens at the apical meristem just behind it, with the zone of maturation further up where cells finish differentiating and root hairs form.\n\nIn short: mitosis keeps 46 and builds and repairs, meiosis halves to 23 and makes gametes, and roots lengthen at the apical meristem behind the root cap.'
  },
  {
    subject: 'Biology',
    type: 'note',
    topic: 'Coordination',
    title: 'Brain parts and the neuron',
    body: 'Coordination lets an organism detect change and respond to it, and in animals it runs through the nervous system for fast short-lived responses and the endocrine system for slow long-lasting ones. UTME tests the brain part for the job and the neuron part for the direction of the impulse, and both are pure matching work.\n\nHere\'s the idea: attach one job to each part of the brain and never let the three great regions swap. The cerebrum thinks, the cerebellum balances, the medulla oblongata keeps the vital rhythms running, and the hypothalamus sits below the cerebrum controlling temperature, hunger and thirst.\n\nStep 1 - Identify the function named in the question: thinking, balance, breathing, or reflex action.\nStep 2 - Match it: cerebrum, cerebellum, medulla oblongata, or the spinal cord for a reflex arc.\nStep 3 - For a neuron question, mark direction: dendrons carry impulses towards the cell body, the axon carries them away, and the synapse is the gap between two neurons.\nStep 4 - For a sense organ question, match the receptor to its stimulus: rods to dim light, cochlea to sound, semicircular canals to balance.\n\nExample: The question reads, "The part of the brain that controls balance and posture is the:", with options Cerebrum, Medulla oblongata, Hypothalamus and Cerebellum. Cerebellum is correct, because it receives information from the semicircular canals, the eyes and the muscles and keeps the body upright and steady. Cerebrum fails, because it deals with thought, memory and voluntary action. Medulla oblongata fails, because it sets the rhythm of breathing and heartbeat rather than posture. Hypothalamus fails, because it monitors blood temperature, hunger and thirst and drives the pituitary, not balance. Three of the four options are real parts of the brain, so only the job decides.\n\nWatch out: rods and cones get reversed in dim-light questions. Rods are the receptors that work in dim light and give poor colour vision, which is why you see in black and white at night; cones need bright light and give colour. If the stem says dim light or night vision, the answer is rods, not cones.\n\nIn short: cerebrum thinks, cerebellum balances, medulla runs the vital rhythms, dendrons carry impulses in and the axon carries them out.'
  },
  {
    subject: 'Biology',
    type: 'note',
    topic: 'Genetics',
    title: 'Crosses, ratios and the two numbers',
    body: 'Genes are the functional units of heredity, carried on chromosomes in the nucleus, and they pass traits from parent to offspring. UTME builds genetics questions around Mendel\'s crosses and around two ratios that students constantly confuse, so this topic is mostly about keeping numbers apart.\n\nHere\'s the idea: the F2 generation of a monohybrid cross has two ratios, and they are different quantities. The genotypic ratio counts allele combinations and is one to two to one; the phenotypic ratio counts what you can see and is three to one.\n\nStep 1 - Draw the parental cross and the F1, where all offspring are heterozygous if the parents are homozygous.\nStep 2 - Work the F2 genotypic ratio from the Tt by Tt square: one TT, two Tt, one tt.\nStep 3 - Convert to phenotypes: TT and Tt both show the dominant trait, tt shows the recessive, giving three to one.\nStep 4 - Read the stem carefully. If it says genotypic, answer one to two to one; if phenotypic, answer three to one.\n\nExample: The question reads, "The phenotypic ratio of the F2 generation of a monohybrid cross is:", with options One to one, Nine to three to three to one, Three to one, and One to two to one. Three to one is correct, because in the Tt by Tt square the offspring are one TT, two Tt and one tt, and since T is dominant the three types TT and Tt look alike, giving three tall to one short. One to two to one fails because it is the genotypic ratio, the count of allele combinations rather than of appearances. Nine to three to three to one fails because that is the F2 phenotypic ratio of a dihybrid cross, involving two genes at once, not one. One to one is the test cross ratio, not the monohybrid F2.\n\nWatch out: blood group genotypes are read as alleles, not as antigens, and a question about a person of group O has only one possible answer, ii, because O carries neither antigen. Group AB is therefore I^A I^B. Treating the letters O and AB as a single allele is the slip that loses marks here.\n\nIn short: F2 genotypes run one to two to one, F2 phenotypes run three to one, and a dihybrid cross gives nine to three to three to one.'
  },
  {
    subject: 'Biology',
    type: 'note',
    topic: 'Evolution',
    title: 'How to read the evidence',
    body: 'Evolution is the gradual change in the characteristics of a population over many generations, and Darwin explained it by natural selection. UTME tests the mechanism and it tests the evidence, and the evidence questions all rest on one distinction: same structure with a different job, against a different structure doing the same job.\n\nHere\'s the idea: homologous structures share an origin but differ in function, which points to a common ancestor, while analogous structures share a function but differ in origin, which points to convergent evolution. Vestigial structures are reduced leftovers, and the human appendix is the standard example.\n\nStep 1 - Ask whether the two structures do the same job or different jobs.\nStep 2 - Same origin, different function means homologous and evidence of common ancestry.\nStep 3 - Same function, different origin means analogous and evidence of convergence, as with the wing of a bird and the wing of an insect.\nStep 4 - For the mechanism, write the chain: variation, overproduction, struggle, survival of the fittest, inheritance, and change over generations.\n\nExample: The question reads, "The forelimbs of a whale and a bat are examples of:", with options Analogous structures, Vestigial structures, Adaptive structures and Homologous structures. Homologous is correct, because both are built from the same bone plan of humerus, radius and ulna, inherited from a common vertebrate ancestor, even though one is a flipper for swimming and the other a wing for flight. Analogous fails, because that label needs the same function from a different origin, as with a bird wing against an insect wing. Vestigial fails, because these limbs are fully functional, not reduced leftovers. Adaptive structures fails because it is not a classification by structure at all but a description of usefulness, and the question is asking about shared origin.\n\nWatch out: the word adaptation tempts you into selecting Homologous as a synonym of useful. It is not. A structure can be perfectly adaptive and still be a recent acquisition with no ancestor behind it; the question about evidence is always asking about origin, and only origin decides homologous against analogous.\n\nIn short: same origin different function is homologous, same function different origin is analogous, and natural selection filters variation that mutation keeps supplying.'
  },
  {
    subject: 'Biology',
    type: 'note',
    topic: 'Ecology',
    title: 'Counting your way along a food chain',
    body: 'Ecology is the study of the relationship between organisms and their environment, and UTME tests it through food chains, energy flow and the relationships between species. A food chain question is mostly arithmetic, and the arithmetic fails only when you lose count of the levels.\n\nHere\'s the idea: a producer occupies level one and every step up is one order higher, so the consumer level equals the number of organisms in front of it in the chain. Energy flows one way and cannot be recycled, and only about ten per cent passes to each level above.\n\nStep 1 - Write the chain in order and count from the producer as one.\nStep 2 - Label by that count: the organism immediately after the producer is the primary consumer.\nStep 3 - For energy questions, remember that roughly ten per cent passes to the next level and the rest is lost as heat and waste.\nStep 4 - For a relationship question, ask who gains: both partners means mutualism, one gains and the other is unaffected means commensalism, and one gains at the expense of the other means parasitism.\n\nExample: The question reads, "In the food chain grass to grasshopper to lizard to snake, the lizard is a:", with options Producer, Primary consumer, Secondary consumer and Decomposer. Secondary consumer is correct, because grass is the producer at level one, the grasshopper eats the grass and is the primary consumer at level two, and the lizard eats the grasshopper and so is the secondary consumer at level three. Producer fails, since only the grass makes its own food. Primary consumer fails, since that is the grasshopper, the level immediately above the producer. Decomposer fails, since decomposers break down dead matter from every level rather than taking their place in the chain.\n\nWatch out: naming organisms from memory instead of counting them. The same lizard is a secondary consumer in a chain that begins with grass, and a tertiary consumer in a chain that begins with a plant eaten by a herbivorous insect. Always count from the producer before you name the level.\n\nIn short: count from the producer as level one, remember about ten per cent energy transfer, and name relationships by who gains and who loses.'
  },
  {
    subject: 'Biology',
    type: 'sheet',
    topic: 'Classification',
    title: 'The classification ladder',
    body: '- Kingdom - the largest group, for example Animalia or Plantae\n- Phylum - in animals, Chordata contains all vertebrates\n- Class - Mammalia is marked by hair and mammary glands\n- Order - a subdivision of a class\n- Family - a subdivision of an order\n- Genus - the first word of the scientific name\n- Species - members can interbreed and produce fertile offspring\n- Binomial nomenclature: genus with a capital, species in lower case, as Escherichia coli\n- Linnaeus introduced binomial nomenclature\n- Five kingdoms often used: Animalia, Plantae, Fungi, Protista, Monera\n- Population: one species in one area at one time\n- Community: all the populations living together in an area\n- Ecosystem: the community plus the non-living surroundings'
  },
  {
    subject: 'Biology',
    type: 'sheet',
    topic: 'Processes',
    title: 'Processes and what they do',
    body: '- Photosynthesis: carbon dioxide + water gives glucose + oxygen, using light in the chloroplast\n- Respiration: glucose + oxygen gives carbon dioxide + water + energy, in the mitochondrion\n- Transpiration: water vapour lost through the stomata, which creates the pull that lifts water\n- Translocation: movement of dissolved food through the phloem\n- Osmosis: movement of water through a partially permeable membrane\n- Diffusion: net movement of particles from high to low concentration\n- Active transport: movement against the concentration gradient, needing energy\n- Digestion: salivary amylase acts on starch, pepsin on protein, lipase on fat\n- Pollination: transfer of pollen from anther to stigma\n- Fertilization: fusion of male and female gametes to form a zygote\n- Mitosis: keeps the chromosome number, for growth and repair\n- Meiosis: halves the chromosome number, giving 23 in a human gamete\n- Germination: growth resumes, needing water, oxygen and a suitable temperature\n- Excretion: removal of urea, carbon dioxide, excess salts and water\n- Decomposition: decomposers return minerals and other nutrients to the soil'
  },
  {
    subject: 'Biology',
    type: 'sheet',
    topic: 'Definitions',
    title: 'Definitions and common examples',
    body: '- Cell: the smallest unit of life; a tissue is similar cells doing one job\n- Species: organisms that interbreed to produce fertile offspring\n- Autotroph: makes its own food, as a green plant does; heterotroph must feed on others\n- Saprophyte: feeds on dead organic matter, such as a mushroom\n- Macronutrient: needed in large quantities; trace element: needed in tiny quantities\n- Complete protein: holds every essential amino acid, as egg and milk do\n- Roughage: cellulose that gives bulk but is not digested\n- Vector: an animal that carries a parasite, the female Anopheles mosquito for malaria\n- Intermediate host: the host in which the parasite reproduces, the mosquito for Plasmodium\n- Antibodies: produced by lymphocytes; vaccination gives active immunity\n- Antibiotics treat diseases caused by bacteria, not diseases caused by viruses\n- Homologous structures: common origin, different function, the forelimbs of a whale and a bat\n- Vestigial structure: reduced and nearly useless, such as the human appendix\n- Prokaryote: no membrane-bound nucleus, a bacterium; eukaryote: nucleus present\n- Binary fission: how bacteria reproduce; budding: yeast; fragmentation: moulds\n- Rhizobium fixes nitrogen in root nodules; mycorrhiza is a fungus with plant roots'
  }
);