/* Revision notes for History */
window.NOTES = window.NOTES || [];
window.NOTES.push(
  {
    subject: 'History',
    type: 'note',
    topic: 'Ancient kingdoms',
    title: 'Kingdoms before the Europeans arrived',
    body: 'Long before European ships appeared on the coast, the lands that now make up Nigeria and their neighbours held well organised states, each with its own titles, army and trade. Examiners rarely ask for narrative here; they ask which state did what, so attach every title to its people and every product to its town.\n\nHere\'s the idea: the questions are matching questions, and the answer is almost always a title, a founder or a place, so drill the pairs rather than the stories.\n\nStep 1 - Identify the people first, Oyo, Kanem-Bornu, the Hausa states, Benin, Ife or the Igbo, and rule out every option from a different people.\nStep 2 - Recall the title attached to that people, so Alaafin for Oyo, Mai for Kanem-Bornu, Shehu for Sokoto, Ooni for Ife and Obi for Onitsha.\nStep 3 - Recall the institution, so the Oyo Mesi checked the Alaafin, the Nri held priestly authority among the Igbo, and the Aro Chukwu oracle sat at Arochukwu.\nStep 4 - Recall the trade or the artefact, and remember that a technique question usually points to bronze work, since the Benin plaques and the Igbo-Ukwu finds were both made by casting.\n\nExample: The political head of the Oyo Empire was known as the: Ooni; Alaafin; Obi; Eze. The answer is the Alaafin. The Alaafin was the political ruler of Oyo, and the empire rested on cavalry, so the other three titles belong elsewhere. Ooni is the ruler of Ile-Ife, which is the traditional cradle of Yoruba civilisation, not of Oyo, and it is the option most candidates reach for because both are Yoruba. Obi is the title of the Onitsha king among the Igbo, and the Obi of Onitsha is named in the Benin expedition question as the kind of ruler the British did not depose. Eze is a title used among the Igbo and in the eastern states for a ruler or head of a community, and it is not the Oyo title.\n\nWatch out: do not let a Yoruba title float onto a Yoruba state. Ile-Ife and Ife are home to the Ooni, Oyo is home to the Alaafin, and Benin to the Oba, and swapping them is the single most common error in this topic.\n\nIn short: learn the people, the title and the town together as one unit, and the option list will usually eliminate itself.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'Trans-Saharan trade',
    title: 'Caravans, gold, salt and the empires',
    body: 'The Sahara shaped trade rather than stopping it. For centuries camel caravans carried salt south and gold north, and the states that straddled the crossings grew wealthy on tolls, taxes and the towns that served the caravans, which is why this topic always comes back to who controlled a crossing or a well.\n\nHere\'s the idea: every Saharan empire in this topic was built on trade, so the fast answer is the name whose career is tied to a caravan route or a famous journey.\n\nStep 1 - Identify which empire the stem names, Ghana, Mali, Songhai or Kanem-Bornu, and eliminate the options attached to the other three at once.\nStep 2 - Recall what the empire traded, so salt, gold and cloth northwards, and dyed cloth from Kano to the desert markets.\nStep 3 - For rulers, keep the founder and the reformer apart, since one man builds the empire and another governs it well.\nStep 4 - For the end of an empire, recall the invader and the year, which is the detail that turns three otherwise identical options into one answer.\n\nExample: The Songhai Empire of the Middle Niger was founded by: Sundiata Keita; Askia Muhammad; Mansa Musa; Sunni Ali Ber. The answer is Sunni Ali Ber. Sunni Ali Ber built the Songhai state on the Middle Niger and made it the dominant power in the region. Sundiata Keita is the founder of the Mali Empire in the 13th century, not of Songhai, and he is the bait for anyone who has memorised one great West African name. Askia Muhammad is the ruler who later reorganised Songhai and gave it a firmer Islamic administration, so he came after the founder and tightened what Sunni Ali had built. Mansa Musa is remembered for the 1324 pilgrimage to Mecca that brought Mali to world attention, which is a Mali fact, not a Songhai one.\n\nWatch out: keep the three founders and the one organiser in their own lanes. Sundiata Keita founds Mali, Sunni Ali Ber founds Songhai, Askia Muhammad reorganises it, and Mansa Musa is the pilgrim of Mali, so a question that offers all four in one option set is testing exactly this.\n\nIn short: whoever controlled the crossing controlled the trade, and whoever controlled the trade built the empire.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'Sokoto Caliphate',
    title: 'How the caliphate began and ran',
    body: 'The Sokoto Jihad of 1804 began as a religious and social reform movement. Usman dan Fodio had preached for years that the Hausa rulers were corrupt and unjust, and a quarrel with the ruler of Gobir turned preaching into war, which is why the movement is classified as reform rather than as a trade war or a colonial resistance.\n\nHere\'s the idea: the caliphate is remembered in three layers, the quarrel that triggered it, the men who supplied the ideas and the administration, and the provinces through which it was governed.\n\nStep 1 - Fix the trigger, the conflict in 1804 between Usman dan Fodio and Sarki Yunfa of Gobir, and treat the question as answered once you have that name.\nStep 2 - Fix the roles: Usman dan Fodio led and preached, Abdullahi dan Fodio was the chief ideologue who wrote the treatises, and Muhammad Bello organised the administration.\nStep 3 - Fix the structure, since the supreme ruler bore the title Shehu and the conquered lands were organised into emirates, each run by an appointed emir.\nStep 4 - Fix the end, the British completing the conquest in 1903 when Sultan Attahiru I was defeated at Burmi.\n\nExample: The immediate trigger of the Sokoto Jihad in 1804 was the conflict between Usman dan Fodio and: the bombardment of Lagos; Sarki Yunfa of Gobir; the Berlin Conference; the Asante king. The answer is Sarki Yunfa of Gobir. Usman dan Fodio had been preaching against the corruption of the Hausa rulers, and the dispute with the Sarki of Gobir, the ruler of the state from which the movement was launched, turned that preaching into a campaign in 1804. The bombardment of Lagos belongs to 1851, when the British used a slave trade justification to attack the Lagos coast, so it is three centuries out. The Berlin Conference of 1884 and 1885 laid down the rules for the European partition of Africa and had no part in an 1804 Hausa quarrel. The Asante king belongs to the Anglo-Asante wars over control of the Gold Coast hinterland, a different region and a different century.\n\nWatch out: do not confuse the founder with the ideologue. If a question asks who wrote the treatises justifying the jihad, the answer is Abdullahi dan Fodio, and the Supreme ruler title is Shehu, not Mai, which belongs to the kings of Kanem-Bornu.\n\nIn short: preach, quarrel with the Sarki of Gobir, conquer the Hausa states, then govern them as emirates under a Shehu.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'British colonialism',
    title: 'From the Lagos bombardment to Lugard',
    body: 'British rule in Nigeria was assembled in pieces between the 1850s and 1914, first along the coast, then up the rivers and finally across the savannah. Almost every question in this topic is a date, a place or a justification attached to one of those stages, and the justifications are where the traps sit.\n\nHere\'s the idea: each colonial move came with a stated reason, and you must be able to give the reason as well as the date, because the options are always reasons.\n\nStep 1 - Place the event in the sequence, coast, rivers, savannah, and then the amalgamation of 1 January 1914.\nStep 2 - Attach the stated justification, so the 1851 bombardment of Lagos was argued to suppress the slave trade, and the 1897 Benin expedition was a punitive response to the killing of a British mission.\nStep 3 - For indirect rule, hold two regions side by side, since it worked where the emirate system was already intact in the North and failed where traditional authority had to be invented in Eastern Nigeria.\nStep 4 - If the option mentions a specific instrument, check it, because a charter, a conference and a commission are all different things.\n\nExample: Indirect rule met stiff resistance in Eastern Nigeria mainly because of: the strength of the emirate system; the wealth of the chiefs; the imposition of warrant chiefs lacking local legitimacy; the abolition of taxation. The answer is the imposition of warrant chiefs lacking local legitimacy. Indirect rule depends on governing through recognised traditional rulers, and in Igbo land there was no such structure waiting to be used, so the British created warrant chiefs. Those chiefs had no local standing, and the attempt to impose them and to tax women provoked the Women\'s War of 1929. The strength of the emirate system is the opposite case, because that is precisely why indirect rule worked well in the Northern Region where the emirs already ruled. The wealth of the chiefs is a distractor with no bearing on legitimacy. The abolition of taxation is nonsense, because indirect rule depended on collecting taxes, and the women\'s protest was caused by the extension of tax to women, not by any abolition.\n\nWatch out: indirect rule is closely associated with Lord Lugard, not with Sir James Robertson, Hugh Clifford or Bourdillon, and the 1897 Benin expedition exiled Oba Ovonramwen and carried the bronzes to Europe rather than ending the caliphate, which fell at Burmi in 1903.\n\nIn short: indirect rule works where traditional authority already exists, and it broke down in the East where the British had to invent it.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'Nationalism',
    title: 'Parties, the press and protest',
    body: 'Nigerian nationalism was carried by newspapers, associations and parties, but it never fully escaped the regions in which each leader was rooted. That weakness shaped everything that followed, because a national cause kept turning into three regional ones long before independence arrived.\n\nHere\'s the idea: for this topic the fastest method is to attach each organisation to its founder, its year and its region, because the options are always drawn from the same small set of names.\n\nStep 1 - Note the constitutional opening, since the elective principle in the Clifford Constitution of 1922 created elected African seats on the Legislative Council.\nStep 2 - Build the party ladder, NNDP in 1923 under Herbert Macaulay, the Nigerian Youth Movement in 1938 with Ernest Ikoli and Nnamdi Azikiwe, and the NCNC in 1944 from Macaulay and Azikiwe.\nStep 3 - Build the regional ladder, the Action Group of 1951 under Obafemi Awolowo, the Northern People\'s Congress under Ahmadu Bello and Tafawa Balewa, and the Northern Elements Progressive Union under Aminu Kano.\nStep 4 - Add the pressure from outside the parties, since the 1945 general strike under Michael Imoudu and the Iva Valley killings of 1949 hardened opinion against colonial rule.\n\nExample: A major weakness of Nigerian nationalism before independence was: lack of educated elites; absence of political parties; a total ban on the press; strong regional and ethnic loyalties. The answer is strong regional and ethnic loyalties. The leaders who fought for self-government were rooted in their own regions, so the NCNC drew mainly on the eastern minority groups, the Action Group on the western Yoruba and the NPC on the northern, and an agreement in one region was read as an attack in another. The Kano riots of 1953 showed exactly that, exposing northern suspicion of the southern push for early self-government. Lack of educated elites is false, because the nationalists were precisely the product of mission schools, the Law School and new universities. Absence of political parties is false for the same reason, since parties were the main engine of the campaign. A total ban on the press is false too, since Azikiwe\'s West African Pilot existed to be read, and the 1922 constitution had already opened a limited elective door.\n\nWatch out: the weakness is not that nationalism was too slow but that it was too regional. Watch also for the 1953 motion, which was moved by Anthony Enahoro and not by Azikiwe, Awolowo or Balewa.\n\nIn short: attach every party to its founder, year and region, and remember the movement was held back by regional and ethnic loyalty.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'Independence',
    title: 'The road to 1 October 1960',
    body: 'Independence came to British West Africa in the 1950s, and Nigeria\'s own date was fixed by constitutional conferences abroad rather than by armed confrontation at home. Ghana, Guinea and Nigeria took different routes, and the question bank likes to set one against another in the options.\n\nHere\'s the idea: hold each country with its exact date and its leader, because the distractors are almost always the correct day in the wrong month or the correct country with the wrong leader.\n\nStep 1 - Fix Nigeria first, since it became independent on 1 October 1960 as a federation within the Commonwealth with Tafawa Balewa as prime minister, and became a sovereign republic on 1 October 1963 under Nnamdi Azikiwe.\nStep 2 - Fix Ghana, which became independent on 6 March 1957 under Kwame Nkrumah, whose Convention People\'s Party was founded in 1949 and whose Positive Action campaign of 1950 used boycotts, strikes and civil disobedience.\nStep 3 - Fix Guinea, which chose independence in 1958 by voting against remaining in the French Community, under Ahmed Sekou Toure, while Senegal was led by Leopold Sedar Senghor, a poet of Negritude.\nStep 4 - Fix the two constitutional steps, so the 1957 London conference produced the Lyttleton Constitution with ministerial government at the centre, and the Republican Constitution of 1963 created the presidency.\n\nExample: The Gold Coast gained independence as Ghana on: 1 March 1957; 6 March 1957; 1 October 1960; 6 March 1960. The answer is 6 March 1957. Nkrumah\'s Convention People\'s Party won the 1956 election and the country left British rule in March 1957, and the sixth is as much a part of the date as the year. 1 March 1957 is the trap, because it keeps the month and loses the day. 1 October 1960 is Nigeria\'s date, not Ghana\'s, and it is the option to reject whenever you see an October date in a Ghana question. 6 March 1960 repeats the right day with a wrong year, and it looks convincing only if you have not anchored the year.\n\nWatch out: the day as well as the year carries marks. Ghana is 6 March 1957, Nigeria is 1 October 1960 and the republic is 1 October 1963, and the commonest slip is to move October onto Ghana or March onto Nigeria.\n\nIn short: fix country, leader and exact date as one bundle, and October always belongs to Nigeria.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'Post-independence',
    title: 'The First and Second Republics',
    body: 'The First Republic lasted barely six years, and everything that went wrong in it was visible before 1966: regional parties, disputed elections and a centre that no region fully trusted. The Second Republic from 1979 repeated the pattern of a presidential constitution, a disputed succession and an abrupt military ending.\n\nHere\'s the idea: link each crisis to its cause, because UTME almost never asks what happened without also offering you an explanation to accept or reject.\n\nStep 1 - Start the sequence at independence in 1960 as a federation, then the republic in 1963, then the 1963 presidential constitution and the end of the First Republic in January 1966.\nStep 2 - For each crisis, name the trigger, so the 1962 Western Region crisis began with the split in the Action Group between Awolowo and Akintola, and Awolowo was convicted of treasonable felony in 1963.\nStep 3 - For the 1964 federal election, remember the charge, widespread malpractice and manipulation, and remember that the disputed census of the early 1960s deepened the quarrel between regions.\nStep 4 - For the Second Republic, name the constitution, the party and the date, since the 1979 Constitution created the presidential system, the NPN won with Shehu Shagari, and he was overthrown on 31 December 1983.\n\nExample: The 1962 crisis in the Western Region was caused mainly by: a military coup; a currency reform; a split in the Action Group between Awolowo and Akintola; a census dispute. The answer is a split in the Action Group between Awolowo and Akintola. The Action Group had been the dominant party of the Western Region since 1951, and the personal and ideological quarrel between its two leading figures broke it apart, which destroyed the machinery the region had used to govern itself. A military coup is wrong on both counts, because the first coup did not come until January 1966 and the crisis was political rather than military. A currency reform is invented, and no such measure caused the crisis. A census dispute is real in Nigerian history but it belongs to the quarrel over representation between the regions in the early 1960s, and the trigger inside the Western Region itself was the party split, which is why Awolowo was convicted of treasonable felony in 1963.\n\nWatch out: the reason the army found it easy to seize power is the point the examiners want drawn, namely weak national party organisation and government resting on regional alliances rather than a single national party.\n\nIn short: regional party splits, a rigged 1964 election and weak national organisation together explain why the First Republic fell in 1966.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'Military rule',
    title: 'Coups, civil war and junta rule',
    body: 'From 1966 onwards Nigeria was governed by soldiers for all but a few years, and the pattern repeated itself: a coup, a promise of reform, then an exit forced by crisis. Learning the sequence and the years together matters more than learning either alone, because the order of the coups is itself a syllabus theme.\n\nHere\'s the idea: treat the coups as a dated list you can recite forwards and backwards, and attach the single action that defines each regime to its name.\n\nStep 1 - Build the opening: 15 January 1966 first coup and Aguiyi-Ironsi, then the 19 July 1966 counter-coup that killed him and installed Yakubu Gowon.\nStep 2 - Build the civil war: twelve states in 1967, Ojukwu\'s proclamation of the Republic of Biafra on 30 May 1967, the war from July 1967 to January 1970, and Gowon\'s slogan of no victor, no vanquished.\nStep 3 - Build the later regimes: Gowon overthrown in 1975, Murtala Mohammed killed in 1976, Buhari from 1983 to 1985, then Babangida from August 1985 with the Structural Adjustment Programme of 1986.\nStep 4 - Close the sequence with the transition, so Babangida annulled the 12 June 1993 election, Shonekan headed the Interim National Government, Abacha took over in November 1993 and died in June 1998, and Abubakar handed over in 1999.\n\nExample: The mass starvation of Biafran civilians was largely caused by the: open-door policy; currency exchange; naval blockade of Biafra; evacuation of schools. The answer is the naval blockade of Biafra. Federal forces denied Biafran ports and shipping to the outside world, so food and medicine could not reach the enclave, and hunger killed far more civilians than either army. An open-door policy is the reverse of what happened, since the federal government closed the sea route rather than opening it. Currency exchange is a financial measure that had no bearing on civilian food supply. Evacuation of schools sounds humane but is unrelated to the famine, and the real human cost lay in the blockade rather than in anything done to schools.\n\nWatch out: the Aburi meeting of January 1967 was held in Ghana, and it failed to settle the dispute between Gowon and Ojukwu, so do not attach Aburi to Lagos or to Nigeria itself, and remember Biafra ended in January 1970 rather than 1975.\n\nIn short: know the coups as a dated chain, and know that Gowon, the twelve states, Biafra and the blockade are one single story.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'Constitutions',
    title: 'Every Nigerian constitution in order',
    body: 'Nigeria has been governed under a long parade of constitutions, and examiners usually ask what each one introduced, how many regions existed and who criticised it. The 1999 Constitution borrowed heavily from the 1979 Constitution, which is a link students often miss.\n\nHere\'s the idea: match each constitution to its year first and to the single feature it is famous for second, because the options are always other constitutions and the dates do the work for you.\n\nStep 1 - Start the colonial list, so Clifford in 1922 for the elective principle, Richards in 1946 for three regions, Macpherson in 1951 for elections to the House of Representatives, and Lyttleton in 1957 for ministerial government at the centre.\nStep 2 - Move to independence, so the 1960 Constitution established Nigeria as a federation within the Commonwealth and the 1963 Republican Constitution made it a sovereign republic with an elected president.\nStep 3 - Note the post-civil war step, since the 1979 Constitution introduced the presidential system and required a presidential candidate to score at least 25 per cent of the votes in two-thirds of the states.\nStep 4 - Note that the 1999 Constitution, promulgated by the military government, ushered in the Fourth Republic, and that it was modelled on 1979.\n\nExample: The Macpherson Constitution was criticised mainly because it: abolished elections; created too many regions; gave voting rights to Europeans only; made the centre too strong and lacked popular consultation. The answer is made the centre too strong and lacked popular consultation. The 1951 constitution extended elections to the House of Representatives, which was progress, but the centre kept the real strength and the document was drawn up without proper consultation of Nigerian opinion. Abolished elections is false, because elections to the House of Representatives are exactly what it provided for, and that is the answer to the companion question on what it introduced. Created too many regions is the opposite of what happened, since the Richards Constitution of 1946 had already cut Nigeria into three and 1951 did not change that. Gave voting rights to Europeans only is absurd, since the whole point of the elective principle was African representation.\n\nWatch out: keep the criticism attached to the right year. Macpherson is criticised for a strong centre and no consultation, while the 1960 and 1963 constitutions are criticised for locking the country into a federation whose regions were unequal, and the 1979 threshold of 25 per cent in two-thirds of the states recurs in later constitutions.\n\nIn short: constitution to year, then year to the one feature it is famous for, and you will not need the whole story.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'Economy and development',
    title: 'Cash crops, oil and adjustment',
    body: 'Nigeria\'s economy was shaped first by colonial export demands and later by petroleum, and each phase left behind a different problem that governments then had to manage. The exam links every policy to the problem it was meant to solve, so learn the pairs rather than the slogans.\n\nHere\'s the idea: every economic question in this topic has a cause and a remedy, and the distractors are remedies borrowed from the wrong decade.\n\nStep 1 - Start with the colonial economy, where the hinterland was linked to the ports by railway so that cocoa, groundnuts, palm produce and cotton could be exported, with tin mined on the Jos plateau.\nStep 2 - Note what that economy looked like on the ground, the groundnut pyramids of Kano and the cocoa heaps of the West, with taxes paid out of farm proceeds.\nStep 3 - Move to oil, struck at Oloibiri in 1956, which by the 1970s dominated both exports and government revenue and made the oil boom expand public spending fast.\nStep 4 - Move to the response, since when oil earnings fell the Structural Adjustment Programme of 1986 was introduced on the advice of the IMF and the World Bank, bringing devaluation, cuts in subsidies and real hardship for households.\n\nExample: The Structural Adjustment Programme (SAP) introduced in 1986 was based largely on advice from: the African Union; ECOWAS; the IMF and World Bank; the United Nations General Assembly. The answer is the IMF and World Bank. The programme was imposed as a condition of renewed external borrowing from those two Bretton Woods institutions, and it brought devaluation of the naira, cuts in fuel subsidies and the withdrawal of import controls. The African Union is the trap because it is an African body created in 2002, sixteen years after the programme, so it could not have advised on it. ECOWAS existed but its remit is trade and economic cooperation among West African states, not macroeconomic reform of a member state. The United Nations General Assembly issues recommendations and was not the source of Nigerian economic policy of this kind.\n\nWatch out: the Structural Adjustment Programme belongs to 1986 under Babangida, not to 1975, 1980 or 1999, and the indigenisation decrees of the 1970s are a separate story, aimed at raising Nigerian ownership of companies rather than at macroeconomic reform.\n\nIn short: colonial cash crops, then oil, then adjustment in 1986, and each policy answers the failure of the economy before it.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'International relations',
    title: 'Nigeria and the wider world',
    body: 'Nigeria entered world politics as a newly independent state in 1960 and tied itself quickly to African and Commonwealth institutions, while officially refusing to join either Cold War bloc. Examiners like pairs here, so fix every body to its founding year and its city and its function.\n\nHere\'s the idea: each organisation in this topic has three handles, its year, its city and its job, and a question gives you two of them and asks for the third.\n\nStep 1 - Fix the OAU, founded in 1963 at Addis Ababa, where its headquarters has remained, and note the two principles attached to it, respect for inherited colonial boundaries and non-alignment.\nStep 2 - Fix ECOWAS, established by the Treaty of Lagos in 1975 to promote free trade and economic cooperation among West African states.\nStep 3 - Fix the world bodies, so the League of Nations formed after the First World War was replaced by the United Nations founded in 1945.\nStep 4 - Fix the Pan-African strand, since the first Pan-African Conference met in London in 1900, W.E.B. Du Bois organised congresses in 1919, 1921, 1923 and 1927, and the Fifth Congress in Manchester in 1945 demanded immediate self-government.\n\nExample: During the Nigerian Civil War, the role of the OAU was to: recognise Biafra; mediate while accepting Nigeria\'s unity; send ECOMOG troops; expel Nigeria. The answer is to mediate while accepting Nigeria\'s unity. The OAU was committed to respect for the boundaries inherited at independence, which meant it could not recognise Biafra as a new state, so it offered to mediate while accepting that Nigeria remained one country. Recognise Biafra is the answer that the question most wants ruled out, and no OAU resolution ever did so. Send ECOMOG troops is anachronistic, since ECOMOG was a West African force of the 1990s and had nothing to do with a 1967 to 1970 war. Expel Nigeria would have meant using the boundary principle against Nigeria, which is the opposite of what the OAU was built to do.\n\nWatch out: the OAU was founded in 1963 at Addis Ababa and replaced by the African Union in 2002, which is also based at Addis Ababa, so a headquarters question must be told apart by the body, not by the city.\n\nIn short: OAU 1963 at Addis Ababa, ECOWAS 1975 by the Treaty of Lagos, United Nations 1945, and Nigeria kept non-alignment throughout.'
  },
  {
    subject: 'History',
    type: 'note',
    topic: 'Historical sources',
    title: 'Where history comes from and how',
    body: 'Every history answer depends on evidence, and the syllabus expects you to classify a source before you use it, because classification decides how far it can be trusted. Most wrong answers in this topic come from skipping that first step and reaching for a familiar name.\n\nHere\'s the idea: two questions decide almost every source question, is it primary or secondary, and who produced it and for what purpose.\n\nStep 1 - Classify first, so anything from someone who witnessed the event, a diary, a speech or an eyewitness account, is primary, while anything interpreting it, including a textbook and an encyclopedia, is secondary.\nStep 2 - Identify the family, so oral tradition carries the history of societies that left no written records, indigenous written sources include the Kano Chronicle and the Chronicle of Borgu, and the Tarikh al-Sudan and Tarikh al-Fattash cover the western Sudan and Timbuktu.\nStep 3 - Apply the tools, so stratigraphy reads the layers of earth to establish sequence, radio-carbon dating measures carbon-14 in organic material, numismatics studies ancient coins and palaeography examines old manuscripts.\nStep 4 - Then test the weakness, since a praise singer who inflates his king\'s exploits to win rewards is showing bias, and transmission can distort meaning along the way.\n\nExample: The observation that a praise singer exaggerated his king\'s exploits in order to gain rewards illustrates which weakness of oral sources? forgery of documents; bias; translation error; printing error. The answer is bias. The singer was not lying about facts in the modern sense, he was shaping the account to flatter and to be rewarded, so the evidence is slanted by the position of the person producing it. Forgery of documents fails on the technology as well as on the idea, since oral tradition is transmitted by word of mouth and there is no document to forge. Translation error and printing error both require writing, and the oriki praise-poem that recounts a king\'s achievements is spoken, not printed.\n\nWatch out: do not call a textbook a primary source because it is old, and do not call a praise-poem weak merely because it is oral, since the expected criticism is bias and distortion in transmission, not falsehood.\n\nIn short: classify the source first, then judge it, and the classification decides which criticism is the right one.'
  },
  {
    subject: 'History',
    type: 'sheet',
    topic: 'Key dates',
    title: 'Nigerian dates to recall cold',
    body: '- 1804 — Usman dan Fodio launches the Sokoto Jihad\n- 1851 — British bombardment of Lagos\n- 1861 — Lagos formally annexed by Britain\n- 1884-1885 — Berlin Conference lays down the rules for the partition of Africa\n- 1897 — Benin Expedition; Oba Ovonramwen exiled\n- 1903 — Sultan Attahiru I defeated at Burmi, Sokoto Caliphate falls\n- 1 January 1914 — amalgamation of the Northern and Southern Protectorates\n- 1922 — Clifford Constitution introduces the elective principle\n- 1929 — Women\'s War of the Eastern Region\n- 1945 — general strike led by Michael Imoudu; United Nations founded\n- 1946 — Richards Constitution divides Nigeria into three regions\n- 1951 — Macpherson Constitution provides for elections to the House of Representatives\n- 1953 — Anthony Enahoro moves the self-government motion; Kano riots\n- 6 March 1957 — Gold Coast becomes Ghana\n- 1957 — Lyttleton Constitution introduces ministerial government at the centre\n- 1 October 1960 — Nigeria gains independence as a federation in the Commonwealth\n- 1 October 1963 — Nigeria becomes a sovereign republic\n- 15 January 1966 — first military coup; Aguiyi-Ironsi takes over\n- 19 July 1966 — counter-coup installs Yakubu Gowon\n- 30 May 1967 — Ojukwu proclaims the Republic of Biafra\n- January 1970 — Nigerian Civil War ends; no victor, no vanquished\n- 1975 — Treaty of Lagos establishes ECOWAS\n- 1979 — Second Republic opens under the presidential constitution\n- 31 December 1983 — Shehu Shagari overthrown\n- 19 August 1985 — Babangida seizes power\n- 1986 — Structural Adjustment Programme introduced\n- 12 June 1993 — presidential election annulled\n- June 1998 — Sani Abacha dies in office\n- 1999 — 1999 Constitution opens the Fourth Republic'
  },
  {
    subject: 'History',
    type: 'sheet',
    topic: 'Wars and treaties',
    title: 'Wars and treaties worth naming',
    body: '- Sokoto Jihad, 1804-1805 — Kano and Katsina fall to the jihadists\n- British abolition of the Atlantic slave trade, 1807; Emancipation Act in the colonies, 1833\n- Asiento granted to Britain, 1713 — right to supply slaves to Spanish colonies\n- Anglo-Asante wars — fought over control of the Gold Coast hinterland\n- Hut Tax War, 1898, Sierra Leone — led by Bai Bureh\n- Anglo-Zulu War, 1879 — defeat of the Zulu Kingdom\n- Yaa Asantewaa War, 1900 — Asante resistance after Prempeh I was exiled to Seychelles\n- Morant Bay Rebellion, 1865, Jamaica — led by Paul Bogle\n- Maji Maji Rebellion, 1905-1907 — against German rule in Tanganyika\n- Herero and Nama rebellion — against German rule in German South West Africa\n- Battle of Adwa, 1896 — Menelik II\'s Ethiopians defeat the Italians\n- Samori Toure founded the Wassoulou Empire and was captured by the French in 1898\n- Benin Expedition, 1897 — bronzes removed to Europe, Oba exiled\n- Berlin Conference, 1884-1885 — rules for the European partition of Africa\n- Treaty of Versailles, 1919 — ends the First World War and penalises Germany\n- Aburi meeting, January 1967, Ghana — Gowon and Ojukwu fail to agree\n- Nigerian Civil War, July 1967 to January 1970\n- Treaty of Lagos, 1975 — establishes ECOWAS\n- Battle of Burmi, 1903 — Sultan Attahiru I defeated by the British'
  },
  {
    subject: 'History',
    type: 'sheet',
    topic: 'People and offices',
    title: 'People and offices to match',
    body: '- Usman dan Fodio — founder of the Sokoto Caliphate in 1804\n- Abdullahi dan Fodio — chief ideologue who wrote treatises justifying the jihad\n- Muhammad Bello — son of Usman and organiser of the caliphate\'s administration\n- Sarki Yunfa of Gobir — ruler whose quarrel with Usman triggered the jihad\n- Shehu — title of the supreme ruler of the Sokoto Caliphate\n- Alaafin — political head of the Oyo Empire\n- Bashorun — head of the Oyo Mesi council that checked the Alaafin\n- Are-Ona Kakanfo — commander-in-chief of the Oyo army\n- Mai — title of the kings of Kanem-Bornu\n- Emir — governor of a province of the Sokoto Caliphate\n- Eweka I — first Oba of Benin; Oba Ewuare I built the great walls\n- Oba Ovonramwen — exiled after the British expedition of 1897\n- Queen Amina of Zaria — warrior queen who expanded Zazzau by conquest\n- Thurstan Shaw — excavated the Igbo-Ukwu bronzes in 1959\n- Kenneth Onwuka Dike — author of Trade and Politics in the Niger Delta\n- Herbert Macaulay — founded the NNDP in 1923 and co-founded the NCNC in 1944\n- Nnamdi Azikiwe — founder of the West African Pilot and first President of Nigeria\n- Obafemi Awolowo — founded the Action Group in 1951 and the 1955 free primary scheme\n- Anthony Enahoro — moved the 1953 self-government motion\n- Aminu Kano — led the Northern Elements Progressive Union against the emirate establishment\n- Kwame Nkrumah — founded the CPP in 1949 and led Ghana to independence in 1957\n- Lord Lugard — pioneer of indirect rule and the 1914 amalgamation'
  }
);
