/* Revision notes for Physics */
window.NOTES = window.NOTES || [];
window.NOTES.push(
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Measurement',
    title: 'Units, dimensions and significant figures',
    body: 'A measurement is a number paired with a unit, and the number means nothing without the unit. The seven SI base units are the metre for length, kilogram for mass, second for time, ampere for current, kelvin for temperature, mole for amount of substance and candela for luminous intensity. Everything else is derived from them: force is kg m/s^2 and takes the name newton, pressure is N/m^2 and takes the name pascal, work is N m and takes the name joule, and frequency is s^-1 and takes the name hertz.\n\nDimensions drop the units and keep the physics. Write length as L, mass as M and time as T. Velocity is length divided by time, so LT^-1; acceleration is LT^-2; force is mass x acceleration, so MLT^-2; work is force x distance, so ML^2T^-2. An equation whose two sides carry different dimensions must be wrong, which is the quickest way to check a derived formula.\n\n- Scalars have magnitude only: mass, speed, distance, energy, temperature.\n- Vectors have magnitude and direction: displacement, velocity, acceleration, force, momentum.\n- Significant figures: leading zeros never count, so 0.00450 has three; 4.5678 rounded to three significant figures is 4.57.\n- Unit conversion: 72 km/h divided by 3.6 is 20 m/s, because 1 km/h is 1000 m divided by 3600 s.\n\nAlways carry the unit through the working; an answer without one is not a measurement.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Linear motion',
    title: 'Acceleration, graphs and projectiles',
    body: 'Speed is distance covered divided by time, and it is a scalar. Velocity is displacement divided by time, and it is a vector, so direction matters. Acceleration is the rate of change of velocity, a = (v - u)/t, measured in m/s^2. Average speed is always total distance divided by total time: a runner who covers 100 m in 10 s and the next 100 m in 20 s averages 200/30 = 6.7 m/s, not the average of the two separate speeds.\n\nFor uniform acceleration three equations carry almost every question:\n\n- v = u + at\n- s = ut + 1/2 at^2\n- v^2 = u^2 + 2as\n\nWorked example: a car starts from rest and reaches 20 m/s in 5 s, so a = 20/5 = 4 m/s^2 and it covers s = 0 + 1/2 x 4 x 25 = 50 m. A stone falling freely from rest covers s = 1/2 g t^2 = 0.5 x 10 x 4 = 20 m in 2 s, and reaches v = gt = 30 m/s after 3 s. A body starting at 10 m/s and decelerating at 2 m/s^2 stops in exactly 5 s, which is why its velocity then is zero.\n\nRead graphs from their axes: the slope of a distance-time graph is speed, the slope of a velocity-time graph is acceleration, and the area under a velocity-time graph is displacement. For projectiles air resistance is ignored and the horizontal velocity never changes: range = u^2 sin(2 theta)/g and time of flight = 2u sin(theta)/g. A ball thrown at 20 m/s at 30 degrees therefore travels 400 x 0.866 / 10 = 34.6 m, and one thrown straight up at 30 m/s rises u^2/2g = 45 m.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Forces',
    title: 'Resultants, friction and pressure',
    body: 'A force is a push or pull that can change a body\'s state of motion. Newton\'s first law says a body stays at rest or keeps moving uniformly in a straight line unless a resultant external force acts on it; that resistance to a change in motion is inertia, and mass measures it. Newton\'s second law gives F = ma, so a 5 kg body accelerated at 2 m/s^2 needs 10 N. Weight is not mass: W = mg, so a 5 kg body weighs 50 N on Earth but only 8 N on the moon where g = 1.6 m/s^2, while its mass is unchanged everywhere.\n\nPressure and moments spread the same force over geometry. Pressure = force/area, so 100 N resting on 0.5 m^2 gives 200 Pa, and atmospheric pressure at sea level is about 1 x 10^5 Pa. Pressure in a liquid is density x g x depth, which gives 1000 x 10 x 5 = 50000 Pa at 5 m. Pressure applied to a confined fluid is transmitted equally in all directions, which is Pascal\'s principle and the working idea of a hydraulic press.\n\n- Friction: the force needed to just move a body is F = mu x R, so 0.4 x 5 x 10 = 20 N.\n- Resultant of perpendicular forces: sqrt(F1^2 + F2^2), so 3 N and 4 N give 5 N.\n- Moment = force x perpendicular distance, so 10 N applied 0.5 m from a pivot gives 5 N m.\n- Impulse = force x time = change in momentum, with unit N s.\n- Upthrust equals the weight of fluid displaced, and a body floats when its own density is less than the liquid\'s.\n- Centripetal force holds a body in a circle: F = mv^2/r, so 2 kg at 10 m/s around radius 5 m needs 40 N.\n\nResolve the forces into perpendicular directions before adding them; a missing force on the free-body diagram is the usual cause of a wrong answer.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Work energy and power',
    title: 'Work, energy, power and machines',
    body: 'Work is done only when a force moves a body along the line of action of that force: W = F s cos(theta). A force of 25 N moving through 4 m does 100 J, but a 10 N force acting perpendicular to a 2 m displacement does 0 J, because cos(90 degrees) = 0. One joule is one newton metre.\n\nEnergy is the capacity to do work. Kinetic energy is 1/2 mv^2, so 2 kg moving at 3 m/s holds 9 J. Gravitational potential energy is mgh, so 10 kg at 5 m with g = 10 gives 500 J. Gravity is a conservative force: the work it does depends only on the start and end heights, never on the path. Friction, air resistance and viscous drag are non-conservative and turn mechanical energy into heat. An electric lamp converts electrical energy mainly into heat and light, and the total energy in any conversion is always conserved.\n\nPower is the rate of doing work, P = W/t, measured in watts, with 1 W = 1 J/s. An engine that lifts 500 N through 3 m in 10 s does 1500 J in 10 s, so it delivers 150 W. One horsepower is about 746 W.\n\nMachines trade force for distance:\n\n- Efficiency = useful work out / energy in x 100, so 400 J of useful work from 500 J of input is 80%.\n- Efficiency = mechanical advantage / velocity ratio x 100, so a velocity ratio of 5 at 80% efficiency gives a mechanical advantage of 4.\n- Hooke\'s law: within the elastic limit the extension of a spring is directly proportional to the load, F = kx, and the energy stored is 1/2 kx^2, so 200 N/m stretched 0.15 m stores 2.25 J.\n- Stress = force/area, strain = extension/original length, and Young modulus = stress/strain; glass is brittle because it fractures with almost no strain.\n\nNo machine is 100% efficient; friction and sound always take their share.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Heat and temperature',
    title: 'Temperature, heat and gas laws',
    body: 'Temperature measures the average kinetic energy of the molecules of a body, while heat is energy moving from a hotter body to a cooler one. The SI unit of temperature is the kelvin, and K = degrees Celsius + 273, so 27 degrees C is 300 K and 300 K is 27 degrees C. During a change of state the temperature does not rise; the energy goes into separating the particles instead.\n\nHeat calculations: Q = mc delta T, where c is the specific heat capacity, the heat needed to raise 1 kg of a substance by 1 degree Celsius. Water has c = 4200 J/kg K, so warming 2 kg of water through 10 degrees C takes 2 x 4200 x 10 = 84000 J. Heat capacity belongs to a whole sample, is written mc, and has unit J/K. For a change of state, Q = mL with the specific latent heat of fusion of ice at 3.36 x 10^5 J/kg, so melting 2 kg of ice needs 6.72 x 10^5 J.\n\nTransfer and expansion:\n\n- Conduction passes energy through collisions from particle to particle; it happens in any state but is most important in solids, and metals are the best conductors, copper among the best.\n- Convection is bulk movement of fluid, so it cannot occur in a solid or in a vacuum.\n- Radiation needs no medium at all; a vacuum flask cuts heat loss by blocking conduction, convection and radiation together.\n- Expansion: change in length = original length x coefficient x temperature change, so a 2.0 m steel rod heated through 50 K with coefficient 1.2 x 10^-5 per K grows by 1.2 mm. Gases expand most, then liquids, then solids, which is why a bimetallic strip bends when heated.\n\nGas laws must use absolute temperature. At constant volume P1/T1 = P2/T2, so a gas at 100 kPa and 300 K reaches 133.3 kPa at 400 K. At constant pressure V1/T1 = V2/T2, giving 0.30 m^3 at 300 K as 0.40 m^3 at 400 K. At constant temperature P1V1 = P2V2.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Waves',
    title: 'Wave language and superposition',
    body: 'A wave transfers energy without carrying matter along with it. In a transverse wave the vibration is perpendicular to the direction of travel, as in light and waves on a stretched string; in a longitudinal wave the vibration is parallel to the direction of travel, as in sound through air. The wavelength is the distance between two consecutive points in phase, such as one crest to the next crest. Frequency is the number of complete waves passing a fixed point each second, and period is the time for one complete vibration, so T = 1/f.\n\nThe wave equation links all three: speed = frequency x wavelength. A wave of frequency 50 Hz and wavelength 4 m travels at 200 m/s; a wave of speed 200 m/s and wavelength 5 m has period 5/200 = 0.025 s. When a wave crosses into a new medium its frequency stays fixed while its speed changes, so the wavelength changes with it. Light in vacuum moves at 3 x 10^8 m/s and needs no medium.\n\n- Superposition: when two waves meet, the resultant displacement at a point is the algebraic sum of their separate displacements there.\n- Amplitude sets the energy and intensity; for a point source the intensity obeys the inverse square law, so doubling the distance cuts the intensity to one quarter.\n- Diffraction is the spreading of a wave past an obstacle or through an opening, and it is most pronounced when the slit width is comparable with the wavelength.\n- Human hearing runs from about 20 Hz to 20,000 Hz; below that is infrasonic and above it is ultrasonic.\n\nFrequency never changes at a boundary; speed and wavelength do.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Sound',
    title: 'Echoes, beats and resonance',
    body: 'Sound is a longitudinal mechanical wave, so it needs a material medium and cannot cross a vacuum. It travels fastest in solids, slower in liquids and slowest in gases: about 340 m/s in air at room temperature, and much faster in steel. Passing from air into water its speed increases even though its frequency stays the same.\n\nAn echo is sound returning from a hard surface. The sound must travel to the surface and back again, so distance = speed x time / 2: a cliff heard 2 s after a shout is 340 x 2 / 2 = 340 m away.\n\n- Pitch depends on frequency, loudness depends on amplitude, and quality or timbre is what lets you tell two instruments playing the same note apart.\n- Noise comes from irregular and random vibrations; music comes from regular periodic ones.\n- Beats are heard when two frequencies are close together, and the beat frequency equals the difference between them, so 250 Hz with 252 Hz gives 2 beats per second.\n- Resonance occurs when the driving force vibrates at the natural frequency of the body, and the amplitude then becomes very large.\n- Intensity obeys the inverse square law: move twice as far from the source and the intensity falls to one quarter.\n\nUltrasound, above 20,000 Hz, is used in SONAR to locate objects and measure depth underwater, in medical scanning and in cleaning fine instruments. Infrasound is produced by earthquakes and thunder. Anything outside the 20 Hz to 20,000 Hz range is inaudible to the human ear.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Light and optics',
    title: 'Reflection, refraction and lenses',
    body: 'Light is a transverse electromagnetic wave that needs no medium and travels at 3 x 10^8 m/s in vacuum. In reflection the angle of incidence equals the angle of reflection, and a plane mirror gives an image that is virtual, erect, the same size as the object and as far behind the mirror as the object is in front.\n\nRefraction is the bending of light on passing from one medium into another. Travelling from a rarer to a denser medium the ray bends towards the normal; from denser to rarer it bends away. Refractive index n = c/v, so with n = 1.5 the speed of light in the medium is 3 x 10^8 / 1.5 = 2 x 10^8 m/s. The critical angle follows sin C = 1/n, so n = 1.414 gives C = 45 degrees. Total internal reflection needs two conditions together: light travelling from a denser to a rarer medium, and an angle of incidence greater than the critical angle.\n\n- A converging lens is convex and a diverging lens is concave; a photographic camera uses a convex lens.\n- Power of a lens = 1/focal length in metres, measured in dioptres: f = 20 cm gives 5 D, f = 0.25 m gives 4 D, and powers simply add in contact, so 2 D with 3 D gives 5 D.\n- Thin lens equation, 1/f = 1/v - 1/u with the usual sign convention, gives a 15 cm convex lens with the object at 30 cm an image at 30 cm.\n- Magnification = image height / object height, so a 4 cm object that forms a 12 cm image is magnified three times.\n- Short sight or myopia is corrected with a concave lens, long sight or hypermetropia with a convex lens, and the near point of a normal eye is 25 cm.\n- Dispersion is the splitting of white light by a prism; red is deviated least and violet most.\n\nA real image needs a converging lens or a concave mirror; a plane mirror can only ever give a virtual one.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Electricity',
    title: 'Current, resistance and circuit rules',
    body: 'Current is the rate of flow of charge, I = Q/t, measured in amperes. Potential difference is the work done in moving unit charge around the circuit, measured in volts, and resistance opposes that flow, measured in ohms. Ohm\'s law says that at constant temperature the current through a conductor is proportional to the potential difference across it, so V = IR. A 2 A current through a 5 ohm resistor gives 10 V; a 12 V supply across 4 ohm draws 3 A; and 6 V driving 0.5 A means the wire has 12 ohm resistance.\n\nSeries and parallel follow two simple rules:\n\n- Series: resistances simply add, R = R1 + R2 + R3, so 2 ohm, 3 ohm and 5 ohm give 10 ohm. The current is the same through every component, and the supply voltage divides between them.\n- Parallel: 1/R = 1/R1 + 1/R2, so 2 ohm with 3 ohm gives 1.2 ohm, and three 6 ohm resistors together give 2 ohm. The voltage is the same across every branch, and the branch currents add up.\n\nPower and energy in a circuit:\n\n- P = VI = I^2 R = V^2/R, so 3 A through 2 ohm dissipates 18 W as heat, and a 10 V appliance drawing 2 A consumes 20 W.\n- Energy = power x time. A 60 W lamp used for 2 hours takes 60 x 2 = 120 Wh, which is 0.12 kWh.\n- Lamps and sockets are wired in parallel so each one gets the full supply and can be switched off without breaking the others.\n- A fuse protects the circuit: its wire melts when the current exceeds a safe value and so cuts the supply.\n\nBefore choosing a fuse, work out the normal current with P = VI and pick a rating just above it.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Magnetism',
    title: 'Fields, motors and induction',
    body: 'Outside a bar magnet, magnetic field lines run from the north pole to the south pole; inside the magnet they close the loop from south to north. The lines never cross, and at any point a compass needle lies along the line, which fixes the direction of the field. A straight current-carrying wire produces circular loops around it, and the field inside a long solenoid carrying a steady current is uniform and parallel to the axis, so a solenoid behaves like a bar magnet.\n\nA current-carrying conductor in a magnetic field experiences a force, and Fleming\'s left-hand rule gives its direction: first finger for field, second finger for current, thumb for the motion. That is the motor effect, and an electric motor turns electrical energy into mechanical energy, using a split-ring commutator to reverse the current every half turn. At right angles the force is F = BIL: 0.5 T x 4 A x 0.2 m = 0.4 N.\n\n- Fleming\'s right-hand rule gives the induced current in a generator or dynamo, which converts mechanical energy into electrical energy.\n- Faraday\'s law: the induced EMF is proportional to the rate of change of magnetic flux linkage, so moving the magnet faster or using more turns gives a larger EMF.\n- A galvanometer detects a very small current, and its deflection shows the direction of that current.\n- Soft iron is used for the core of an electromagnet because it is easily magnetised and demagnetised; steel keeps its magnetism and is used for permanent magnets.\n- A transformer works by mutual induction with Vs/Vp = Ns/Np, so 100 primary turns and 500 secondary turns at 60 V supply 300 V, a step-up of five times.\n\nRemember the pair: left hand for motors, where current in a field gives force; right hand for generators, where motion in a field gives current.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Nuclear physics',
    title: 'Radioactivity, half-life and nuclear energy',
    body: 'The atom has a tiny nucleus of protons and neutrons, the nucleons, with electrons in shells around it. The atomic number counts the protons and fixes the identity of the element; the mass number is protons plus neutrons, so neutrons = mass number - atomic number. Isotopes are atoms of the same element with the same atomic number but different mass numbers, so they are chemically identical even when one of them is radioactive.\n\nRadioactive decay is the spontaneous, random emission of radiation from an unstable nucleus. No change of temperature, pressure or chemical combination can speed it up or slow it down. There are three types of radiation:\n\n- Alpha particles are helium nuclei, two protons and two neutrons; they are heavily ionising but the least penetrating, and a sheet of paper stops them.\n- Beta particles are fast-moving electrons; they penetrate further and need a few millimetres of aluminium to stop them.\n- Gamma rays are electromagnetic radiation with no charge and no mass; they are the most penetrating and need thick lead to absorb them.\n\nHalf-life is the time taken for half of the nuclei present to decay. The activity falls by half each half-life but never reaches zero: after 3 half-lives an original 80 g sample has just 10 g left. Carbon-14, with a half-life of about 5730 years, is used to date archaeological specimens, and the SI unit of radioactivity is the becquerel, meaning one decay per second.\n\nFission splits a heavy nucleus such as uranium when it is struck by a neutron, releasing energy and further neutrons that sustain a chain reaction. Fusion joins light nuclei, as in the Sun, and requires an extremely high temperature. Both release energy because mass itself is converted, following E = mc^2.'
  },
  {
    subject: 'Physics',
    type: 'note',
    topic: 'Electronics',
    title: 'Semiconductors, diodes and logic gates',
    body: 'Semiconductors such as silicon and germanium conduct better than insulators but worse than metals, and their conductivity changes with temperature and with the light falling on them. Pure silicon has four outer electrons, and doping it with a controlled impurity changes the number of free charge carriers.\n\n- A pentavalent impurity has five valence electrons and donates an extra free electron, giving n-type material in which electrons are the majority carriers.\n- A trivalent impurity has three valence electrons and leaves a hole, giving p-type material in which holes are the majority carriers.\n- Both materials stay electrically neutral overall; only the type of charge carrier differs.\n\nA p-n junction diode conducts in one direction only, so it passes current when forward biased and blocks it when reverse biased. Rectification is the conversion of alternating current into direct current, which is exactly what that one-way action achieves. A transistor has three terminals and works as an amplifier or as a switch, because a small base current controls a much larger collector current.\n\nLogic gates follow rules that are easy to recall:\n\n- OR gate: the output is 1 when at least one input is 1.\n- AND gate: the output is 1 only when all the inputs are 1.\n- NOT gate: the output is always the opposite of the input.\n\nSensors use the same physics. The resistance of a light dependent resistor falls as the light intensity increases, and a thermistor resistance falls as temperature rises, so either can switch a lamp on automatically when it gets dark. Rectification followed by smoothing with a capacitor is how an adapter turns mains AC into the steady DC an electronic device needs.'
  },
  {
    subject: 'Physics',
    type: 'sheet',
    topic: 'Formula sheet',
    title: 'Formulas worth memorising',
    body: '- Force: F = ma\n- Work: W = F s cos(theta); 1 J = 1 N m\n- Kinetic energy: KE = 1/2 mv^2; potential energy: PE = mgh\n- Power: P = W/t = Fv, in watts\n- Equations of motion: v = u + at, s = ut + 1/2 at^2, v^2 = u^2 + 2as\n- Projectile range: R = u^2 sin(2 theta)/g; time of flight: t = 2u sin(theta)/g\n- Momentum: p = mv; impulse = Ft = change in momentum\n- Pressure: P = F/A; liquid pressure: p = density x g x h\n- Efficiency: useful output / input x 100 = mechanical advantage / velocity ratio x 100\n- Heat: Q = mc delta T; change of state: Q = mL\n- Wave speed: v = f lambda; period: T = 1/f\n- Mirror formula: 1/f = 1/u + 1/v (real quantities positive)\n- Lens formula: 1/f = 1/v - 1/u; magnification = image height / object height\n- Lens power: P = 1/f, with f in metres, in dioptres\n- Ohm\'s law: V = IR; series: R = R1 + R2 + R3; parallel: 1/R = 1/R1 + 1/R2\n- Electrical power: P = VI = I^2 R = V^2/R; energy = power x time\n- Refractive index: n = c/v; critical angle: sin C = 1/n\n- Simple pendulum: T = 2 pi sqrt(L/g); SHM acceleration: a = -(omega^2) x\n- Circular motion: F = mv^2/r, a = v^2/r, time for one revolution = 2 pi r / v\n- Gravitation: F = G m1 m2 / r^2; weight: W = mg\n- Transformer: Vs/Vp = Ns/Np; force on a conductor: F = BIL'
  },
  {
    subject: 'Physics',
    type: 'sheet',
    topic: 'Units and constants',
    title: 'SI units and standard values',
    body: '- SI base units: metre, kilogram, second, ampere, kelvin, mole, candela\n- Derived units: force N, work and energy J, power W, pressure Pa, frequency Hz, charge C, resistance ohm, magnetic flux density T, activity Bq, lens power D\n- Speed of light in vacuum: 3 x 10^8 m/s\n- Acceleration due to gravity: g = 10 m/s^2, about 9.8 m/s^2; on the moon g = 1.6 m/s^2\n- Speed of sound in air at room temperature: about 340 m/s; fastest in steel, slowest in air\n- Atmospheric pressure at sea level: about 1 x 10^5 Pa\n- Density of water: 1000 kg/m^3\n- Specific heat capacity of water: 4200 J/kg K; specific latent heat of fusion of ice: 3.36 x 10^5 J/kg\n- Heat capacity of a sample has unit J/K; specific heat capacity has unit J/kg K\n- Normal near point of the human eye: 25 cm; audible range: 20 Hz to 20,000 Hz\n- 1 horsepower = 746 W; 1 kWh = 3.6 x 10^6 J; 1 W = 1 J/s\n- 72 km/h = 20 m/s (divide by 3.6); K = degrees Celsius + 273\n- Escape velocity from the earth: about 11.2 km/s; g is greatest at the poles\n- Weight on the moon is about one sixth of the weight on the earth; mass never changes\n- Carbon-14 half-life: about 5730 years; after 2 half-lives one quarter of the sample remains\n- Useful numbers: pi = 22/7, sin(45 degrees) = 0.707, sqrt(2) = 1.414'
  },
  {
    subject: 'Physics',
    type: 'sheet',
    topic: 'Definitions',
    title: 'Definitions to learn word for word',
    body: '- Scalar: a quantity with magnitude only. Vector: a quantity with magnitude and direction\n- Speed: distance travelled per unit time. Velocity: displacement per unit time\n- Acceleration: the rate of change of velocity, a = (v - u)/t\n- Inertia: the tendency of a body to remain at rest or to continue uniform motion unless a resultant force acts\n- Momentum: mass x velocity, unit kg m/s. Impulse: force x time, unit N s\n- Work: force x distance moved in the direction of the force, unit J\n- Power: the rate of doing work, unit W\n- Efficiency: useful work output divided by energy input, expressed as a percentage\n- Pressure: force per unit area, unit Pa. Density: mass per unit volume\n- Specific heat capacity: heat needed to raise 1 kg of a substance by 1 degree Celsius\n- Specific latent heat: heat needed to change the state of 1 kg of a substance with no change in temperature\n- Frequency: complete vibrations per second, unit Hz. Period: time for one vibration\n- Wavelength: distance between two consecutive points in phase. Amplitude: maximum displacement from equilibrium\n- Refractive index: ratio of the speed of light in vacuum to the speed in the medium\n- Critical angle: the angle of incidence in the denser medium that gives an angle of refraction of 90 degrees\n- Magnification: image height divided by object height\n- Half-life: the time taken for half of the nuclei present in a radioactive sample to decay\n- Rectification: the conversion of alternating current into direct current'
  }
);
