window.QUESTION_BANK = (window.QUESTION_BANK || []).concat([
  { s: 'Biology', q: 'Which organelle is commonly called the powerhouse of the cell?', o: ['Nucleus', 'Ribosome', 'Mitochondrion', 'Vacuole'], a: 2 },
  { s: 'Biology', q: 'The organelle in which photosynthesis takes place is the:', o: ['Golgi body', 'Chloroplast', 'Lysosome', 'Cell wall'], a: 1 },
  { s: 'Biology', q: 'The cell theory of life was proposed by:', o: ['Schleiden and Schwann', 'Robert Hooke', 'Leeuwenhoek', 'Watson and Crick'], a: 0 },
  { s: 'Biology', q: 'All living organisms are built up of which basic structural unit?', o: ['Organelle', 'Tissue', 'Organ', 'Cell'], a: 3 },
  { s: 'Biology', q: 'The rigid outer layer of a plant cell is the:', o: ['Cell membrane', 'Cell wall', 'Cytoplasm', 'Nucleus'], a: 1 },
  { s: 'Biology', q: 'Protein synthesis in the cell is carried out by the:', o: ['Golgi body', 'Mitochondrion', 'Ribosomes', 'Vacuole'], a: 2 },
  { s: 'Biology', q: 'Which organelle contains hydrolytic enzymes for intracellular digestion?', o: ['Lysosome', 'Chloroplast', 'Ribosome', 'Nucleus'], a: 0 },
  { s: 'Biology', q: 'The site of aerobic respiration in the cell is the:', o: ['Chloroplast', 'Nucleus', 'Cell wall', 'Mitochondrion'], a: 3 },
  { s: 'Biology', q: 'The jelly-like substance that fills the cell is the:', o: ['Nucleus', 'Cytoplasm', 'Cell wall', 'Vacuole'], a: 1 },
  { s: 'Biology', q: 'The movement of particles from a region of high concentration to low concentration is:', o: ['Osmosis', 'Active transport', 'Diffusion', 'Pinocytosis'], a: 2 },
  { s: 'Biology', q: 'The selectively permeable structure that controls entry and exit of substances is the:', o: ['Cell membrane', 'Cell wall', 'Vacuole', 'Nucleus'], a: 0 },
  { s: 'Biology', q: 'Which of the following organisms is unicellular?', o: ['Hydra', 'Planaria', 'Amoeba', 'Earthworm'], a: 2 },
  { s: 'Biology', q: 'Which structure is present in plant cells but absent in animal cells?', o: ['Mitochondrion', 'Cell wall', 'Nucleus', 'Ribosome'], a: 1 },
  { s: 'Biology', q: 'The organelle with stacked membranous sacs called grana is the:', o: ['Chloroplast', 'Golgi body', 'Mitochondrion', 'Lysosome'], a: 0 },
  { s: 'Biology', q: 'The part of the nucleus where ribosomes are produced is the:', o: ['Cytoplasm', 'Golgi body', 'Nucleolus', 'Vacuole'], a: 2 },
  { s: 'Biology', q: 'A cell that lacks a membrane-bound nucleus is described as:', o: ['Prokaryotic', 'Eukaryotic', 'Multicellular', 'Unicellular'], a: 0 },
  { s: 'Biology', q: 'Which of the following is a prokaryote?', o: ['Euglena', 'Bacterium', 'Amoeba', 'Paramecium'], a: 1 },
  { s: 'Biology', q: 'The basic level of organisation in all living things is the:', o: ['Cell', 'Tissue', 'Organ', 'Organelle'], a: 0 },
  { s: 'Biology', q: 'A group of cells of similar structure performing the same function forms a:', o: ['Organ', 'Organ system', 'Population', 'Tissue'], a: 3 },
  { s: 'Biology', q: 'In the classification of living things, the largest taxonomic group is the:', o: ['Phylum', 'Class', 'Kingdom', 'Order'], a: 2 },
  { s: 'Biology', q: 'The taxonomic group whose members can interbreed to produce fertile offspring is the:', o: ['Genus', 'Species', 'Family', 'Phylum'], a: 1 },
  { s: 'Biology', q: 'Binomial nomenclature was introduced by:', o: ['Carolus Linnaeus', 'Charles Darwin', 'Gregor Mendel', 'Louis Pasteur'], a: 0 },
  { s: 'Biology', q: 'In the name Escherichia coli, the word Escherichia represents the:', o: ['Genus', 'Species', 'Family', 'Order'], a: 0 },
  { s: 'Biology', q: 'Organisms that manufacture their own food are called:', o: ['Autotrophs', 'Heterotrophs', 'Saprophytes', 'Parasites'], a: 0 },
  { s: 'Biology', q: 'An organism that feeds on dead organic matter is a:', o: ['Predator', 'Saprophyte', 'Herbivore', 'Parasite'], a: 1 },
  { s: 'Biology', q: 'Which of the following animals is a vertebrate?', o: ['Snail', 'Crab', 'Catfish', 'Cockroach'], a: 2 },
  { s: 'Biology', q: 'The phylum to which human beings belong is:', o: ['Arthropoda', 'Mollusca', 'Chordata', 'Coelenterata'], a: 2 },
  { s: 'Biology', q: 'A distinguishing feature of class Mammalia is the presence of:', o: ['Scales', 'Feathers', 'Hair and mammary glands', 'Gills'], a: 2 },
  { s: 'Biology', q: 'Which of the following animals is cold-blooded?', o: ['Man', 'Frog', 'Hen', 'Goat'], a: 1 },
  { s: 'Biology', q: 'The grouping of organisms into groups based on shared features is called:', o: ['Classification', 'Evolution', 'Adaptation', 'Reproduction'], a: 0 },
  { s: 'Biology', q: 'The process by which green plants manufacture their food is:', o: ['Photosynthesis', 'Respiration', 'Transpiration', 'Absorption'], a: 0 },
  { s: 'Biology', q: 'The gas absorbed by plants from the atmosphere during photosynthesis is:', o: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'], a: 1 },
  { s: 'Biology', q: 'The end products of photosynthesis are:', o: ['Carbon dioxide and water', 'Glucose and oxygen', 'Glucose and carbon dioxide', 'Oxygen and water'], a: 1 },
  { s: 'Biology', q: 'A nutrient needed by the body in large quantities is called a:', o: ['Vitamin', 'Mineral salt', 'Macronutrient', 'Trace element'], a: 2 },
  { s: 'Biology', q: 'Deficiency of vitamin C in the diet causes:', o: ['Scurvy', 'Rickets', 'Beriberi', 'Night blindness'], a: 0 },
  { s: 'Biology', q: 'Rickets in children is caused by a deficiency of:', o: ['Vitamin A', 'Vitamin D', 'Vitamin B1', 'Vitamin K'], a: 1 },
  { s: 'Biology', q: 'Night blindness is caused by a deficiency of:', o: ['Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin K'], a: 0 },
  { s: 'Biology', q: 'Which of the following foodstuffs is a carbohydrate?', o: ['Starch', 'Protein', 'Fat', 'Vitamin'], a: 0 },
  { s: 'Biology', q: 'The class of food that supplies the most energy per gram is:', o: ['Carbohydrate', 'Protein', 'Fat', 'Vitamin'], a: 2 },
  { s: 'Biology', q: 'The enzyme in saliva that digests starch is:', o: ['Pepsin', 'Salivary amylase', 'Trypsin', 'Lipase'], a: 1 },
  { s: 'Biology', q: 'The enzyme secreted in the stomach that digests protein is:', o: ['Trypsin', 'Pepsin', 'Amylase', 'Lipase'], a: 1 },
  { s: 'Biology', q: 'Bile juice is produced by the:', o: ['Pancreas', 'Gall bladder', 'Liver', 'Stomach'], a: 2 },
  { s: 'Biology', q: 'A protein food that contains all essential amino acids is described as:', o: ['Complete protein', 'Incomplete protein', 'Carbohydrate', 'Roughage'], a: 0 },
  { s: 'Biology', q: 'Roughage in the diet is mainly provided by:', o: ['Fats', 'Proteins', 'Cellulose', 'Simple sugars'], a: 2 },
  { s: 'Biology', q: 'Kwashiorkor is caused by a deficiency of:', o: ['Carbohydrates', 'Protein', 'Fats', 'Vitamin C'], a: 1 },
  { s: 'Biology', q: 'The blood vessel that carries blood away from the heart is the:', o: ['Vein', 'Artery', 'Capillary', 'Venule'], a: 1 },
  { s: 'Biology', q: 'The blood group regarded as the universal donor is:', o: ['AB', 'A', 'B', 'O'], a: 3 },
  { s: 'Biology', q: 'Blood plasma is responsible for transporting:', o: ['Oxygen only', 'Waste products and nutrients', 'Platelets only', 'Carbon dioxide only'], a: 1 },
  { s: 'Biology', q: 'The oxygen-carrying pigment found in red blood cells is:', o: ['Haemoglobin', 'Chlorophyll', 'Melanin', 'Bile pigment'], a: 0 },
  { s: 'Biology', q: 'Which component of the blood is responsible for clotting?', o: ['Red blood cell', 'White blood cell', 'Platelet', 'Lymphocyte'], a: 2 },
  { s: 'Biology', q: 'The main function of white blood cells is to:', o: ['Carry oxygen', 'Fight infection', 'Clot blood', 'Transport nutrients'], a: 1 },
  { s: 'Biology', q: 'The organ that pumps blood around the body is the:', o: ['Liver', 'Kidney', 'Heart', 'Lung'], a: 2 },
  { s: 'Biology', q: 'The human heart has how many chambers?', o: ['Two', 'Three', 'Four', 'Five'], a: 2 },
  { s: 'Biology', q: 'Valves in the heart are useful because they prevent:', o: ['Backflow of blood', 'Blood clotting', 'Loss of oxygen', 'The heartbeat'], a: 0 },
  { s: 'Biology', q: 'Water and mineral salts are conducted in plants by the:', o: ['Xylem', 'Phloem', 'Cambium', 'Cortex'], a: 0 },
  { s: 'Biology', q: 'Translocation of food in plants takes place through the:', o: ['Xylem', 'Phloem', 'Pith', 'Epidermis'], a: 1 },
  { s: 'Biology', q: 'The loss of water vapour from the leaves of plants is called:', o: ['Transpiration', 'Respiration', 'Guttation', 'Perspiration'], a: 0 },
  { s: 'Biology', q: 'Transpiration pull is important in the:', o: ['Absorption of water', 'Formation of food', 'Digestion of starch', 'Movement of the leaf'], a: 0 },
  { s: 'Biology', q: 'The movement of water molecules through a semi-permeable membrane is:', o: ['Osmosis', 'Diffusion', 'Active transport', 'Plasmolysis'], a: 0 },
  { s: 'Biology', q: 'A plant cell placed in a strong sugar solution becomes:', o: ['Turgid', 'Plasmolysed', 'Bursting', 'Enlarged'], a: 1 },
  { s: 'Biology', q: 'A plant cell placed in pure water becomes:', o: ['Plasmolysed', 'Turgid', 'Shrivelled', 'Dead'], a: 1 },
  { s: 'Biology', q: 'Anaerobic respiration in yeast produces:', o: ['Lactic acid', 'Alcohol and carbon dioxide', 'Water and carbon dioxide', 'Proteins'], a: 1 },
  { s: 'Biology', q: 'The products of aerobic respiration are:', o: ['Glucose and oxygen', 'Carbon dioxide, water and energy', 'Alcohol and carbon dioxide', 'Lactic acid and energy'], a: 1 },
  { s: 'Biology', q: 'The process by which food is broken down to release energy is called:', o: ['Respiration', 'Photosynthesis', 'Transpiration', 'Excretion'], a: 0 },
  { s: 'Biology', q: 'Energy for all life processes is released during:', o: ['Digestion', 'Respiration', 'Absorption', 'Assimilation'], a: 1 },
  { s: 'Biology', q: 'Which of the following nutrients is energy-yielding?', o: ['Vitamin', 'Carbohydrate', 'Mineral salt', 'Water'], a: 1 },
  { s: 'Biology', q: 'The respiratory organ of a fish is the:', o: ['Lungs', 'Gills', 'Skin', 'Trachea'], a: 1 },
  { s: 'Biology', q: 'In insects, air enters the body through the:', o: ['Spiracles', 'Stomata', 'Gills', 'Alveoli'], a: 0 },
  { s: 'Biology', q: 'Gas exchange in the leaves of plants occurs through the:', o: ['Stomata', 'Lenticels', 'Cuticle', 'Epidermis'], a: 0 },
  { s: 'Biology', q: 'The main excretory organ that produces urine in humans is the:', o: ['Liver', 'Kidney', 'Skin', 'Lung'], a: 1 },
  { s: 'Biology', q: 'Which structure carries out the filtering function of the kidney?', o: ['Neuron', 'Nephron', 'Alveolus', 'Villus'], a: 1 },
  { s: 'Biology', q: 'Urine is conveyed from the kidney to the urinary bladder by the:', o: ['Urethra', 'Ureter', 'Renal artery', 'Vas deferens'], a: 1 },
  { s: 'Biology', q: 'Excretion in plants takes place mainly through:', o: ['Shedding of leaves and transpiration', 'Kidneys', 'Sweat glands', 'Lungs'], a: 0 },
  { s: 'Biology', q: 'The nitrogenous waste of protein metabolism removed by the kidney is:', o: ['Urea', 'Carbon dioxide', 'Bile pigment', 'Sweat'], a: 0 },
  { s: 'Biology', q: 'The vessel that carries blood to the kidney for filtration is the:', o: ['Renal artery', 'Renal vein', 'Hepatic vein', 'Pulmonary artery'], a: 0 },
  { s: 'Biology', q: 'The fusion of male and female gametes is called:', o: ['Fertilization', 'Germination', 'Pollination', 'Parturition'], a: 0 },
  { s: 'Biology', q: 'The male reproductive cell in humans is the:', o: ['Ovum', 'Zygote', 'Spermatozoon', 'Ovule'], a: 2 },
  { s: 'Biology', q: 'The organ in which the foetus develops is the:', o: ['Ovary', 'Uterus', 'Fallopian tube', 'Vagina'], a: 1 },
  { s: 'Biology', q: 'Fertilization in humans normally takes place in the:', o: ['Uterus', 'Ovary', 'Fallopian tube', 'Vagina'], a: 2 },
  { s: 'Biology', q: 'The structure linking the foetus to the placenta is the:', o: ['Umbilical cord', 'Oviduct', 'Cervix', 'Amnion'], a: 0 },
  { s: 'Biology', q: 'During childbirth, the baby passes out through the:', o: ['Ovary', 'Cervix and vagina', 'Umbilical cord', 'Placenta'], a: 1 },
  { s: 'Biology', q: 'The process of giving birth to a baby is called:', o: ['Ovulation', 'Parturition', 'Implantation', 'Menstruation'], a: 1 },
  { s: 'Biology', q: 'The release of a mature ovum from the ovary is called:', o: ['Ovulation', 'Menstruation', 'Fertilization', 'Gestation'], a: 0 },
  { s: 'Biology', q: 'In humans, the period from fertilization to birth is about:', o: ['Nine months', 'Three months', 'Six months', 'Twelve months'], a: 0 },
  { s: 'Biology', q: 'Identical twins develop from:', o: ['Two fertilized eggs', 'A single fertilized egg', 'Three separate eggs', 'Unfertilized eggs'], a: 1 },
  { s: 'Biology', q: 'In plants, growth occurs mainly in regions called:', o: ['Meristems', 'Cortex', 'Pith', 'Epidermis'], a: 0 },
  { s: 'Biology', q: 'The region of the root responsible for increase in length is the:', o: ['Root cap', 'Apical meristem', 'Zone of maturation', 'Endodermis'], a: 1 },
  { s: 'Biology', q: 'An increase in the number of cells in an organism is called:', o: ['Cell division', 'Cell expansion', 'Cell differentiation', 'Cell shrinkage'], a: 0 },
  { s: 'Biology', q: 'The type of cell division that produces gametes is:', o: ['Mitosis', 'Meiosis', 'Binary fission', 'Budding'], a: 1 },
  { s: 'Biology', q: 'In human beings, the period of fastest growth is:', o: ['Infancy', 'Old age', 'Middle age', 'Late adult life'], a: 0 },
  { s: 'Biology', q: 'The functional unit of the nervous system is the:', o: ['Nephron', 'Neuron', 'Villus', 'Osteocyte'], a: 1 },
  { s: 'Biology', q: 'The part of the brain that controls balance and posture is the:', o: ['Cerebrum', 'Medulla oblongata', 'Hypothalamus', 'Cerebellum'], a: 3 },
  { s: 'Biology', q: 'The part of the brain that controls breathing and heartbeat is the:', o: ['Cerebrum', 'Cerebellum', 'Medulla oblongata', 'Thalamus'], a: 2 },
  { s: 'Biology', q: 'The part of the brain responsible for thinking and intelligence is the:', o: ['Cerebellum', 'Medulla oblongata', 'Spinal cord', 'Cerebrum'], a: 3 },
  { s: 'Biology', q: 'The specialised cells that transmit nerve impulses are the:', o: ['Epithelial cells', 'Muscle cells', 'Neurons', 'Blood cells'], a: 2 },
  { s: 'Biology', q: 'The junction between two neurons is called a:', o: ['Axon', 'Dendrite', 'Synapse', 'Myelin sheath'], a: 2 },
  { s: 'Biology', q: 'The part of the neuron that carries impulses away from the cell body is the:', o: ['Dendron', 'Axon', 'Nucleus', 'Synaptic knob'], a: 1 },
  { s: 'Biology', q: 'The spinal cord is protected by the:', o: ['Skull', 'Ribs', 'Pelvis', 'Vertebrae'], a: 3 },
  { s: 'Biology', q: 'A rapid, automatic response to a stimulus is a:', o: ['Tropism', 'Taxis', 'Reflex action', 'Voluntary movement'], a: 2 },
  { s: 'Biology', q: 'The receptor cells that function in vision under dim light are the:', o: ['Cones', 'Rods', 'Lens', 'Iris'], a: 1 },
  { s: 'Biology', q: 'The structure that changes the shape of the lens for focusing is the:', o: ['Retina', 'Cornea', 'Ciliary muscle', 'Sclera'], a: 2 },
  { s: 'Biology', q: 'The structure of the eye that controls the amount of light entering it is the:', o: ['Lens', 'Retina', 'Vitreous humour', 'Iris'], a: 3 },
  { s: 'Biology', q: 'The inversion of images formed on the retina is corrected by the:', o: ['Lens', 'Cornea', 'Retina', 'Brain'], a: 3 },
  { s: 'Biology', q: 'Sound waves are finally detected by the:', o: ['Eardrum', 'Cochlea', 'Ossicles', 'Pinna'], a: 1 },
  { s: 'Biology', q: 'The receptor organ for balance in the ear is the:', o: ['Eardrum', 'Auditory nerve', 'Semicircular canals', 'Ossicles'], a: 2 },
  { s: 'Biology', q: 'The receptor cells for the sense of smell are located in the:', o: ['Tongue', 'Ear', 'Skin', 'Nasal epithelium'], a: 3 },
  { s: 'Biology', q: 'Taste buds are located mainly on the:', o: ['Nose', 'Lips', 'Tongue', 'Throat'], a: 2 },
  { s: 'Biology', q: 'The skin receptor that detects changes in temperature is a:', o: ['Mechanoreceptor', 'Photoreceptor', 'Baroreceptor', 'Thermoreceptor'], a: 3 },
  { s: 'Biology', q: 'The bending of a shoot towards light is called:', o: ['Geotropism', 'Phototropism', 'Hydrotropism', 'Thigmotropism'], a: 1 },
  { s: 'Biology', q: 'The growth of roots downwards into the soil is due to:', o: ['Phototropism', 'Geotropism', 'Hydrotropism', 'Chemotropism'], a: 1 },
  { s: 'Biology', q: 'The essential reproductive parts of a flower are the:', o: ['Petal', 'Sepal', 'Stamen and carpel', 'Peduncle'], a: 2 },
  { s: 'Biology', q: 'The male reproductive part of a flower is the:', o: ['Carpel', 'Petal', 'Sepal', 'Stamen'], a: 3 },
  { s: 'Biology', q: 'The female reproductive part of a flower is the:', o: ['Stamen', 'Anther', 'Carpel', 'Filament'], a: 2 },
  { s: 'Biology', q: 'Pollen grains are produced in the:', o: ['Ovary', 'Stigma', 'Style', 'Anther'], a: 3 },
  { s: 'Biology', q: 'The transfer of pollen grains from the anther to the stigma is called:', o: ['Pollination', 'Fertilization', 'Germination', 'Seed dispersal'], a: 0 },
  { s: 'Biology', q: 'In self-pollination, pollen is transferred to the stigma of:', o: ['The same flower or another flower on the same plant', 'A different plant of another species', 'A flower of a different genus', 'The root of the plant'], a: 0 },
  { s: 'Biology', q: 'The protective covering of a seed is the:', o: ['Testa', 'Cotyledon', 'Radicle', 'Plumule'], a: 0 },
  { s: 'Biology', q: 'The part of the seed that develops into the shoot is the:', o: ['Radicle', 'Cotyledon', 'Testa', 'Plumule'], a: 3 },
  { s: 'Biology', q: 'The part of the seed that develops into the root is the:', o: ['Plumule', 'Cotyledon', 'Hilum', 'Radicle'], a: 3 },
  { s: 'Biology', q: 'Seeds dispersed by wind are usually provided with:', o: ['Wings or feathery appendages', 'Thorns', 'Bright colours', 'Fleshy pulp'], a: 0 },
  { s: 'Biology', q: 'The functional units of heredity are the:', o: ['Genes', 'Gametes', 'Zygotes', 'Traits'], a: 0 },
  { s: 'Biology', q: 'The number of chromosomes in a human somatic cell is:', o: ['Twenty-three', 'Forty-four', 'Forty-six', 'Forty-eight'], a: 2 },
  { s: 'Biology', q: 'How many chromosomes are contained in a human gamete?', o: ['Twenty-three', 'Forty-six', 'Forty-four', 'Twenty-two'], a: 0 },
  { s: 'Biology', q: 'A pea plant with the genetic constitution Tt is described as:', o: ['Homozygous dominant', 'Homozygous recessive', 'Heterozygous', 'Hemizygous'], a: 2 },
  { s: 'Biology', q: 'The phenotypic ratio of the F2 generation of a monohybrid cross is:', o: ['One to one', 'Nine to three to three to one', 'Three to one', 'One to two to one'], a: 2 },
  { s: 'Biology', q: 'The genotypic ratio of the F2 generation of a monohybrid cross is:', o: ['Three to one', 'One to one', 'One to two to one', 'Nine to three to three to one'], a: 2 },
  { s: 'Biology', q: 'The blood group that can receive blood from any other group is:', o: ['O', 'A', 'B', 'AB'], a: 3 },
  { s: 'Biology', q: 'The chromosome combination that determines a male in humans is:', o: ['XX', 'YY', 'XO', 'XY'], a: 3 },
  { s: 'Biology', q: 'Mendel carried out his experiments on inheritance using:', o: ['Pea plants', 'Fruit flies', 'Mice', 'Bacteria'], a: 0 },
  { s: 'Biology', q: 'A person with blood group O has which antigens on the red blood cells?', o: ['A and B antigens', 'A antigen only', 'B antigen only', 'No antigens'], a: 3 },
  { s: 'Biology', q: 'Crossing over of chromosomes occurs during:', o: ['Metaphase of mitosis', 'Interphase', 'Anaphase II', 'Prophase I of meiosis'], a: 3 },
  { s: 'Biology', q: 'A permanent change in the base sequence of DNA is called:', o: ['Variation', 'Selection', 'Adaptation', 'Mutation'], a: 3 },
  { s: 'Biology', q: 'A change in the number of chromosomes in an organism is called:', o: ['Gene mutation', 'Point mutation', 'Recombination', 'Chromosomal aberration'], a: 3 },
  { s: 'Biology', q: 'The process by which better adapted organisms survive and reproduce is:', o: ['Genetic drift', 'Mutation', 'Gene flow', 'Natural selection'], a: 3 },
  { s: 'Biology', q: 'The forelimbs of a whale and a bat are examples of:', o: ['Analogous structures', 'Vestigial structures', 'Adaptive structures', 'Homologous structures'], a: 3 },
  { s: 'Biology', q: 'The living components of an ecosystem are described as:', o: ['Biotic factors', 'Abiotic factors', 'Edaphic factors', 'Climatic factors'], a: 0 },
  { s: 'Biology', q: 'Which of the following is a non-living factor in an ecosystem?', o: ['Temperature', 'Plants', 'Animals', 'Decomposers'], a: 0 },
  { s: 'Biology', q: 'The flow of energy through a food chain is:', o: ['Unidirectional', 'Cyclical', 'Reversible', 'Infinite'], a: 0 },
  { s: 'Biology', q: 'Energy trapped by producers in an ecosystem comes from:', o: ['Chemosynthesis', 'Respiration', 'Photosynthesis', 'Decomposition'], a: 2 },
  { s: 'Biology', q: 'In the food chain grass to grasshopper to lizard to snake, the lizard is a:', o: ['Producer', 'Primary consumer', 'Secondary consumer', 'Decomposer'], a: 2 },
  { s: 'Biology', q: 'Organisms that break down dead organic matter and return nutrients to the soil are:', o: ['Producers', 'Consumers', 'Decomposers', 'Predators'], a: 2 },
  { s: 'Biology', q: 'Roughly what percentage of energy passes from one trophic level to the next?', o: ['Ten percent', 'Fifty percent', 'Ninety percent', 'One hundred percent'], a: 0 },
  { s: 'Biology', q: 'The relationship between a clownfish and a sea anemone is:', o: ['Parasitism', 'Predation', 'Commensalism', 'Mutualism'], a: 3 },
  { s: 'Biology', q: 'A relationship in which one organism benefits while the other is unaffected is:', o: ['Mutualism', 'Commensalism', 'Parasitism', 'Competition'], a: 1 },
  { s: 'Biology', q: 'Malaria is transmitted by the female:', o: ['Anopheles mosquito', 'Aedes mosquito', 'Tsetse fly', 'Sandfly'], a: 0 },
  { s: 'Biology', q: 'The causative agent of malaria is a:', o: ['Virus', 'Bacterium', 'Protozoan', 'Fungus'], a: 2 },
  { s: 'Biology', q: 'Typhoid fever is caused by:', o: ['A virus', 'A bacterium', 'A protozoan', 'A worm'], a: 1 },
  { s: 'Biology', q: 'HIV infection damages the body mainly by destroying:', o: ['Red blood cells', 'Platelets', 'Lymphocytes', 'Clotting factors'], a: 2 },
  { s: 'Biology', q: 'Cholera is spread mainly through:', o: ['Contaminated food and water', 'Mosquito bites', 'Air droplets alone', 'Contact with soil'], a: 0 },
  { s: 'Biology', q: 'The parasite that causes sleeping sickness is:', o: ['Plasmodium', 'Entamoeba histolytica', 'Ascaris lumbricoides', 'Trypanosoma'], a: 3 },
  { s: 'Biology', q: 'The intermediate host of the malaria parasite is the:', o: ['Man', 'Tsetse fly', 'Snail', 'Female Anopheles mosquito'], a: 3 },
  { s: 'Biology', q: 'Ascariasis is contracted by:', o: ['A mosquito bite', 'Ingestion of contaminated food or water', 'Airborne droplets', 'Direct skin contact'], a: 1 },
  { s: 'Biology', q: 'The type of immunity given by a vaccination is:', o: ['Passive immunity', 'Natural immunity', 'Congenital immunity', 'Active immunity'], a: 3 },
  { s: 'Biology', q: 'Antibodies in the blood are produced by:', o: ['Red blood cells', 'Platelets', 'Lymphocytes', 'Neutrophils'], a: 2 },
  { s: 'Biology', q: 'Antibiotics are effective in the treatment of diseases caused by:', o: ['Viruses', 'Prions', 'Bacteria', 'Protozoa'], a: 2 },
  { s: 'Biology', q: 'The immunity a baby gains from its mother through the placenta is:', o: ['Active immunity', 'Passive immunity', 'Artificial acquired immunity', 'Cell-mediated immunity'], a: 1 },
  { s: 'Biology', q: 'Which of the following organisms is a fungus?', o: ['Euglena', 'Amoeba', 'Paramecium', 'Mushroom'], a: 3 },
  { s: 'Biology', q: 'Bacteria multiply mainly by:', o: ['Budding', 'Sporulation', 'Fragmentation', 'Binary fission'], a: 3 },
  { s: 'Biology', q: 'Viruses differ from bacteria because viruses:', o: ['Have a cell wall', 'Are always motile', 'Reproduce only inside a host cell', 'Are prokaryotic'], a: 2 },
  { s: 'Biology', q: 'The micro-organism used in bread making is:', o: ['Lactobacillus', 'Rhizobium', 'Aspergillus', 'Yeast'], a: 3 },
  { s: 'Biology', q: 'The bacterium that fixes atmospheric nitrogen in root nodules is:', o: ['Escherichia coli', 'Salmonella', 'Staphylococcus', 'Rhizobium'], a: 3 },
  { s: 'Biology', q: 'Mycorrhiza is a symbiotic association between a fungus and:', o: ['Leaves', 'Flowers', 'Stem', 'Plant roots'], a: 3 },
  { s: 'Biology', q: 'The bacterial disease that damages nerves and causes loss of feeling is:', o: ['Tuberculosis', 'Cholera', 'Measles', 'Leprosy'], a: 3 },
  { s: 'Biology', q: 'Tuberculosis mainly affects the:', o: ['Liver', 'Kidney', 'Heart', 'Lungs'], a: 3 },
  { s: 'Biology', q: 'The surest way of preventing typhoid fever is by:', o: ['Eating raw food', 'Sharing utensils', 'Sleeping outdoors', 'Boiling drinking water'], a: 3 },
  { s: 'Biology', q: 'The disease that was completely eradicated worldwide through vaccination is:', o: ['Malaria', 'Cholera', 'Measles', 'Smallpox'], a: 3 },
  { s: 'Biology', q: 'Pollination by wind is characteristic of:', o: ['Orchids', 'Sunflower', 'Mango', 'Grasses'], a: 3 },
  { s: 'Biology', q: 'A flower adapted for insect pollination usually has:', o: ['Small dull petals with no scent', 'No nectar or fragrance', 'Green inconspicuous petals', 'Bright petals, nectar and fragrance'], a: 3 },
  { s: 'Biology', q: 'In the leaf, the tissue that carries out most photosynthesis is the:', o: ['Epidermis', 'Xylem', 'Cuticle', 'Mesophyll'], a: 3 },
  { s: 'Biology', q: 'The tissue that gives mechanical strength to the stem is the:', o: ['Parenchyma', 'Epidermis', 'Xylem', 'Sclerenchyma'], a: 3 },
  { s: 'Biology', q: 'Secondary growth in a dicotyledonous stem is caused by the:', o: ['Epidermis', 'Pith', 'Cortex', 'Vascular cambium'], a: 3 },
  { s: 'Biology', q: 'Stomata are flanked by specialized cells called:', o: ['Epidermal hairs', 'Cuticle', 'Cortex cells', 'Guard cells'], a: 3 },
  { s: 'Biology', q: 'The upward movement of water in tall trees is best explained by the:', o: ['Root pressure theory', 'Imbibition', 'Cohesion-tension theory', 'Active transport theory'], a: 2 },
  { s: 'Biology', q: 'Stomata close during water stress because of:', o: ['Increased turgor of guard cells', 'Cuticle thickening', 'Wax deposition', 'Loss of turgor in guard cells'], a: 3 },
  { s: 'Biology', q: 'Wilting of a plant is a result of:', o: ['Excess water in cells', 'Over supply of minerals', 'Loss of cell turgor', 'High light intensity'], a: 2 },
  { s: 'Biology', q: 'The plant hormone that promotes cell elongation and phototropism is:', o: ['Gibberellin', 'Cytokinin', 'Abscisic acid', 'Auxin'], a: 3 },
  { s: 'Biology', q: 'The scientific study of the relationship between organisms and their environment is:', o: ['Taxonomy', 'Physiology', 'Ecology', 'Anatomy'], a: 2 },
  { s: 'Biology', q: 'The gradual replacement of one community of organisms by another over time is called:', o: ['Competition', 'Adaptation', 'Ecological succession', 'Migration'], a: 2 },
  { s: 'Biology', q: 'All organisms of the same species living in the same area at the same time form a:', o: ['Community', 'Ecosystem', 'Population', 'Biome'], a: 2 },
  { s: 'Biology', q: 'The protection of wildlife and their habitats against extinction is called:', o: ['Cultivation', 'Domestication', 'Conservation', 'Propagation'], a: 2 }
]);
