window.QUESTION_BANK = (window.QUESTION_BANK || []).concat([
  { s: 'History', q: 'The Sokoto Caliphate was founded in 1804 by:', o: ['Usman dan Fodio', 'Muhammad Bello', 'Abdullahi dan Fodio', 'Aliyu Babba'], a: 0 },
  { s: 'History', q: 'The political head of the Oyo Empire was known as the:', o: ['Ooni', 'Alaafin', 'Obi', 'Eze'], a: 1 },
  { s: 'History', q: 'Kings of the Kanem-Bornu Empire bore the traditional title:', o: ['Sarki', 'Shehu', 'Mai', 'Emir'], a: 2 },
  { s: 'History', q: 'According to legend, the seven Hausa states of the Hausa Bakwai were founded by descendants of:', o: ['Askia Muhammad', 'Bayajidda', 'Ali Ghaji', 'Umar Nagwamatatsi'], a: 1 },
  { s: 'History', q: 'Kano was famous in pre-colonial times for its production and trade in:', o: ['Kola nuts', 'Fishing', 'Textile dyeing and dyed cloth', 'Ship-building'], a: 2 },
  { s: 'History', q: 'Queen Amina of Zaria is best remembered for:', o: ['Introducing Islam to Zazzau', 'Founding the Sokoto Caliphate', 'Her military conquests and the expansion of Zazzau', 'Translating the Qur\'an into Hausa'], a: 2 },
  { s: 'History', q: 'The Igbo-Ukwu bronze and copper artifacts were first excavated in 1959 by:', o: ['Thurstan Shaw', 'Kenneth Onwuka Dike', 'Lord Lugard', 'C. R. Day'], a: 0 },
  { s: 'History', q: 'The site of Igbo-Ukwu, famous for its early bronze work, lies in present-day:', o: ['Edo State', 'Kano State', 'Anambra State', 'Kogi State'], a: 2 },
  { s: 'History', q: 'The celebrated Benin bronze plaques that decorated the royal palace were produced using:', o: ['Wood carving only', 'Iron forging', 'Sun-dried clay moulding', 'The lost-wax casting technique'], a: 3 },
  { s: 'History', q: 'In the Oyo Empire, the head of the Oyo Mesi, the council that checked the Alaafin, was the:', o: ['Bashorun', 'Osi Efa', 'Agbakin', 'Aroba'], a: 0 },
  { s: 'History', q: 'The Are-Ona Kakanfo of the Oyo Empire was the:', o: ['Chief priest of Sango', 'Commander-in-chief of the army', 'Queen mother', 'Chief judge of the Mesi'], a: 1 },
  { s: 'History', q: 'The Egungun festival among the Yoruba is held in honour of:', o: ['The Alaafin personally', 'Local ward heads', 'The ancestors', 'The river gods'], a: 2 },
  { s: 'History', q: 'The Nri Kingdom of the Igbo was distinctive for its:', o: ['Control of trans-Saharan routes', 'Heavy cavalry', 'Priestly and religious authority', 'Atlantic sea ports'], a: 2 },
  { s: 'History', q: 'Ile-Ife, regarded as the cradle of Yoruba civilisation, is traditionally linked to the mythical founder:', o: ['Oranmiyan', 'Sango', 'Oduduwa', 'Obatala'], a: 2 },
  { s: 'History', q: 'The first Oba of Benin was:', o: ['Eweka I', 'Ewuare I', 'Oronmiyan', 'Ozolua'], a: 0 },
  { s: 'History', q: 'Oba Ewuare I of Benin, a great 15th-century warrior king, is popularly credited with:', o: ['Expelling the Portuguese', 'Annexing Lagos', 'Introducing a written script', 'Building the great walls of Benin'], a: 3 },
  { s: 'History', q: 'The Aro Chukwu oracle, popularly known as Long Juju, was located at:', o: ['Bonny', 'Arochukwu', 'Nri', 'Warri'], a: 1 },
  { s: 'History', q: 'The traditional political system of Igbo society is best described as:', o: ['Absolute monarchy', 'Theocratic rule', 'Feudal emirate', 'Acephalous and democratic'], a: 3 },
  { s: 'History', q: 'The Ekpe secret society was a prominent institution among the:', o: ['Tiv', 'Nupe', 'Jukun', 'Efik and Ibibio'], a: 3 },
  { s: 'History', q: 'The Jukun Kingdom, often identified with Kwararafa, was situated mainly along the:', o: ['Sokoto flood plain', 'Cross River estuary', 'Benue River valley', 'Lagos lagoon'], a: 2 },
  { s: 'History', q: 'The Nupe Kingdom was located principally along the banks of the:', o: ['Benue River', 'Cross River', 'Sokoto River', 'Niger River'], a: 3 },
  { s: 'History', q: 'Kanem-Bornu carried on long-distance trade in salt and cloth mainly with:', o: ['Western Europe', 'East Asia', 'North Africa across the Sahara', 'East Africa'], a: 2 },
  { s: 'History', q: 'From the 15th century onwards, the capital of Kanem-Bornu was:', o: ['Gwandu', 'Birni Ngazargamu', 'Kano', 'Yola'], a: 1 },
  { s: 'History', q: 'The Kano Chronicle is best described as:', o: ['A British colonial report', 'A Hausa newspaper', 'A religious treatise on jihad', 'An indigenous chronicle of the Kano kings'], a: 3 },
  { s: 'History', q: 'The military strength of the Oyo Empire rested largely on its:', o: ['Naval fleet', 'Control of seaports', 'Cavalry forces', 'Mountain artillery'], a: 2 },
  { s: 'History', q: 'The famous dye pits of Bida in Kano are evidence of the importance of:', o: ['Kola trade', 'Textile dyeing', 'Salt mining', 'Cocoa export'], a: 1 },
  { s: 'History', q: 'The Hausa state of Gobir is historically significant mainly because:', o: ['It was the capital of Benin', 'Its rulers bore the title Ooni', 'It was the stronghold from which the Sokoto Jihad was launched', 'It rejected all trade'], a: 2 },
  { s: 'History', q: 'The supreme ruler of the Sokoto Caliphate bore the title:', o: ['Mai', 'Shehu', 'Alaafin', 'Obi'], a: 1 },
  { s: 'History', q: 'The Sokoto Caliphate was organised into a number of provinces known as:', o: ['Emirates', 'Colonies', 'Free cities', 'City-states of the Igbo'], a: 0 },
  { s: 'History', q: 'The chief ideologue of the Sokoto Jihad, who wrote treatises justifying it, was:', o: ['Muhammad Bello', 'Uthman dan Fodio', 'Abdullahi dan Fodio', 'Umaru Nagwamatatsi'], a: 2 },
  { s: 'History', q: 'The immediate trigger of the Sokoto Jihad in 1804 was the conflict between Usman dan Fodio and:', o: ['The bombardment of Lagos', 'Sarki Yunfa of Gobir', 'The Berlin Conference', 'The Asante king'], a: 1 },
  { s: 'History', q: 'The Sokoto Jihad of 1804 is best classified as:', o: ['A war for control of trade routes', 'An anti-colonial war', 'A religious and social reform movement', 'A slave revolt'], a: 2 },
  { s: 'History', q: 'The Hausa states conquered by the Jihad forces in 1804-1805 included:', o: ['Benin and Oyo', 'Nupe and Jukun', 'Warri and Calabar', 'Kano and Katsina'], a: 3 },
  { s: 'History', q: 'The Songhai Empire of the Middle Niger was founded by:', o: ['Sundiata Keita', 'Askia Muhammad', 'Mansa Musa', 'Sunni Ali Ber'], a: 3 },
  { s: 'History', q: 'The Moroccan invasion of 1591 that destroyed the Songhai Empire was launched by:', o: ['Sunni Ali Ber', 'Sundiata Keita', 'Ahmad al-Mansur of Morocco', 'Askia Muhammad'], a: 2 },
  { s: 'History', q: 'Timbuktu became a great centre of learning largely because of:', o: ['Its European universities', 'Its seaport', 'The Sankore scholars', 'The gold mines nearby'], a: 2 },
  { s: 'History', q: 'Askia Muhammad is remembered as the ruler who:', o: ['Founded the Mali Empire', 'A Songhai ruler who spread Islam and reorganised the empire', 'Led the Maji Maji rebellion', 'Discovered the River Niger'], a: 1 },
  { s: 'History', q: 'The Mali Empire was founded in the 13th century by:', o: ['Mansa Musa', 'Sunni Ali Ber', 'Sundiata Keita', 'Askia Muhammad'], a: 2 },
  { s: 'History', q: 'The 1324 pilgrimage to Mecca of Mansa Musa is significant because it:', o: ['Led to the destruction of Mali', 'Ended the slave trade', 'Brought Mali to world attention', 'Caused the Berlin Conference'], a: 2 },
  { s: 'History', q: 'The wealth of the medieval Ghana Empire was derived mainly from:', o: ['Ship-building', 'The gold and salt trade', 'Cocoa export', 'Fishing'], a: 1 },
  { s: 'History', q: 'The Ghana Empire of the Soninke was located in present-day:', o: ['Ghana only', 'Nigeria', 'Mauritania and western Mali', 'Kenya'], a: 2 },
  { s: 'History', q: 'To reconstruct the history of societies that left no written records, historians rely mainly on:', o: ['Royal chronicles', 'Newspapers', 'Census returns', 'Oral tradition'], a: 3 },
  { s: 'History', q: 'A historian who uses the account of a person who actually witnessed an event is using:', o: ['A secondary source', 'A primary source', 'A textbook', 'An encyclopedia'], a: 1 },
  { s: 'History', q: 'A major weakness of oral tradition as a historical source is that it:', o: ['Is always written down', 'Covers only European history', 'Cannot be verified at all', 'May be distorted in the course of transmission'], a: 3 },
  { s: 'History', q: 'The method of determining the age of organic archaeological materials by measuring carbon-14 is called:', o: ['Stratigraphy', 'Palaeography', 'Typology', 'Radio-carbon dating'], a: 3 },
  { s: 'History', q: 'The British Parliament passed the law abolishing the Atlantic slave trade in:', o: ['1807', '1787', '1833', '1865'], a: 0 },
  { s: 'History', q: 'The first European nation to transport enslaved Africans across the Atlantic was:', o: ['Britain', 'Spain', 'Portugal', 'France'], a: 2 },
  { s: 'History', q: 'The Portuguese slave-trading fort of Sao Jorge da Mina was built in present-day:', o: ['Senegal', 'Ghana', 'Togo', 'Nigeria'], a: 1 },
  { s: 'History', q: 'The Asiento contract, which gave Britain the right to supply slaves to Spanish colonies, was granted in:', o: ['1600', '1713', '1807', '1885'], a: 2 },
  { s: 'History', q: 'The inhumane ocean crossing from Africa to the Americas, on which many captives died, is known as:', o: ['The Triangular Trade', 'The Middle Passage', 'The Scramble', 'The Passage of Lagos'], a: 1 },
  { s: 'History', q: 'The triangular trade linked Europe, Africa and:', o: ['Europe', 'Africa', 'The Americas', 'Asia'], a: 2 },
  { s: 'History', q: 'The author of The Interesting Narrative of the Life of Olaudah Equiano, used by abolitionists, was:', o: ['Thomas Clarkson', 'William Wilberforce', 'Robert Bristow', 'Olaudah Equiano'], a: 3 },
  { s: 'History', q: 'The Clapham Sect of prominent British abolitionists counted among its leaders:', o: ['Cecil Rhodes', 'Lord Lugard', 'William Wilberforce', 'David Livingstone'], a: 2 },
  { s: 'History', q: 'The West Africa Squadron, established by the British after 1807, was used to:', o: ['Map the River Niger', 'Build railways', 'Patrol and intercept slave ships', 'Collect customs'], a: 2 },
  { s: 'History', q: 'The British Parliament passed the Emancipation Act abolishing slavery in its colonies in:', o: ['1807', '1833', '1865', '1900'], a: 1 },
  { s: 'History', q: 'Which of these rivers served as a major route for the export of enslaved people from the Bight of Benin?', o: ['The Nile', 'The Congo', 'The Zambezi', 'The Niger'], a: 3 },
  { s: 'History', q: 'The British bombardment of Lagos in 1851 was justified by the British as an effort to:', o: ['Suppress the slave trade', 'Build a railway', 'Found a university', 'Hunt for gold'], a: 0 },
  { s: 'History', q: 'Lagos was formally annexed by Britain in:', o: ['1851', '1900', '1861', '1885'], a: 2 },
  { s: 'History', q: 'The British chartered company that acquired trading rights in the lower Niger region was the:', o: ['Royal African Company', 'East India Company', 'Royal Niger Company', 'British South Africa Company'], a: 2 },
  { s: 'History', q: 'The Royal Niger Company was originally promoted by:', o: ['George Taubman Goldie', 'Cecil Rhodes', 'Paul Kruger', 'Lord Lugard'], a: 0 },
  { s: 'History', q: 'The West Africa Conference that laid down the rules for the partition of Africa met in:', o: ['1815', '1869', '1884-1885', '1914'], a: 2 },
  { s: 'History', q: 'The main significance of the Berlin Conference of 1884-1885 is that it:', o: ['Ended the Atlantic slave trade', 'Created the OAU', 'Granted Nigeria independence', 'Laid down the rules for the European partition of Africa'], a: 3 },
  { s: 'History', q: 'The Berlin Conference of 1884-1885 was attended only by:', o: ['African and Asian leaders', 'The Pope and clergy', 'European powers and the United States', 'League of Nations members'], a: 2 },
  { s: 'History', q: 'The European monarch who personally owned the Congo Free State was:', o: ['Leopold II', 'Kaiser Wilhelm II', 'Cecil Rhodes', 'Paul Kruger'], a: 0 },
  { s: 'History', q: 'Cecil Rhodes is most closely associated with the colonisation of:', o: ['West Africa', 'North Africa', 'Southern Africa', 'The Sahara'], a: 2 },
  { s: 'History', q: 'The Maji Maji Rebellion of 1905-1907 was directed against:', o: ['French rule in Algeria', 'British rule in Nigeria', 'Italian rule in Libya', 'German rule in Tanganyika'], a: 3 },
  { s: 'History', q: 'The rebellion of the Herero and Nama against German rule took place in:', o: ['German East Africa', 'French Senegal', 'British Kenya', 'German South West Africa'], a: 3 },
  { s: 'History', q: 'Samori Toure, who resisted French expansion in West Africa, founded the:', o: ['Ashanti Empire', 'Wassoulou Empire', 'Sokoto Caliphate', 'Kingdom of Dahomey'], a: 1 },
  { s: 'History', q: 'Samori Toure was finally captured by the French in:', o: ['1898', '1885', '1905', '1914'], a: 0 },
  { s: 'History', q: 'The Anglo-Zulu War, which ended with the defeat of the Zulu Kingdom, was fought in:', o: ['1866', '1906', '1879', '1885'], a: 2 },
  { s: 'History', q: 'The Ethiopian army under Menelik II defeated the Italians at the Battle of Adwa in:', o: ['1896', '1885', '1935', '1960'], a: 0 },
  { s: 'History', q: 'The Yaa Asantewaa War of 1900 was fought by the people of:', o: ['The Zulu', 'The Fante', 'The Asante', 'The Nupe'], a: 2 },
  { s: 'History', q: 'Prempeh I, the Asantehene deported by the British, was exiled first to:', o: ['Seychelles', 'Mauritius', 'Sierra Leone', 'Liberia'], a: 0 },
  { s: 'History', q: 'The Hut Tax War of 1898 in Sierra Leone was led by:', o: ['Bai Bureh', 'Samori Toure', 'Kwame Nkrumah', 'Lord Lugard'], a: 0 },
  { s: 'History', q: 'The Morant Bay Rebellion of 1865, led by Paul Bogle, took place in:', o: ['Gold Coast', 'Nigeria', 'Kenya', 'Jamaica'], a: 3 },
  { s: 'History', q: 'The Fante Confederation, which attempted to unite the Fante states against Asante and European encroachment, was formed in the:', o: ['1780s', '1860s', '1900s', '1940s'], a: 1 },
  { s: 'History', q: 'The West African republic founded in 1847 by freed American slaves was:', o: ['Liberia', 'Ethiopia', 'Egypt', 'Algeria'], a: 0 },
  { s: 'History', q: 'Liberia was settled by freed slaves sponsored by the:', o: ['American Colonization Society', 'Royal Niger Company', 'Portuguese crown', 'Dutch East India Company'], a: 0 },
  { s: 'History', q: 'Sierra Leone\'s Freetown was originally settled by:', o: ['Dutch traders', 'Liberated Africans and Black Loyalists', 'French missionaries', 'Arab merchants'], a: 1 },
  { s: 'History', q: 'The series of Anglo-Asante wars was fought over control of:', o: ['The Gold Coast hinterland', 'The Niger Delta', 'Lake Chad', 'The Senegal River'], a: 0 },
  { s: 'History', q: 'The British punitive expedition against Benin in 1897 led to the exile of:', o: ['Oba Ovonramwen', 'Alaafin Atanda', 'The Emir of Katsina', 'The Obi of Onitsha'], a: 0 },
  { s: 'History', q: 'One direct consequence of the 1897 Benin Expedition was the:', o: ['Abolition of the Oba stool', 'Founding of the University of Lagos', 'Creation of Biafra', 'Removal of Benin bronzes to Europe'], a: 3 },
  { s: 'History', q: 'The Sokoto Caliphate finally fell to the British in 1903 when:', o: ['The Berlin Conference opened', 'The Lagos bombardment took place', 'Oba Ovonramwen surrendered', 'Sultan Attahiru I was defeated at Burmi'], a: 3 },
  { s: 'History', q: 'Lord Lugard\'s policy of indirect rule was carried out through:', o: ['Native authorities and traditional rulers', 'Elected provincial councils', 'Military district commandants', 'Missionary assemblies'], a: 0 },
  { s: 'History', q: 'Indirect rule worked most successfully in Nigeria\'s:', o: ['Northern Region', 'Eastern Region', 'Lagos Colony', 'Calabar Province'], a: 0 },
  { s: 'History', q: 'Indirect rule met stiff resistance in Eastern Nigeria mainly because of:', o: ['The strength of the emirate system', 'The wealth of the chiefs', 'The imposition of warrant chiefs lacking local legitimacy', 'The abolition of taxation'], a: 2 },
  { s: 'History', q: 'The warrant chief system imposed by the British was applied mainly in:', o: ['Hausaland', 'Igbo land', 'Yorubaland', 'The Niger Delta'], a: 1 },
  { s: 'History', q: 'The 1929 Women\'s War was a protest by Igbo women against:', o: ['The abolition of slavery', 'Taxation of women and the warrant chiefs', 'Railway construction', 'Missionary schools'], a: 1 },
  { s: 'History', q: 'The general strike of 1945 in Nigeria was led by:', o: ['Herbert Macaulay', 'Michael Imoudu', 'Nnamdi Azikiwe', 'Tafawa Balewa'], a: 1 },
  { s: 'History', q: 'The Iva Valley massacre of coal miners in 1949 took place in:', o: ['Kano', 'Calabar', 'Enugu', 'Jos'], a: 2 },
  { s: 'History', q: 'The Nigerian National Democratic Party (NNDP), founded in 1923, was led by:', o: ['Herbert Macaulay', 'Nnamdi Azikiwe', 'William Aboderin', 'Ernest Ikoli'], a: 0 },
  { s: 'History', q: 'The Clifford Constitution of 1922 introduced:', o: ['Indirect rule', 'The elective principle', 'Regionalism', 'A senate'], a: 1 },
  { s: 'History', q: 'Under the Clifford Constitution, elected members were sent to the:', o: ['Northern House of Chiefs', 'Supreme Court', 'Legislative Council', 'Emirate Council'], a: 2 },
  { s: 'History', q: 'The constitution that divided Nigeria into three regions was the:', o: ['1946', '1914', '1922', '1957'], a: 0 },
  { s: 'History', q: 'The Richards Constitution divided Nigeria into the:', o: ['Lagos, Calabar and Sokoto regions', 'Eastern, Western and Northern Regions', 'Two regions', 'Niger and Benue provinces'], a: 1 },
  { s: 'History', q: 'The Macpherson Constitution of 1951 provided for:', o: ['A military government', 'The office of Prime Minister', 'Elections to the House of Representatives', 'Abolition of the regions'], a: 2 },
  { s: 'History', q: 'The Macpherson Constitution was criticised mainly because it:', o: ['Abolished elections', 'Created too many regions', 'Gave voting rights to Europeans only', 'Made the centre too strong and lacked popular consultation'], a: 3 },
  { s: 'History', q: 'The Lyttleton Constitution of 1957 introduced:', o: ['A presidential system', 'Ministerial government at the centre', 'Military rule', 'The office of Premier of Lagos'], a: 1 },
  { s: 'History', q: 'The Independence Constitution of 1960 established Nigeria as a:', o: ['Unitary state', 'Colony of Britain', 'Federation within the Commonwealth', 'Absolute monarchy'], a: 2 },
  { s: 'History', q: 'The Republican Constitution of 1963 made Nigeria a:', o: ['Constitutional monarchy', 'Sovereign republic', 'Unitary state', 'Colonial dependency'], a: 1 },
  { s: 'History', q: 'The first President of Nigeria was:', o: ['Nnamdi Azikiwe', 'Tafawa Balewa', 'Herbert Macaulay', 'Ahmadu Bello'], a: 0 },
  { s: 'History', q: 'Nigeria gained independence from Britain on:', o: ['1 October 1960', '1 October 1963', '27 May 1967', '15 January 1966'], a: 0 },
  { s: 'History', q: 'The National Council of Nigeria and the Cameroons (NCNC) was founded in 1944 by:', o: ['Awolowo and Akintola', 'Ahmadu Bello and Balewa', 'Herbert Macaulay and Nnamdi Azikiwe', 'Ikoli and Akinsanya'], a: 2 },
  { s: 'History', q: 'Nnamdi Azikiwe\'s newspaper, which became a powerful voice of nationalism, was the:', o: ['Nigerian Tribune', 'West African Pilot', 'Daily Times', 'Morning Star'], a: 1 },
  { s: 'History', q: 'The Nigerian Youth Movement (NYM), founded in 1938, counted among its founders:', o: ['Awolowo and Akintola', 'Macaulay and Balewa', 'Aminu Kano and Buhari', 'Ernest Ikoli and Nnamdi Azikiwe'], a: 3 },
  { s: 'History', q: 'The Action Group, the dominant party of the Western Region, was founded in 1951 by:', o: ['Ahmadu Bello', 'Obafemi Awolowo', 'Nnamdi Azikiwe', 'Aminu Kano'], a: 1 },
  { s: 'History', q: 'The first free primary education scheme in Nigeria was introduced in the Western Region in 1955 under:', o: ['Obafemi Awolowo', 'Nnamdi Azikiwe', 'Tafawa Balewa', 'John Macpherson'], a: 0 },
  { s: 'History', q: 'The Northern People\'s Congress (NPC) was dominated by:', o: ['Awolowo and Akintola', 'Azikiwe and Akinsanya', 'Ahmadu Bello and Tafawa Balewa', 'Aminu Kano and Buhari'], a: 2 },
  { s: 'History', q: 'The Northern Elements Progressive Union (NEPU), the first political party of the North, was led by:', o: ['Ahmadu Bello', 'Tafawa Balewa', 'Yusuf Maitama Sule', 'Aminu Kano'], a: 3 },
  { s: 'History', q: 'The main ideological thrust of NEPU was to:', o: ['Restore the Sokoto Caliphate', 'Oppose the feudal emirate establishment', 'Ban Islam', 'Secede from Nigeria'], a: 1 },
  { s: 'History', q: 'The 1953 motion demanding self-government for Nigeria by 1956 was moved by:', o: ['Nnamdi Azikiwe', 'Obafemi Awolowo', 'Anthony Enahoro', 'Tafawa Balewa'], a: 2 },
  { s: 'History', q: 'The Kano riots of 1953 reflected Northern suspicion of:', o: ['British taxation', 'Southern politicians\' push for early self-government', 'Missionary schools', 'The Oba of Benin'], a: 1 },
  { s: 'History', q: 'The constitutional conference that produced Nigeria\'s 1957 constitution was held in:', o: ['London', 'Accra', 'Lagos', 'Aburi'], a: 0 },
  { s: 'History', q: 'A major weakness of Nigerian nationalism before independence was:', o: ['Lack of educated elites', 'Absence of political parties', 'A total ban on the press', 'Strong regional and ethnic loyalties'], a: 3 },
  { s: 'History', q: 'The 1962 crisis in the Western Region was caused mainly by:', o: ['A military coup', 'A currency reform', 'A split in the Action Group between Awolowo and Akintola', 'A census dispute'], a: 2 },
  { s: 'History', q: 'Chief Obafemi Awolowo was convicted of treasonable felony in:', o: ['1963', '1953', '1966', '1979'], a: 0 },
  { s: 'History', q: 'The 1964 federal election in Nigeria was widely criticised for:', o: ['Lack of candidates', 'A total ban on parties', 'A low population count', 'Widespread malpractice and manipulation'], a: 3 },
  { s: 'History', q: 'The first military coup in Nigeria took place on:', o: ['15 January 1966', '19 July 1966', '30 May 1967', '31 December 1983'], a: 0 },
  { s: 'History', q: 'The military head of state who took over after the January 1966 coup was:', o: ['Yakubu Gowon', 'Nnamdi Azikiwe', 'Johnson Aguiyi-Ironsi', 'Tafawa Balewa'], a: 2 },
  { s: 'History', q: 'The counter-coup of July 1966 installed as head of state:', o: ['Emeka Ojukwu', 'Yakubu Gowon', 'Olusegun Obasanjo', 'Ibrahim Babangida'], a: 1 },
  { s: 'History', q: 'The head of state killed in the counter-coup of July 1966 was:', o: ['Johnson Aguiyi-Ironsi', 'Tafawa Balewa', 'The Sardauna of Sokoto', 'Obafemi Awolowo'], a: 0 },
  { s: 'History', q: 'The twelve states into which Nigeria was reorganised just before the civil war were created in:', o: ['1966', '1970', '1967', '1976'], a: 2 },
  { s: 'History', q: 'The Eastern Region was proclaimed the Republic of Biafra on:', o: ['1 January 1966', '30 May 1967', '6 July 1967', '12 January 1970'], a: 1 },
  { s: 'History', q: 'The leader of the breakaway Republic of Biafra was:', o: ['Yakubu Gowon', 'Olusegun Obasanjo', 'Ibrahim Babangida', 'Chukwuemeka Odumegwu Ojukwu'], a: 3 },
  { s: 'History', q: 'The Aburi meeting of January 1967 between Gowon and Ojukwu was held in:', o: ['Ghana', 'Togo', 'Ethiopia', 'Ivory Coast'], a: 0 },
  { s: 'History', q: 'The Nigerian Civil War (Biafran War) began in:', o: ['January 1966', 'May 1967', 'July 1967', 'October 1960'], a: 2 },
  { s: 'History', q: 'The Nigerian Civil War came to an end in:', o: ['December 1969', 'January 1970', 'July 1967', 'November 1968'], a: 1 },
  { s: 'History', q: 'The mass starvation of Biafran civilians was largely caused by the:', o: ['Open-door policy', 'Currency exchange', 'Naval blockade of Biafra', 'Evacuation of schools'], a: 2 },
  { s: 'History', q: 'After the civil war, the Gowon administration adopted the slogan:', o: ['Unity in diversity', 'Work and honour', 'Freedom first', 'No victor, no vanquished'], a: 3 },
  { s: 'History', q: 'The Organisation of African Unity (OAU) was founded in:', o: ['1945', '1975', '1963', '1980'], a: 2 },
  { s: 'History', q: 'The OAU was founded at a conference held in:', o: ['Accra', 'Addis Ababa', 'Cairo', 'Lagos'], a: 1 },
  { s: 'History', q: 'The OAU policy of upholding the boundaries inherited at independence is known as:', o: ['Non-alignment', 'Socialism', 'Pan-Arabism', 'Respect for inherited colonial boundaries'], a: 3 },
  { s: 'History', q: 'During the Nigerian Civil War, the role of the OAU was to:', o: ['Recognise Biafra', 'Mediate while accepting Nigeria\'s unity', 'Send ECOMOG troops', 'Expel Nigeria'], a: 1 },
  { s: 'History', q: 'The headquarters of the OAU (now African Union) is in:', o: ['Nairobi', 'Accra', 'Addis Ababa', 'Abuja'], a: 2 },
  { s: 'History', q: 'The Economic Community of West African States (ECOWAS) was established by the Treaty of Lagos in:', o: ['1975', '1963', '1980', '1990'], a: 0 },
  { s: 'History', q: 'Nigeria\'s Second Republic was inaugurated in:', o: ['1979', '1963', '1983', '1999'], a: 0 },
  { s: 'History', q: 'The 1979 Constitution of Nigeria introduced:', o: ['A parliamentary system', 'A presidential system', 'Military rule', 'A confederal system'], a: 1 },
  { s: 'History', q: 'The 1979 Constitution required a presidential candidate to score at least:', o: ['50% of the votes in one state', '10% of the votes nationally', 'Unanimous support of all states', '25% of the votes in two-thirds of the states'], a: 3 },
  { s: 'History', q: 'Shehu Shagari, winner of the 1979 presidential election, was the candidate of the:', o: ['UPN', 'NPN', 'NPP', 'GNPP'], a: 1 },
  { s: 'History', q: 'President Shehu Shagari was overthrown in a military coup on:', o: ['15 January 1966', '27 May 1967', '19 August 1985', '31 December 1983'], a: 3 },
  { s: 'History', q: 'The military regime that ruled Nigeria from 1983 to 1985 was headed by:', o: ['Ibrahim Babangida', 'Sani Abacha', 'Muhammadu Buhari', 'Abdulsalami Abubakar'], a: 2 },
  { s: 'History', q: 'The military head of state who seized power in August 1985 and later introduced the Structural Adjustment Programme was:', o: ['Muhammadu Buhari', 'Sani Abacha', 'Ibrahim Babangida', 'Abdulsalami Abubakar'], a: 2 },
  { s: 'History', q: 'The Structural Adjustment Programme (SAP) introduced in 1986 was based largely on advice from:', o: ['The African Union', 'ECOWAS', 'The IMF and World Bank', 'The United Nations General Assembly'], a: 2 },
  { s: 'History', q: 'The presidential election of 12 June 1993 is generally believed to have been won by:', o: ['Bashir Tofa', 'Shehu Shagari', 'Umaru Musa Yar\'Adua', 'Moshood Kashimawo Abiola'], a: 3 },
  { s: 'History', q: 'The presidential election of 12 June 1993 was annulled by the government of:', o: ['Ibrahim Babangida', 'Sani Abacha', 'Muhammadu Buhari', 'Ernest Shonekan'], a: 0 },
  { s: 'History', q: 'The Interim National Government that succeeded Babangida in August 1993 was headed by:', o: ['M.K.O. Abiola', 'Sani Abacha', 'Ernest Shonekan', 'Muhammadu Buhari'], a: 2 },
  { s: 'History', q: 'The military regime that took power in November 1993 was led by:', o: ['Ibrahim Babangida', 'Ernest Shonekan', 'Abdulsalami Abubakar', 'Sani Abacha'], a: 3 },
  { s: 'History', q: 'General Sani Abacha died in office in:', o: ['June 1998', 'June 1993', 'July 1999', 'December 1983'], a: 0 },
  { s: 'History', q: 'Nigeria\'s Fourth Republic was ushered in by a constitution promulgated in:', o: ['1995', '1989', '2003', '1999'], a: 3 },
  { s: 'History', q: 'The first president of Nigeria\'s Fourth Republic was:', o: ['Umaru Musa Yar\'Adua', 'Olusegun Obasanjo', 'Goodluck Jonathan', 'Muhammadu Buhari'], a: 1 },
  { s: 'History', q: 'The Gold Coast gained independence as Ghana on:', o: ['1 March 1957', '6 March 1957', '1 October 1960', '6 March 1960'], a: 1 },
  { s: 'History', q: 'The first President of Ghana after it became a republic in 1960 was:', o: ['Edward Akufo-Addo', 'Jerry Rawlings', 'Kwame Nkrumah', 'J.B. Danquah'], a: 2 },
  { s: 'History', q: 'The Convention People\'s Party (CPP) of the Gold Coast was founded in 1949 by:', o: ['Kwame Nkrumah', 'J.B. Danquah', 'Emmanuel Obetsebi-Lamptey', 'William Ofori-Atta'], a: 0 },
  { s: 'History', q: 'The Positive Action campaign launched by Nkrumah in 1950 involved:', o: ['Armed rebellion', 'A military coup', 'Boycotts, strikes and civil disobedience', 'A court petition'], a: 2 },
  { s: 'History', q: 'The Gold Coast leaders detained after the 1948 Accra riots, later celebrated as the Big Six, were led by:', o: ['Patrice Lumumba', 'Kwame Nkrumah', 'Leopold Senghor', 'Jomo Kenyatta'], a: 1 },
  { s: 'History', q: 'The French colony that gained independence in 1958 after voting against remaining in the French Community was:', o: ['Senegal', 'Mali', 'Guinea', 'Ivory Coast'], a: 2 },
  { s: 'History', q: 'The leader of Guinea at independence in 1958 was:', o: ['Leopold Sedar Senghor', 'Ahmed Sekou Toure', 'Modibo Keita', 'Houphouet-Boigny'], a: 1 },
  { s: 'History', q: 'Senegal\'s first president, also a celebrated poet of the Negritude movement, was:', o: ['Aime Cesar', 'Sekou Toure', 'Leopold Sedar Senghor', 'Houphouet-Boigny'], a: 2 },
  { s: 'History', q: 'The Negritude movement, launched in 1930s Paris, was founded by Senghor, Cesar and:', o: ['George Padmore', 'W.E.B. Du Bois', 'Marcus Garvey', 'Leon-Gontran Damas'], a: 3 },
  { s: 'History', q: 'The first Pan-African Conference of 1900 was held in:', o: ['London', 'Paris', 'Accra', 'New York'], a: 0 },
  { s: 'History', q: 'The Fifth Pan-African Congress held in Manchester in 1945 was important because it:', o: ['Created the OAU', 'Founded the United Nations', 'Demanded immediate self-government', 'Ended the slave trade'], a: 2 },
  { s: 'History', q: 'The movement founded by Marcus Garvey in 1914 to promote Black pride and solidarity was the:', o: ['UNIA', 'ANC', 'OAU', 'League of Nations'], a: 0 },
  { s: 'History', q: 'The organiser of the 1945 Pan-African Congress who later served as an adviser to Nkrumah was:', o: ['W.E.B. Du Bois', 'George Padmore', 'Marcus Garvey', 'Edward Blyden'], a: 1 },
  { s: 'History', q: 'W.E.B. Du Bois was instrumental in organising the Pan-African Congresses of:', o: ['1919, 1921, 1923 and 1927', '1900 and 1945', '1945 and 1963', '1885 and 1914'], a: 0 },
  { s: 'History', q: 'The Indian nationalist leader who championed non-violent civil disobedience was:', o: ['Subhas Chandra Bose', 'Mohandas Karamchand Gandhi', 'Lord Mountbatten', 'Lord Wavell'], a: 1 },
  { s: 'History', q: 'British India was partitioned into India and Pakistan in:', o: ['1935', '1947', '1950', '1945'], a: 1 },
  { s: 'History', q: 'The Second World War began with:', o: ['The invasion of Poland by Germany', 'The Russian Revolution', 'The Wall Street crash', 'The assassination of Franz Ferdinand'], a: 0 },
  { s: 'History', q: 'The event that triggered the First World War was the assassination of:', o: ['Adolf Hitler', 'Vladimir Lenin', 'Archduke Franz Ferdinand', 'Napoleon Bonaparte'], a: 2 },
  { s: 'History', q: 'The treaty that formally ended the First World War and imposed heavy penalties on Germany was the:', o: ['Treaty of Vienna', 'Treaty of Versailles', 'Treaty of Tordesillas', 'Treaty of Berlin'], a: 1 },
  { s: 'History', q: 'The international organisation formed after the First World War to preserve world peace was the:', o: ['The League of Nations', 'The United Nations', 'NATO', 'The OAU'], a: 0 },
  { s: 'History', q: 'The United Nations was founded in:', o: ['1920', '1947', '1955', '1945'], a: 3 },
  { s: 'History', q: 'The Nigerian historian Kenneth Onwuka Dike is best known for his scholarly work:', o: ['The Kano Chronicle', 'History of the Yorubas', 'Trade and Politics in the Niger Delta', 'Usul Fikr'], a: 2 },
  { s: 'History', q: 'The Kano Chronicle and the Chronicle of Borgu are examples of:', o: ['Oral sources', 'Archaeological evidence', 'Indigenous written sources', 'Foreign newspaper reports'], a: 2 },
  { s: 'History', q: 'The Tarikh al-Sudan and Tarikh al-Fattash are valuable written sources for the history of:', o: ['The Igbo hinterland', 'The Yoruba forest cities', 'The Western Sudan and Timbuktu', 'The Niger Delta kingdoms'], a: 2 },
  { s: 'History', q: 'The book written by Ibn Khaldun, regarded as a landmark in the scientific study of history, is the:', o: ['Kano Chronicle', 'Muqaddimah', 'Interesting Narrative', 'Social Contract'], a: 1 },
  { s: 'History', q: 'Herodotus is often called the Father of History because he:', o: ['Invented the printing press', 'Systematically collected and recorded accounts of the peoples he studied', 'Founded the first university', 'Developed carbon dating'], a: 1 },
  { s: 'History', q: 'The study of ancient coins as historical evidence is known as:', o: ['Stratigraphy', 'Palaeography', 'Typology', 'Numismatics'], a: 3 },
  { s: 'History', q: 'The examination of the layers of earth during an excavation to establish the sequence of occupation is called:', o: ['Numismatics', 'Oral tradition', 'Cartography', 'Stratigraphy'], a: 3 },
  { s: 'History', q: 'A praise-poem (oriki) that recounts the achievements of a king is a form of:', o: ['Numismatic evidence', 'Oral tradition', 'Archaeological evidence', 'Written charter'], a: 1 },
  { s: 'History', q: 'The observation that a praise singer exaggerated his king\'s exploits in order to gain rewards illustrates which weakness of oral sources?', o: ['Forgery of documents', 'Bias', 'Translation error', 'Printing error'], a: 1 }
]);
