/* =========================================================
   JAMB Study Tracker — Physics practice questions (180)
   Loaded after js/questions.js; appends to window.QUESTION_BANK
   { s: subject, q: question, o: [four options], a: correct index }
   ========================================================= */
window.QUESTION_BANK = (window.QUESTION_BANK || []).concat([
  /* --- Measurement, units, dimensions --- */
  { s: 'Physics', q: 'The SI unit of force is the:', o: ['Joule', 'Newton', 'Watt', 'Pascal'], a: 1 },
  { s: 'Physics', q: 'A body of mass 5 kg accelerates at 2 m/s^2. The force applied is:', o: ['2.5 N', '7 N', '10 N', '20 N'], a: 2 },
  { s: 'Physics', q: 'Which of the following is a base quantity in the SI system?', o: ['Force', 'Velocity', 'Length', 'Energy'], a: 2 },
  { s: 'Physics', q: 'The dimension of work is:', o: ['ML^2T^-2', 'MLT^-2', 'ML^2T^-1', 'MLT^-3'], a: 0 },
  { s: 'Physics', q: 'The SI unit of pressure is the:', o: ['Joule', 'N/m', 'J/s', 'N/m^2'], a: 3 },
  { s: 'Physics', q: 'Correct 4.5678 to three significant figures:', o: ['4.56', '4.57', '4.58', '4.568'], a: 1 },
  { s: 'Physics', q: 'Find the circumference of a circle of radius 7 cm. (Take pi = 22/7)', o: ['22 cm', '28 cm', '44 cm', '154 cm'], a: 2 },
  { s: 'Physics', q: 'A vernier caliper has 10 vernier scale divisions spanning 9 main scale divisions of 1 mm each. Its least count is:', o: ['0.01 mm', '1 mm', '0.5 mm', '0.1 mm'], a: 3 },
  { s: 'Physics', q: 'The dimension of velocity is:', o: ['LT^-1', 'LT^-2', 'L^2T^-1', 'LT^-3'], a: 0 },
  { s: 'Physics', q: 'Which of the following is a scalar quantity?', o: ['Momentum', 'Speed', 'Force', 'Acceleration'], a: 1 },
  { s: 'Physics', q: 'The derived SI unit of frequency is the:', o: ['Watt', 'Pascal', 'Tesla', 'Hertz'], a: 3 },
  { s: 'Physics', q: 'One horsepower is equivalent to:', o: ['746 W', '750 W', '1000 W', '550 W'], a: 0 },
  { s: 'Physics', q: 'The number of significant figures in 0.00450 is:', o: ['5', '4', '3', '2'], a: 2 },
  { s: 'Physics', q: 'A speed of 72 km/h is equal to:', o: ['2 m/s', '20 m/s', '200 m/s', '2.7 m/s'], a: 1 },
  /* --- Motion --- */
  { s: 'Physics', q: 'A car starts from rest and reaches a speed of 20 m/s in 5 s. Its acceleration is:', o: ['0.25 m/s^2', '4 m/s^2', '100 m/s^2', '10 m/s^2'], a: 1 },
  { s: 'Physics', q: 'A stone falls freely from rest. The distance it covers in 2 s (take g = 10 m/s^2) is:', o: ['10 m', '40 m', '5 m', '20 m'], a: 3 },
  { s: 'Physics', q: 'A body falls freely from rest. Its velocity after 3 s (take g = 10 m/s^2) is:', o: ['3 m/s', '30 m/s', '45 m/s', '15 m/s'], a: 1 },
  { s: 'Physics', q: 'A runner covers 100 m in 10 s and another 100 m in 20 s. The average speed for the whole journey is:', o: ['15 m/s', '5 m/s', '6.7 m/s', '10 m/s'], a: 2 },
  { s: 'Physics', q: 'A projectile is fired at 20 m/s at an angle of 30 degrees to the horizontal. Its range on level ground (take g = 10 m/s^2) is:', o: ['20 m', '34.6 m', '40 m', '17.3 m'], a: 1 },
  { s: 'Physics', q: 'A ball is projected at 30 m/s at 30 degrees to the horizontal. Its time of flight (take g = 10 m/s^2) is:', o: ['1.5 s', '6 s', '3 s', '4.5 s'], a: 2 },
  { s: 'Physics', q: 'Which of the following is a vector quantity?', o: ['Displacement', 'Speed', 'Mass', 'Temperature'], a: 0 },
  { s: 'Physics', q: 'A stone is thrown vertically upward at 30 m/s. The maximum height reached (take g = 10 m/s^2) is:', o: ['90 m', '15 m', '30 m', '45 m'], a: 3 },
  { s: 'Physics', q: 'The slope of a distance-time graph represents:', o: ['Momentum', 'Acceleration', 'Displacement', 'Speed'], a: 3 },
  { s: 'Physics', q: 'The area under a velocity-time graph represents:', o: ['Momentum', 'Acceleration', 'Distance', 'Displacement'], a: 3 },
  { s: 'Physics', q: 'A body has an initial velocity of 10 m/s and decelerates uniformly at 2 m/s^2. Its velocity after 5 s is:', o: ['20 m/s', '5 m/s', '0 m/s', '2 m/s'], a: 2 },
  { s: 'Physics', q: 'A body starts from rest and accelerates at 2 m/s^2 for 4 s. The distance covered is:', o: ['36 m', '16 m', '40 m', '20 m'], a: 1 },
  /* --- Forces --- */
  { s: 'Physics', q: 'A body of mass 5 kg rests on a rough horizontal surface. If the coefficient of friction is 0.4 and g = 10 m/s^2, the minimum force needed to just move it is:', o: ['50 N', '25 N', '10 N', '20 N'], a: 3 },
  { s: 'Physics', q: 'The resultant of two perpendicular forces of 3 N and 4 N is:', o: ['5 N', '7 N', '1.2 N', '25 N'], a: 0 },
  { s: 'Physics', q: 'A force of 10 N is applied at a distance of 0.5 m from a pivot. The moment of the force about the pivot is:', o: ['2.5 Nm', '5 Nm', '15 Nm', '20 Nm'], a: 1 },
  { s: 'Physics', q: 'The tendency of a body to remain at rest or to continue in uniform motion unless acted on by an external force is called:', o: ['Momentum', 'Impulse', 'Inertia', 'Elasticity'], a: 2 },
  { s: 'Physics', q: 'The impulse of a force has the unit:', o: ['N/m^2', 'J/s', 'N s', 'Joule'], a: 2 },
  { s: 'Physics', q: 'The momentum of a body of mass 4 kg moving at 6 m/s is:', o: ['24 kg m/s', '6 kg m/s', '10 kg m/s', '1.5 kg m/s'], a: 0 },
  { s: 'Physics', q: 'A car of mass 1500 kg moving at 20 m/s is brought to rest in 10 s. The magnitude of the average braking force is:', o: ['300 N', '15000 N', '3000 N', '1500 N'], a: 2 },
  { s: 'Physics', q: 'A ball of mass 0.5 kg moving at 10 m/s is brought to rest in 0.25 s. The average force acting on it is:', o: ['0.5 N', '20 N', '0.125 N', '5 N'], a: 1 },
  /* --- Work, energy and power --- */
  { s: 'Physics', q: 'The work done by a force of 25 N moving through a distance of 4 m is:', o: ['4 J', '25 J', '29 J', '100 J'], a: 3 },
  { s: 'Physics', q: 'The kinetic energy of a body of mass 2 kg moving at 3 m/s is:', o: ['9 J', '18 J', '4.5 J', '3 J'], a: 0 },
  { s: 'Physics', q: 'The gravitational potential energy of a body of mass 10 kg at a height of 5 m (take g = 10 m/s^2) is:', o: ['50 J', '5000 J', '500 J', '25 J'], a: 2 },
  { s: 'Physics', q: 'An engine lifts a load of 500 N through a height of 3 m in 10 s. The power developed is:', o: ['1.5 W', '15 W', '150 W', '1500 W'], a: 2 },
  { s: 'Physics', q: 'A machine uses 500 J of energy and does 400 J of useful work. Its efficiency is:', o: ['40%', '50%', '100%', '80%'], a: 3 },
  { s: 'Physics', q: 'A spring of force constant 200 N/m is stretched by 0.15 m. The energy stored in it is:', o: ['2.25 J', '30 J', '3 J', '0.75 J'], a: 0 },
  { s: 'Physics', q: 'The SI unit of power is the:', o: ['Joule', 'Newton', 'Watt', 'Pascal'], a: 2 },
  { s: 'Physics', q: 'A machine has a velocity ratio of 5 and an efficiency of 80%. Its mechanical advantage is:', o: ['5', '2', '4', '1.25'], a: 2 },
  { s: 'Physics', q: 'Which of the following forces is a conservative force?', o: ['Friction', 'Gravity', 'Air resistance', 'Viscous drag'], a: 1 },
  { s: 'Physics', q: 'In an electric lamp, electrical energy is converted mainly into:', o: ['Chemical energy', 'Mechanical energy', 'Sound energy', 'Heat and light energy'], a: 3 },
  { s: 'Physics', q: 'A force of 10 N acts perpendicular to the direction of a displacement of 2 m. The work done by the force is:', o: ['0 J', '20 J', '5 J', '12 J'], a: 0 },
  /* --- Heat and temperature --- */
  { s: 'Physics', q: 'The SI unit of temperature is the:', o: ['Joule', 'Celsius', 'Kelvin', 'Fahrenheit'], a: 2 },
  { s: 'Physics', q: 'A temperature of 27 degrees C expressed in kelvin is:', o: ['200 K', '327 K', '27 K', '300 K'], a: 3 },
  { s: 'Physics', q: 'A temperature of 300 K expressed in degrees Celsius is:', o: ['27 degrees C', '100 degrees C', '0 degrees C', '300 degrees C'], a: 0 },
  { s: 'Physics', q: 'The quantity of heat needed to raise the temperature of 2 kg of water through 10 degrees C (specific heat capacity 4200 J/kg K) is:', o: ['8400 J', '4200 J', '84000 J', '21000 J'], a: 2 },
  { s: 'Physics', q: 'The energy required to melt 2 kg of ice completely (specific latent heat of fusion 3.36 x 10^5 J/kg) is:', o: ['6.72 x 10^5 J', '3.36 x 10^5 J', '1.68 x 10^5 J', '6.72 x 10^4 J'], a: 0 },
  { s: 'Physics', q: 'The temperature of a body is a measure of the:', o: ['Total energy of its molecules', 'Average kinetic energy of its molecules', 'Pressure of its molecules', 'Volume of its molecules'], a: 1 },
  { s: 'Physics', q: 'Which of the following expands the most when heated through the same temperature change?', o: ['Solids', 'Liquids', 'Gases', 'All three expand by the same amount'], a: 2 },
  { s: 'Physics', q: 'A bimetallic strip bends when heated because the two metals have different:', o: ['Densities', 'Melting points', 'Coefficients of linear expansion', 'Specific heat capacities'], a: 2 },
  { s: 'Physics', q: 'A vacuum flask reduces heat loss by preventing:', o: ['Conduction only', 'Convection only', 'Radiation only', 'Conduction, convection and radiation'], a: 3 },
  { s: 'Physics', q: 'The unit of heat capacity is:', o: ['J/kg', 'J/kg K', 'J/K', 'Watt'], a: 2 },
  { s: 'Physics', q: 'The specific heat capacity of a substance is the heat required to raise the temperature of:', o: ['1 kg of the substance by 1 degree C', '1 g of the substance by 1 degree C', 'the whole sample by 1 degree C', '1 kg of the substance by 100 degrees C'], a: 0 },
  { s: 'Physics', q: 'Which of the following is the best conductor of heat?', o: ['Glass', 'Copper', 'Rubber', 'Wood'], a: 1 },
  { s: 'Physics', q: 'A steel rod 2.0 m long is heated through 50 K. If its coefficient of linear expansion is 1.2 x 10^-5 K^-1, the increase in length is:', o: ['12 mm', '0.12 mm', '0.012 mm', '1.2 mm'], a: 3 },
  { s: 'Physics', q: 'A gas at constant volume has a pressure of 100 kPa at 27 degrees C. Its pressure at 127 degrees C is:', o: ['133.3 kPa', '150 kPa', '120 kPa', '100 kPa'], a: 0 },
  { s: 'Physics', q: 'A gas occupies 0.50 m^3 at a pressure of 200 kPa. Its volume at 400 kPa, temperature kept constant, is:', o: ['1.00 m^3', '0.50 m^3', '0.25 m^3', '0.10 m^3'], a: 2 },
  { s: 'Physics', q: 'A gas occupies 0.30 m^3 at 27 degrees C at constant pressure. Its volume at 127 degrees C is:', o: ['0.30 m^3', '0.375 m^3', '0.40 m^3', '0.45 m^3'], a: 2 },
  /* --- Waves --- */
  { s: 'Physics', q: 'A wave has a frequency of 50 Hz and a wavelength of 4 m. Its speed is:', o: ['5 m/s', '20 m/s', '12.5 m/s', '200 m/s'], a: 3 },
  { s: 'Physics', q: 'The wavelength of a sound wave of frequency 170 Hz travelling at 340 m/s is:', o: ['0.5 m', '1 m', '2 m', '170 m'], a: 2 },
  { s: 'Physics', q: 'A wave completes one vibration in 0.05 s. Its frequency is:', o: ['0.05 Hz', '5 Hz', '20 Hz', '50 Hz'], a: 2 },
  { s: 'Physics', q: 'Sound waves in air are:', o: ['Transverse waves', 'Longitudinal waves', 'Electromagnetic waves', 'Matter waves'], a: 1 },
  { s: 'Physics', q: 'The wavelength of a wave is the distance between:', o: ['Amplitude and equilibrium position', 'Two consecutive points in phase, such as consecutive crests', 'A crest and the next trough', 'Period and frequency'], a: 1 },
  { s: 'Physics', q: 'Which of the following waves does not require a medium for its propagation?', o: ['Sound wave in air', 'Water wave in a pond', 'Light wave', 'Wave on a stretched string'], a: 2 },
  { s: 'Physics', q: 'The speed of light in vacuum is:', o: ['3 x 10^6 m/s', '3 x 10^10 m/s', '3 x 10^5 m/s', '3 x 10^8 m/s'], a: 3 },
  { s: 'Physics', q: 'When a wave passes from air into glass, its frequency:', o: ['Increases', 'Decreases', 'Remains constant', 'Becomes zero'], a: 2 },
  { s: 'Physics', q: 'A wave travels at 200 m/s and has a wavelength of 5 m. Its period is:', o: ['0.025 s', '4 s', '0.25 s', '20 s'], a: 0 },
  { s: 'Physics', q: 'The amplitude of a sound wave determines its:', o: ['Pitch', 'Loudness', 'Speed', 'Frequency'], a: 1 },
  { s: 'Physics', q: 'The number of complete waves passing a fixed point per second is the:', o: ['Wavelength', 'Amplitude', 'Period', 'Frequency'], a: 3 },
  { s: 'Physics', q: 'The approximate range of frequencies audible to the human ear is:', o: ['20 Hz to 20,000 Hz', '20 Hz to 2,000 Hz', '200 Hz to 20,000 Hz', '20,000 Hz to 200,000 Hz'], a: 0 },
  { s: 'Physics', q: 'A sound of frequency 25,000 Hz is described as:', o: ['Infrasonic', 'Audible', 'Ultrasonic', 'Supersonic'], a: 2 },
  { s: 'Physics', q: 'According to the principle of superposition, the resultant displacement of two waves meeting at a point is the:', o: ['Product of their displacements', 'Difference of their displacements', 'Larger of their displacements', 'Algebraic sum of their displacements'], a: 3 },
  /* --- Sound --- */
  { s: 'Physics', q: 'The approximate speed of sound in air at room temperature is:', o: ['34 m/s', '340 m/s', '3400 m/s', '340 km/s'], a: 1 },
  { s: 'Physics', q: 'An observer hears an echo 2 s after shouting at a cliff. The distance of the cliff (speed of sound = 340 m/s) is:', o: ['680 m', '340 m', '170 m', '34 m'], a: 1 },
  { s: 'Physics', q: 'The pitch of a musical note depends mainly on the sound wave:', o: ['Amplitude', 'Speed', 'Frequency', 'Intensity'], a: 2 },
  { s: 'Physics', q: 'Sound waves cannot travel through:', o: ['Air', 'Water', 'Steel', 'Vacuum'], a: 3 },
  { s: 'Physics', q: 'Sound travels fastest in:', o: ['Air', 'Water', 'Steel', 'Vacuum'], a: 2 },
  { s: 'Physics', q: 'SONAR makes use of:', o: ['Ultrasonic waves', 'Infrared waves', 'Radio waves', 'X-rays'], a: 0 },
  { s: 'Physics', q: 'The loudness of a sound depends mainly on its:', o: ['Frequency', 'Amplitude', 'Wavelength', 'Speed'], a: 1 },
  { s: 'Physics', q: 'Resonance occurs when the frequency of the driving force equals the:', o: ['Amplitude', 'Wavelength', 'Period', 'Natural frequency'], a: 3 },
  { s: 'Physics', q: 'When sound travels from air into water, its speed:', o: ['Increases', 'Decreases', 'Stays the same', 'Becomes zero'], a: 0 },
  { s: 'Physics', q: 'Two tuning forks vibrate at 250 Hz and 252 Hz. The beat frequency heard is:', o: ['0.5 Hz', '251 Hz', '502 Hz', '2 Hz'], a: 3 },
  { s: 'Physics', q: 'The SI unit of frequency is the:', o: ['Watt', 'Newton', 'Hertz', 'Joule'], a: 2 },
  { s: 'Physics', q: 'The time taken for one complete vibration of a wave is called its:', o: ['Wavelength', 'Period', 'Amplitude', 'Frequency'], a: 1 },
  { s: 'Physics', q: 'The intensity of sound obeys the inverse square law. When the distance from the source is doubled, the intensity becomes:', o: ['Double', 'Zero', 'Unchanged', 'One quarter'], a: 3 },
  { s: 'Physics', q: 'Sound produced by irregular and random vibrations is called:', o: ['Music', 'Noise', 'Tone', 'Note'], a: 1 },
  { s: 'Physics', q: 'The repetition of sound caused by reflection from a hard surface is called an:', o: ['Echo', 'Refraction', 'Diffraction', 'Interference'], a: 0 },
  /* --- Light and optics --- */
  { s: 'Physics', q: 'The bending of light as it passes from one medium into another is called:', o: ['Reflection', 'Refraction', 'Diffraction', 'Polarisation'], a: 1 },
  { s: 'Physics', q: 'The refractive index of a medium is 1.5. If the speed of light in vacuum is 3 x 10^8 m/s, its speed in the medium is:', o: ['1.5 x 10^8 m/s', '4.5 x 10^8 m/s', '2.0 x 10^8 m/s', '3.0 x 10^8 m/s'], a: 2 },
  { s: 'Physics', q: 'The law of reflection states that the angle of incidence is equal to the:', o: ['Angle of refraction', 'Critical angle', 'Angle of reflection', 'Glancing angle'], a: 2 },
  { s: 'Physics', q: 'Light travelling from an optically rarer medium into a denser medium bends:', o: ['Towards the normal', 'Away from the normal', 'Along the surface', 'At 45 degrees to the normal'], a: 0 },
  { s: 'Physics', q: 'The critical angle for a medium of refractive index 1.414 is approximately:', o: ['30 degrees', '60 degrees', '90 degrees', '45 degrees'], a: 3 },
  { s: 'Physics', q: 'Total internal reflection can occur when light travels:', o: ['From a rarer medium to a denser medium', 'From vacuum to glass at normal incidence', 'From a denser medium to a rarer medium at any angle of incidence', 'From a denser medium to a rarer medium at an angle greater than the critical angle'], a: 3 },
  { s: 'Physics', q: 'A converging lens is:', o: ['Concave lens', 'Plane lens', 'Convex lens', 'Cylindrical lens'], a: 2 },
  { s: 'Physics', q: 'A concave mirror of focal length 10 cm has an object placed 30 cm in front of it. The image is formed:', o: ['15 cm in front of the mirror', '15 cm behind the mirror', '30 cm in front of the mirror', '7.5 cm in front of the mirror'], a: 0 },
  { s: 'Physics', q: 'An object 4 cm tall forms an image 12 cm tall. The magnification produced is:', o: ['0.33', '4', '3', '12'], a: 2 },
  { s: 'Physics', q: 'A convex lens of focal length 20 cm has a power of:', o: ['0.2 D', '2 D', '5 D', '20 D'], a: 2 },
  { s: 'Physics', q: 'Short sightedness (myopia) is corrected using a:', o: ['Concave lens', 'Cylindrical lens', 'Convex lens', 'Bifocal lens'], a: 0 },
  { s: 'Physics', q: 'Long sightedness (hypermetropia) is corrected using a:', o: ['Convex lens', 'Concave lens', 'Plane lens', 'Prism'], a: 0 },
  { s: 'Physics', q: 'The near point of a normal human eye is at a distance of:', o: ['10 cm', '50 cm', 'Infinity', '25 cm'], a: 3 },
  { s: 'Physics', q: 'The splitting of white light into its colours by a prism is called:', o: ['Reflection', 'Polarisation', 'Dispersion', 'Interference'], a: 2 },
  { s: 'Physics', q: 'Which colour of light is deviated least by a glass prism?', o: ['Violet', 'Blue', 'Red', 'Green'], a: 2 },
  { s: 'Physics', q: 'A photographic camera uses a:', o: ['Concave lens', 'Plane mirror', 'Prism', 'Convex lens'], a: 3 },
  { s: 'Physics', q: 'A convex lens of focal length 15 cm forms an image of an object placed 30 cm from the lens. The image distance is:', o: ['15 cm', '60 cm', '10 cm', '30 cm'], a: 3 },
  { s: 'Physics', q: 'Two lenses of powers 2 D and 3 D are placed in contact. The power of the combination is:', o: ['1 D', '6 D', '5 D', '1.5 D'], a: 2 },
  { s: 'Physics', q: 'Diffraction of a wave is most pronounced when the size of the slit is comparable with the wave:', o: ['Amplitude', 'Frequency', 'Speed', 'Wavelength'], a: 3 },
  { s: 'Physics', q: 'The image formed by a plane mirror is:', o: ['Real, inverted and the same size', 'Virtual, erect and the same size', 'Real, erect and diminished', 'Virtual, inverted and enlarged'], a: 1 },
  { s: 'Physics', q: 'The power of a lens of focal length 0.25 m is:', o: ['0.25 D', '4 D', '0.4 D', '8 D'], a: 1 },
  { s: 'Physics', q: 'Which of the following travels at the speed of light in vacuum?', o: ['Sound waves', 'Water waves', 'Ultrasonic waves', 'Radio waves'], a: 3 },
  { s: 'Physics', q: 'Light may be regarded as a:', o: ['Longitudinal sound wave', 'Transverse electromagnetic wave', 'Matter wave', 'Stationary wave'], a: 1 },
  { s: 'Physics', q: 'A real image can be formed by a:', o: ['Plane mirror only', 'Concave lens', 'Convex lens or concave mirror', 'Diverging mirror only'], a: 2 },
  /* --- Magnetism --- */
  { s: 'Physics', q: 'Outside a bar magnet, the magnetic field lines run from the:', o: ['South pole to the north pole', 'North pole to the south pole', 'Centre of the magnet to both poles', 'Both poles to the centre of the magnet'], a: 1 },
  { s: 'Physics', q: 'Which instrument is used to detect a very small electric current?', o: ['Ammeter', 'Voltmeter', 'Galvanometer', 'Ohmmeter'], a: 2 },
  { s: 'Physics', q: 'Fleming left-hand rule is used to determine the direction of force in an:', o: ['Electric motor', 'Generator', 'Transformer', 'Rectifier'], a: 0 },
  { s: 'Physics', q: 'Fleming right-hand rule is used in a:', o: ['Generator (dynamo)', 'Electric motor', 'Transformer', 'Heating element'], a: 0 },
  { s: 'Physics', q: 'According to Faraday law of electromagnetic induction, the induced EMF is proportional to the rate of change of:', o: ['Current', 'Resistance', 'Magnetic flux linkage', 'Charge'], a: 2 },
  { s: 'Physics', q: 'A conductor of length 0.2 m carrying a current of 4 A is placed at right angles to a uniform field of flux density 0.5 T. The force on it is:', o: ['0.4 N', '4 N', '0.04 N', '2 N'], a: 0 },
  { s: 'Physics', q: 'Soft iron is used for the core of an electromagnet because it:', o: ['Retains magnetism permanently', 'Is easily magnetised and demagnetised', 'Has very high hysteresis loss', 'Cannot be magnetised at all'], a: 1 },
  { s: 'Physics', q: 'A dynamo converts:', o: ['Electrical energy to mechanical energy', 'Chemical energy to electrical energy', 'Mechanical energy to electrical energy', 'Heat energy to mechanical energy'], a: 2 },
  { s: 'Physics', q: 'The magnetic field inside a long solenoid carrying a steady current is:', o: ['Zero', 'Circular', 'Non-uniform', 'Uniform and parallel to the axis'], a: 3 },
  /* --- Electricity and circuits --- */
  { s: 'Physics', q: 'The SI unit of electrical resistance is the:', o: ['Ampere', 'Coulomb', 'Volt', 'Ohm'], a: 3 },
  { s: 'Physics', q: 'A current of 2 A flows through a resistor of 5 Ohm. The potential difference across the resistor is:', o: ['2.5 V', '5 V', '7 V', '10 V'], a: 3 },
  { s: 'Physics', q: 'The current flowing through a 4 Ohm resistor connected to a 12 V supply is:', o: ['3 A', '0.33 A', '48 A', '8 A'], a: 0 },
  { s: 'Physics', q: 'A potential difference of 6 V produces a current of 0.5 A in a wire. The resistance of the wire is:', o: ['12 Ohm', '3 Ohm', '0.083 Ohm', '6 Ohm'], a: 0 },
  { s: 'Physics', q: 'The effective resistance of a 2 Ohm resistor connected in parallel with a 3 Ohm resistor is:', o: ['5 Ohm', '1.2 Ohm', '6 Ohm', '0.6 Ohm'], a: 1 },
  { s: 'Physics', q: 'Resistors of 2 Ohm, 3 Ohm and 5 Ohm are connected in series. The total resistance is:', o: ['0.2 Ohm', '3.3 Ohm', '25 Ohm', '10 Ohm'], a: 3 },
  { s: 'Physics', q: 'Three resistors each of 6 Ohm are connected in parallel. Their effective resistance is:', o: ['18 Ohm', '3 Ohm', '6 Ohm', '2 Ohm'], a: 3 },
  { s: 'Physics', q: 'An appliance operates at 10 V and draws a current of 2 A. The power it consumes is:', o: ['5 W', '12 W', '20 W', '0.5 W'], a: 2 },
  { s: 'Physics', q: 'A current of 3 A flows through a 2 Ohm resistor. The power dissipated as heat is:', o: ['6 W', '9 W', '1.5 W', '18 W'], a: 3 },
  { s: 'Physics', q: 'A 60 W lamp is used for 2 hours. The energy it consumes is:', o: ['120 kWh', '0.06 kWh', '0.3 kWh', '0.12 kWh'], a: 3 },
  { s: 'Physics', q: 'Household appliances such as lamps and sockets are connected in:', o: ['Series', 'Parallel', 'Series-parallel combination', 'Either series or parallel'], a: 1 },
  { s: 'Physics', q: 'The main function of a fuse in an electric circuit is to:', o: ['Increase the current in the circuit', 'Measure the current in the circuit', 'Protect the circuit by melting when the current exceeds a safe value', 'Store electric charge'], a: 2 },
  /* --- Electronics --- */
  { s: 'Physics', q: 'A semiconductor commonly used in the manufacture of transistors is:', o: ['Copper', 'Silicon', 'Rubber', 'Glass'], a: 1 },
  { s: 'Physics', q: 'A semiconductor diode conducts electric current:', o: ['In both directions', 'Only alternating current', 'No current at all', 'In one direction only'], a: 3 },
  { s: 'Physics', q: 'An n-type semiconductor is produced by doping pure silicon with a:', o: ['Trivalent impurity', 'Pentavalent impurity', 'Heptavalent impurity', 'Inert gas impurity'], a: 1 },
  { s: 'Physics', q: 'The majority charge carriers in a p-type semiconductor are:', o: ['Electrons', 'Protons', 'Neutrons', 'Holes'], a: 3 },
  { s: 'Physics', q: 'A transistor can be used as a:', o: ['Rectifier only', 'Filter only', 'Fuse', 'Amplifier or a switch'], a: 3 },
  { s: 'Physics', q: 'The output of an OR logic gate is 1 when:', o: ['At least one input is 1', 'All inputs are 0', 'All inputs are 1', 'The inputs are complementary'], a: 0 },
  { s: 'Physics', q: 'The output of an AND logic gate is 1 only when:', o: ['At least one input is 1', 'All inputs are 0', 'The two inputs differ', 'Both inputs are 1'], a: 3 },
  { s: 'Physics', q: 'Rectification is the conversion of:', o: ['DC to AC', 'AC to DC', 'Mechanical energy to electrical energy', 'AC to AC at a new frequency'], a: 1 },
  { s: 'Physics', q: 'The resistance of a light dependent resistor (LDR) decreases when:', o: ['Light intensity increases', 'Light intensity decreases', 'Temperature decreases', 'Pressure increases'], a: 0 },
  /* --- Radioactivity --- */
  { s: 'Physics', q: 'An alpha particle is:', o: ['A fast-moving electron', 'A helium nucleus', 'An electromagnetic ray', 'A hydrogen nucleus'], a: 1 },
  { s: 'Physics', q: 'A beta particle is:', o: ['An electron', 'A helium nucleus', 'A proton', 'A neutron'], a: 0 },
  { s: 'Physics', q: 'Which of the following radiations is the most penetrating?', o: ['Alpha particles', 'Beta particles', 'Gamma rays', 'All are equally penetrating'], a: 2 },
  { s: 'Physics', q: 'The half-life of a radioactive substance is the time taken for:', o: ['Half of the nuclei present to decay', 'Its activity to fall to zero', 'All of its nuclei to decay', 'Its nuclei to double in number'], a: 0 },
  { s: 'Physics', q: 'Carbon-14 is mainly used for:', o: ['Powering nuclear reactors', 'Medical imaging of bones', 'Sterilising food', 'Dating archaeological specimens'], a: 3 },
  { s: 'Physics', q: 'Nuclear fission is the:', o: ['Joining of two light nuclei', 'Annihilation of a charged particle', 'Emission of an alpha particle', 'Splitting of a heavy nucleus'], a: 3 },
  { s: 'Physics', q: 'Nuclear fusion is the:', o: ['Splitting of a heavy nucleus', 'Combining of light nuclei', 'Natural radioactive decay of a nucleus', 'Oxidation of a metal'], a: 1 },
  { s: 'Physics', q: 'The SI unit of radioactivity is the:', o: ['Curie', 'Becquerel', 'Gray', 'Sievert'], a: 1 },
  { s: 'Physics', q: 'Radioactive decay of a given nucleus is:', o: ['Predictable for that individual nucleus', 'Caused by changes in temperature', 'Random and spontaneous', 'Reversible at will'], a: 2 },
  { s: 'Physics', q: 'The atomic number of an element is the number of:', o: ['Neutrons in the nucleus', 'Protons in the nucleus', 'Nucleons in the nucleus', 'Electron shells'], a: 1 },
  { s: 'Physics', q: 'Isotopes of an element have the same:', o: ['Atomic number', 'Mass number', 'Number of neutrons', 'Number of nucleons'], a: 0 },
  /* --- Elasticity and materials --- */
  { s: 'Physics', q: 'Hooke law states that within the elastic limit, the extension of a spring is:', o: ['Inversely proportional to the applied load', 'Directly proportional to the applied load', 'Independent of the applied load', 'Proportional to the square of the applied load'], a: 1 },
  { s: 'Physics', q: 'A spring of force constant 100 N/m is stretched by 0.10 m. The force required is:', o: ['1000 N', '1 N', '0.01 N', '10 N'], a: 3 },
  { s: 'Physics', q: 'Strain is defined as:', o: ['Force per unit area', 'Extension per unit original length', 'Stress divided by the modulus', 'Load divided by the extension'], a: 1 },
  { s: 'Physics', q: 'Young modulus is the ratio of:', o: ['Stress divided by strain', 'Strain divided by stress', 'Force divided by extension', 'Pressure divided by volume'], a: 0 },
  { s: 'Physics', q: 'A spring of force constant 50 N/m is stretched by 0.20 m. The elastic potential energy stored is:', o: ['10 J', '0.5 J', '4 J', '1 J'], a: 3 },
  { s: 'Physics', q: 'Which of the following materials is brittle?', o: ['Copper', 'Steel', 'Lead', 'Glass'], a: 3 },
  /* --- Pressure and buoyancy --- */
  { s: 'Physics', q: 'A force of 100 N acts on an area of 0.5 m^2. The pressure exerted is:', o: ['50 Pa', '200 Pa', '100 Pa', '0.005 Pa'], a: 1 },
  { s: 'Physics', q: 'The pressure exerted by a liquid of density 1000 kg/m^3 at a depth of 5 m (take g = 10 m/s^2) is:', o: ['5000 Pa', '500 Pa', '500000 Pa', '50000 Pa'], a: 3 },
  { s: 'Physics', q: 'Atmospheric pressure at sea level is approximately:', o: ['10^3 Pa', '10^5 Pa', '10^7 Pa', '10 Pa'], a: 1 },
  { s: 'Physics', q: 'A hydraulic press works on the:', o: ['Pascal principle', 'Archimedes principle', 'Bernoulli principle', 'Hooke law'], a: 0 },
  { s: 'Physics', q: 'The density of a body of mass 2 kg and volume 0.5 m^3 is:', o: ['4 kg/m^3', '0.25 kg/m^3', '2 kg/m^3', '8 kg/m^3'], a: 0 },
  { s: 'Physics', q: 'According to Archimedes principle, the upthrust on a body immersed in a fluid is equal to the:', o: ['Mass of the body', 'Volume of the body', 'Pressure at the base of the container', 'Weight of the fluid displaced'], a: 3 },
  { s: 'Physics', q: 'A body floats on the surface of a liquid when its density is:', o: ['Greater than the density of the liquid', 'Less than the density of the liquid', 'Equal to twice the density of the liquid', 'Equal to the pressure in the liquid'], a: 1 },
  { s: 'Physics', q: 'An iron nail sinks in water because the density of iron is:', o: ['Greater than that of water', 'Less than that of water', 'The same as that of water', 'Half that of mercury'], a: 0 },
  /* --- Circular motion and gravitation --- */
  { s: 'Physics', q: 'A body of mass 2 kg moves in a circle of radius 5 m at 10 m/s. The centripetal force required is:', o: ['4 N', '40 N', '20 N', '100 N'], a: 1 },
  { s: 'Physics', q: 'A body moving in a circle of radius 5 m at a speed of 10 m/s has a centripetal acceleration of:', o: ['0.5 m/s^2', '5 m/s^2', '10 m/s^2', '20 m/s^2'], a: 3 },
  { s: 'Physics', q: 'A body moves in a circle of radius 5 m at a constant speed of 10 m/s. The time for one revolution is approximately:', o: ['6.28 s', '3.14 s', '0.31 s', '1.57 s'], a: 1 },
  { s: 'Physics', q: 'The weight of a body of mass 5 kg on the moon (g = 1.6 m/s^2) is approximately:', o: ['50 N', '8 N', '300 N', '1.6 N'], a: 1 },
  { s: 'Physics', q: 'The mass of a body on the moon compared with its mass on the earth is:', o: ['The same', 'One-sixth', 'Six times', 'Twice'], a: 0 },
  { s: 'Physics', q: 'The escape velocity from the surface of the earth is about:', o: ['9.8 km/s', '7.9 km/s', '12.4 km/s', '11.2 km/s'], a: 3 },
  { s: 'Physics', q: 'If the distance between two masses is halved while each mass is doubled, the gravitational force between them becomes:', o: ['Twice', 'Four times', 'Sixteen times', 'Unchanged'], a: 2 },
  { s: 'Physics', q: 'The value of g is maximum at the:', o: ['Centre of the earth', 'Equator', 'Latitude 45 degrees', 'Poles'], a: 3 },
  /* --- Oscillations, energy and transformers --- */
  { s: 'Physics', q: 'A simple pendulum of length 1 m (take g = 10 m/s^2) has a period of approximately:', o: ['0.5 s', '2 s', '1 s', '4 s'], a: 1 },
  { s: 'Physics', q: 'In simple harmonic motion, the acceleration of the particle is:', o: ['Directly proportional to the displacement and directed towards the equilibrium position', 'Directly proportional to the displacement and directed away from the equilibrium position', 'Constant and always zero', 'Proportional to the velocity of the particle only'], a: 0 },
  { s: 'Physics', q: 'A transformer has 100 turns in its primary coil and 500 turns in its secondary coil. If the primary is supplied with 60 V, the secondary voltage is:', o: ['300 V', '12 V', '60 V', '30 V'], a: 0 }
]);
