/* =========================================================
   JAMB Study Tracker — past question bank
   Loaded before app.js as window.QUESTION_BANK
   { s: subject, q: question, o: [four options], a: correct index }
   ========================================================= */
window.QUESTION_BANK = [
  /* --- Use of English --- */
  { s: 'Use of English', q: 'Choose the option nearest in meaning to the word in capital letters: The chairman was EBULLIENT during the ceremony.', o: ['Tired', 'Cheerful', 'Angry', 'Silent'], a: 1 },
  { s: 'Use of English', q: 'Choose the option opposite in meaning to the word: BENEVOLENT', o: ['Kind', 'Generous', 'Malevolent', 'Caring'], a: 2 },
  { s: 'Use of English', q: 'Complete the sentence: Neither of the boys ___ the answer.', o: ['have', 'were', 'has', 'are'], a: 2 },
  { s: 'Use of English', q: 'Fill the gap: She has been living in Lagos ___ 2015.', o: ['for', 'from', 'since', 'by'], a: 2 },
  { s: 'Use of English', q: 'A person who hates the whole of mankind is a ___', o: ['philanthropist', 'misanthrope', 'stoic', 'hermit'], a: 1 },
  { s: 'Use of English', q: 'The word "candid" means most nearly:', o: ['secretive', 'frank', 'careless', 'bitter'], a: 1 },
  { s: 'Use of English', q: 'Choose the correctly punctuated sentence:', o: ['"Where are you going?" he asked.', '"Where are you going" he asked?', '"Where are you going?", he asked.', 'Where are you going? he asked.'], a: 0 },
  { s: 'Use of English', q: 'The plural of "crisis" is:', o: ['crisises', 'crises', 'crisis', 'crisi'], a: 1 },
  { s: 'Use of English', q: 'Choose the option nearest in meaning to the word in capital letters: The judge gave an IMPARTIAL verdict.', o: ['biased', 'hasty', 'fair', 'uncertain'], a: 2 },
  { s: 'Use of English', q: 'Choose the option opposite in meaning to the word: SCARCE', o: ['rare', 'plentiful', 'deficient', 'limited'], a: 1 },
  { s: 'Use of English', q: 'Complete the sentence: He is one of the boys who ___ been selected.', o: ['have', 'has', 'is', 'was'], a: 0 },
  { s: 'Use of English', q: 'The plural of "leaf" is:', o: ['leafs', 'leafes', 'leaves', 'leaf'], a: 2 },
  { s: 'Use of English', q: 'A person who writes the biography of another person is a:', o: ['biographer', 'autobiographer', 'novelist', 'historian'], a: 0 },
  { s: 'Use of English', q: 'Choose the correctly spelt word:', o: ['accomodation', 'acommodation', 'accommodation', 'accommodetion'], a: 2 },
  { s: 'Use of English', q: 'To "let the cat out of the bag" means to:', o: ['start an argument', 'reveal a secret', 'buy something cheap', 'escape from danger'], a: 1 },
  { s: 'Use of English', q: 'Choose the correct reported form: She said, "I am tired."', o: ['She said that she is tired.', 'She said that she was tired.', 'She says she was tired.', 'She said that she has tired.'], a: 1 },
  { s: 'Use of English', q: 'A word that modifies a verb, an adjective or another adverb is an:', o: ['adjective', 'preposition', 'adverb', 'conjunction'], a: 2 },
  { s: 'Use of English', q: 'A word that imitates the sound it describes, as in "buzz" or "hiss", is an example of:', o: ['onomatopoeia', 'alliteration', 'euphemism', 'personification'], a: 0 },

  /* --- Mathematics --- */
  { s: 'Mathematics', q: 'Simplify: 2/3 + 3/4', o: ['17/12', '5/7', '6/12', '24/17'], a: 0 },
  { s: 'Mathematics', q: 'If 3x − 5 = 16, what is x?', o: ['5', '6', '7', '8'], a: 2 },
  { s: 'Mathematics', q: 'Find the area of a circle of radius 7 cm. (Take π = 22/7)', o: ['44 cm²', '154 cm²', '22 cm²', '308 cm²'], a: 1 },
  { s: 'Mathematics', q: 'What is 15% of ₦200?', o: ['₦15', '₦25', '₦30', '₦35'], a: 2 },
  { s: 'Mathematics', q: 'Solve: 2(x + 3) = 18', o: ['x = 5', 'x = 6', 'x = 7', 'x = 12'], a: 1 },
  { s: 'Mathematics', q: 'A right-angled triangle has sides 3 cm, 4 cm and 5 cm. Its area is:', o: ['6 cm²', '12 cm²', '7 cm²', '15 cm²'], a: 0 },
  { s: 'Mathematics', q: 'Simplify: √144 + √25', o: ['12', '15', '17', '25'], a: 2 },
  { s: 'Mathematics', q: 'Simple interest on ₦5,000 at 10% per annum for 2 years is:', o: ['₦500', '₦1,000', '₦1,500', '₦2,000'], a: 1 },
  { s: 'Mathematics', q: 'The mean of 4, 6, 8 and x is 6. Find x.', o: ['4', '5', '6', '7'], a: 2 },
  { s: 'Mathematics', q: 'If log₁₀ 1000 = x, find x.', o: ['1', '2', '3', '4'], a: 2 },
  { s: 'Mathematics', q: 'The median of 3, 5, 7, 9 and 11 is:', o: ['5', '6', '7', '9'], a: 2 },
  { s: 'Mathematics', q: 'A triangle has base 10 cm and height 5 cm. Its area is:', o: ['25 cm²', '50 cm²', '15 cm²', '30 cm²'], a: 0 },
  { s: 'Mathematics', q: 'Solve the simultaneous equations: x + y = 10 and x − y = 4.', o: ['x = 7, y = 3', 'x = 6, y = 4', 'x = 5, y = 5', 'x = 8, y = 2'], a: 0 },
  { s: 'Mathematics', q: 'The probability of getting a head when a fair coin is tossed once is:', o: ['1/4', '1/2', '1', '0'], a: 1 },
  { s: 'Mathematics', q: 'The sum of the first 10 natural numbers is:', o: ['45', '50', '55', '60'], a: 2 },
  { s: 'Mathematics', q: 'Factorise: x² − 9', o: ['(x − 3)(x + 3)', '(x − 9)(x + 1)', '(x − 3)(x − 3)', '(x + 9)(x − 1)'], a: 0 },
  { s: 'Mathematics', q: 'The circumference of a circle is 44 cm. Find its radius. (Take π = 22/7)', o: ['7 cm', '14 cm', '3.5 cm', '21 cm'], a: 0 },
  { s: 'Mathematics', q: 'If 30% of a number is 60, the number is:', o: ['150', '180', '200', '240'], a: 2 },

  /* --- Physics --- */
  { s: 'Physics', q: 'The SI unit of force is the:', o: ['Joule', 'Watt', 'Newton', 'Pascal'], a: 2 },
  { s: 'Physics', q: 'Which of these is a vector quantity?', o: ['Speed', 'Distance', 'Mass', 'Velocity'], a: 3 },
  { s: 'Physics', q: "Newton's first law of motion is also called the law of:", o: ['Inertia', 'Momentum', 'Acceleration', 'Reaction'], a: 0 },
  { s: 'Physics', q: 'The unit of power is the:', o: ['Volt', 'Ampere', 'Watt', 'Ohm'], a: 2 },
  { s: 'Physics', q: 'The formula for kinetic energy is:', o: ['mgh', '½mv²', 'Fd', 'mc²'], a: 1 },
  { s: 'Physics', q: 'The speed of light is approximately:', o: ['3 × 10⁶ m/s', '3 × 10⁸ m/s', '3 × 10¹⁰ m/s', '340 m/s'], a: 1 },
  { s: 'Physics', q: 'A body moving in a circle at constant speed has:', o: ['zero acceleration', 'constant velocity', 'centripetal acceleration', 'increasing speed'], a: 2 },
  { s: 'Physics', q: 'Which instrument measures atmospheric pressure?', o: ['Barometer', 'Hygrometer', 'Anemometer', 'Thermometer'], a: 0 },
  { s: 'Physics', q: 'The SI unit of energy is the:', o: ['Newton', 'Joule', 'Watt', 'Pascal'], a: 1 },
  { s: 'Physics', q: 'Which of these is a scalar quantity?', o: ['Velocity', 'Acceleration', 'Speed', 'Force'], a: 2 },
  { s: 'Physics', q: "Ohm's law states that the potential difference V is equal to:", o: ['IR', 'I/R', 'R/I', 'VI'], a: 0 },
  { s: 'Physics', q: "Newton's second law of motion shows that the rate of change of momentum of a body is equal to the:", o: ['work done', 'force applied', 'power developed', 'kinetic energy'], a: 1 },
  { s: 'Physics', q: 'The weight of a mass of 2 kg on Earth (take g = 10 m/s²) is:', o: ['2 N', '10 N', '20 N', '0.2 N'], a: 2 },
  { s: 'Physics', q: 'Which of these electromagnetic waves has the longest wavelength?', o: ['Gamma rays', 'X-rays', 'Ultraviolet rays', 'Radio waves'], a: 3 },
  { s: 'Physics', q: 'At what temperature do the Celsius and Fahrenheit scales give the same reading?', o: ['−40°C', '0°C', '40°C', '100°C'], a: 0 },
  { s: 'Physics', q: 'Sound waves cannot travel through a:', o: ['vacuum', 'metal', 'water', 'air'], a: 0 },
  { s: 'Physics', q: 'The SI unit of electric charge is the:', o: ['ampere', 'coulomb', 'volt', 'ohm'], a: 1 },
  { s: 'Physics', q: 'The pascal is the SI unit of:', o: ['force', 'pressure', 'power', 'energy'], a: 1 },

  /* --- Chemistry --- */
  { s: 'Chemistry', q: 'The chemical symbol for gold is:', o: ['Go', 'Gd', 'Au', 'Ag'], a: 2 },
  { s: 'Chemistry', q: 'The pH of pure water at 25°C is:', o: ['0', '7', '10', '14'], a: 1 },
  { s: 'Chemistry', q: 'Zinc reacts with dilute hydrochloric acid to produce:', o: ['Oxygen', 'Chlorine', 'Hydrogen', 'Carbon dioxide'], a: 2 },
  { s: 'Chemistry', q: 'The most abundant gas in the air is:', o: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'], a: 2 },
  { s: 'Chemistry', q: 'The atomic number of an element is the number of:', o: ['neutrons', 'protons', 'shells', 'isotopes'], a: 1 },
  { s: 'Chemistry', q: 'The chemical formula of common salt is:', o: ['KCl', 'NaOH', 'NaCl', 'NaHCO₃'], a: 2 },
  { s: 'Chemistry', q: 'Which of these is a noble gas?', o: ['Chlorine', 'Neon', 'Nitrogen', 'Helium compounds'], a: 1 },
  { s: 'Chemistry', q: 'Water is formed when hydrogen burns in:', o: ['chlorine', 'oxygen', 'nitrogen', 'sulphur'], a: 1 },
  { s: 'Chemistry', q: 'Which of these is a base?', o: ['HCl', 'NaOH', 'NaCl', 'H₂SO₄'], a: 1 },
  { s: 'Chemistry', q: 'The number of electrons in the outermost shell of a chlorine atom (atomic number 17) is:', o: ['1', '5', '7', '17'], a: 2 },
  { s: 'Chemistry', q: 'The change of a liquid into vapour at all temperatures below its boiling point is called:', o: ['boiling', 'evaporation', 'sublimation', 'condensation'], a: 1 },
  { s: 'Chemistry', q: 'Which of these is an exothermic change?', o: ['Melting of ice', 'Evaporation of water', 'Combustion of methane', 'Dissolving ammonium nitrate in water'], a: 2 },
  { s: 'Chemistry', q: 'The chemical formula of ethanol is:', o: ['C₂H₅OH', 'CH₃COOH', 'C₂H₄', 'CO₂'], a: 0 },
  { s: 'Chemistry', q: 'The gas that turns lime water milky is:', o: ['oxygen', 'carbon(IV) oxide', 'hydrogen', 'ammonia'], a: 1 },
  { s: 'Chemistry', q: 'Isotopes of the same element have the same number of:', o: ['neutrons', 'protons', 'nucleons', 'energy levels'], a: 1 },
  { s: 'Chemistry', q: 'Which of these processes requires both oxygen and moisture?', o: ['Rusting of iron', 'Melting of ice', 'Dissolving sugar in water', 'Sublimation of iodine'], a: 0 },
  { s: 'Chemistry', q: 'Which of these can be used to prepare oxygen in the laboratory?', o: ['Zinc and dilute hydrochloric acid', 'Hydrogen peroxide and manganese(IV) oxide', 'Copper and oxygen', 'Sodium chloride and water'], a: 1 },
  { s: 'Chemistry', q: 'Which of these is a hydrocarbon?', o: ['Methane', 'Sodium chloride', 'Water', 'Ammonia'], a: 0 },

  /* --- Biology --- */
  { s: 'Biology', q: 'The powerhouse of the cell is the:', o: ['ribosome', 'mitochondrion', 'nucleus', 'vacuole'], a: 1 },
  { s: 'Biology', q: 'Photosynthesis takes place mainly in the:', o: ['chloroplast', 'cell wall', 'cytoplasm', 'membrane'], a: 0 },
  { s: 'Biology', q: 'Which blood cells fight infection?', o: ['Red blood cells', 'Platelets', 'White blood cells', 'Plasma cells only'], a: 2 },
  { s: 'Biology', q: 'The largest organ of the human body is the:', o: ['Liver', 'Skin', 'Heart', 'Brain'], a: 1 },
  { s: 'Biology', q: 'The basic unit of life is the:', o: ['tissue', 'organ', 'cell', 'molecule'], a: 2 },
  { s: 'Biology', q: 'During photosynthesis, plants take in:', o: ['oxygen', 'nitrogen', 'carbon dioxide', 'hydrogen'], a: 2 },
  { s: 'Biology', q: 'The universal donor blood group is:', o: ['AB+', 'A', 'B', 'O'], a: 3 },
  { s: 'Biology', q: 'Cell division that produces two identical cells is:', o: ['meiosis', 'mitosis', 'fertilisation', 'binary fission'], a: 1 },
  { s: 'Biology', q: 'The site of protein synthesis in the cell is the:', o: ['ribosome', 'golgi apparatus', 'lysosome', 'cell wall'], a: 0 },
  { s: 'Biology', q: 'Which of these structures is found in animal cells but not in typical plant cells?', o: ['Cell wall', 'Chloroplast', 'Centriole', 'Large vacuole'], a: 2 },
  { s: 'Biology', q: 'The movement of water molecules from a region of high concentration to one of low concentration through a semi-permeable membrane is:', o: ['diffusion', 'osmosis', 'plasmolysis', 'active transport'], a: 1 },
  { s: 'Biology', q: 'Blood vessels that carry blood away from the heart are the:', o: ['veins', 'arteries', 'capillaries', 'venules'], a: 1 },
  { s: 'Biology', q: 'The functional unit of the kidney is the:', o: ['neuron', 'nephron', 'alveolus', 'villus'], a: 1 },
  { s: 'Biology', q: 'Gregor Mendel is known as the father of:', o: ['ecology', 'genetics', 'physiology', 'medicine'], a: 1 },
  { s: 'Biology', q: 'Which vitamin is synthesised in the skin when it is exposed to sunlight?', o: ['Vitamin A', 'Vitamin B₁', 'Vitamin C', 'Vitamin D'], a: 3 },
  { s: 'Biology', q: 'The ingestion of solid food particles by a cell is called:', o: ['osmosis', 'diffusion', 'phagocytosis', 'transpiration'], a: 2 },
  { s: 'Biology', q: 'The total number of chromosomes in a normal human body cell is:', o: ['23', '24', '46', '48'], a: 2 },
  { s: 'Biology', q: 'The green colouring matter in leaves is:', o: ['chlorophyll', 'carotene', 'haemoglobin', 'melanin'], a: 0 },

  /* --- Economics --- */
  { s: 'Economics', q: 'The fundamental economic problem is:', o: ['inflation', 'scarcity', 'unemployment', 'monopoly'], a: 1 },
  { s: 'Economics', q: 'Man-made factors of production are called:', o: ['land', 'labour', 'capital', 'entrepreneurship'], a: 2 },
  { s: 'Economics', q: 'A market where buyers and sellers meet is the:', o: ['factor market only', 'market', 'stock exchange', 'bank'], a: 1 },
  { s: 'Economics', q: 'The demand curve normally slopes:', o: ['upward', 'downward', 'horizontally', 'vertically'], a: 1 },
  { s: 'Economics', q: 'Goods that see demand rise as income rises are:', o: ['inferior goods', 'normal goods', 'substitute goods', 'public goods'], a: 1 },
  { s: 'Economics', q: 'The central bank of Nigeria is:', o: ['CBN', 'NDIC', 'SEC', 'NSE'], a: 0 },
  { s: 'Economics', q: 'The measure of the average level of prices is the:', o: ['index of retail prices', 'interest rate', 'exchange rate', 'budget'], a: 0 },
  { s: 'Economics', q: 'An economy that relies only on the public sector is a:', o: ['mixed economy', 'market economy', 'command economy', 'free economy'], a: 2 },
  { s: 'Economics', q: 'The price system is also known as the:', o: ['command system', 'market system', 'mixed system', 'public system'], a: 1 },
  { s: 'Economics', q: 'Which of these is NOT a factor of production?', o: ['Land', 'Labour', 'Money', 'Capital'], a: 2 },
  { s: 'Economics', q: 'When the price of a good rises and its quantity demanded falls, the good obeys the:', o: ['law of supply', 'law of demand', 'law of returns to scale', "Say's law"], a: 1 },
  { s: 'Economics', q: 'Inflation refers to a sustained rise in the:', o: ['general price level', 'volume of exports', 'level of employment', 'supply of a single commodity'], a: 0 },
  { s: 'Economics', q: 'The NDIC is an institution that insures:', o: ['bank deposits', 'life policies', 'company shares', 'export credits'], a: 0 },
  { s: 'Economics', q: "Devaluation of a currency makes a country's exports:", o: ['more expensive', 'cheaper', 'inelastic', 'dutiable'], a: 1 },
  { s: 'Economics', q: 'A tax placed on imported goods is a:', o: ['subsidy', 'tariff', 'quota', 'grant'], a: 1 },
  { s: 'Economics', q: 'A monopoly exists in a market when there is:', o: ['a single seller', 'a single buyer', 'many sellers', 'many buyers'], a: 0 },
  { s: 'Economics', q: 'Marginal utility is the:', o: ['total satisfaction from all units consumed', 'average satisfaction per unit', 'additional satisfaction from consuming one more unit', 'satisfaction derived from the first unit'], a: 2 },
  { s: 'Economics', q: 'Opportunity cost is best defined as:', o: ['the total cost of production', 'the cost already incurred', 'the next best alternative forgone', 'a fixed cost that does not change'], a: 2 },

  /* --- Government --- */
  { s: 'Government', q: 'The arm of government that interprets the law is the:', o: ['executive', 'legislature', 'judiciary', 'civil service'], a: 2 },
  { s: 'Government', q: 'How many states does Nigeria have?', o: ['24', '30', '36', '37'], a: 2 },
  { s: 'Government', q: 'Local government is the ___ tier of government in Nigeria.', o: ['first', 'second', 'third', 'fourth'], a: 2 },
  { s: 'Government', q: 'Suffrage means the right to:', o: ['own property', 'vote', 'hold office', 'free speech'], a: 1 },
  { s: 'Government', q: 'Nigeria became a republic in:', o: ['1960', '1963', '1966', '1979'], a: 1 },
  { s: 'Government', q: 'A bicameral legislature has:', o: ['one chamber', 'two chambers', 'three chambers', 'no chamber'], a: 1 },
  { s: 'Government', q: 'The 1999 Constitution of Nigeria is the ___ constitution.', o: ['first', 'second', 'third', 'fourth'], a: 3 },
  { s: 'Government', q: 'The head of state and government of Nigeria is the:', o: ['President', 'Governor', 'Speaker', 'Chief Justice'], a: 0 },
  { s: 'Government', q: 'Which of these is NOT an arm of government?', o: ['Legislature', 'Executive', 'Judiciary', 'Civil service'], a: 3 },
  { s: 'Government', q: 'The doctrine of separation of powers was associated with:', o: ['Thomas Hobbes', 'Montesquieu', 'Karl Marx', 'Aristotle'], a: 1 },
  { s: 'Government', q: 'The party that wins the majority of seats in an election forms the:', o: ['opposition', 'government', 'cabinet', 'senate'], a: 1 },
  { s: 'Government', q: 'Nigeria is divided into how many geopolitical zones?', o: ['4', '5', '6', '7'], a: 2 },
  { s: 'Government', q: 'In a democracy, ultimate sovereignty rests with:', o: ['the people', 'the military', 'the monarch', 'the judiciary'], a: 0 },
  { s: 'Government', q: 'Which of these is a fundamental right under the 1999 Constitution of Nigeria?', o: ['Right to free air travel', 'Right to fair hearing', 'Right to free university education for all', 'Right to own an oil refinery without a licence'], a: 1 },
  { s: 'Government', q: 'The body that conducts elections in Nigeria is:', o: ['INEC', 'NDIC', 'EFCC', 'CBN'], a: 0 },
  { s: 'Government', q: 'A system of government in which the people rule themselves through elected representatives is:', o: ['autocracy', 'monarchy', 'democracy', 'oligarchy'], a: 2 },
  { s: 'Government', q: 'The first Nigerian constitution was enacted in:', o: ['1914', '1922', '1946', '1951'], a: 1 },
  { s: 'Government', q: 'The Nigerian Senate is composed of how many members?', o: ['91', '109', '359', '360'], a: 1 },

  /* --- Geography --- */
  { s: 'Geography', q: 'The instrument used to measure atmospheric pressure is the:', o: ['thermometer', 'barometer', 'hygrometer', 'rain gauge'], a: 1 },
  { s: 'Geography', q: 'The line of latitude 0° is called the:', o: ['Tropic of Cancer', 'Equator', 'Prime Meridian', 'Tropic of Capricorn'], a: 1 },
  { s: 'Geography', q: 'The capital of Nigeria is:', o: ['Lagos', 'Abuja', 'Kano', 'Ibadan'], a: 1 },
  { s: 'Geography', q: 'The river that meets the Benue at Lokoja is the River:', o: ['Nile', 'Niger', 'Cross', 'Benue'], a: 1 },
  { s: 'Geography', q: 'Crude oil in Nigeria is found mainly in the:', o: ['Sahel', 'Niger Delta', 'Chad Basin', 'North Central'], a: 1 },
  { s: 'Geography', q: 'The largest ethnic group in Nigeria by population is the:', o: ['Yoruba', 'Igbo', 'Hausa-Fulani', 'Ijaw'], a: 2 },
  { s: 'Geography', q: 'Which of these is a non-renewable resource?', o: ['Solar energy', 'Wind', 'Crude oil', 'Water'], a: 2 },
  { s: 'Geography', q: 'The climate of the southern part of Nigeria is:', o: ['arid', 'tropical rainforest', 'sahel', 'temperate'], a: 1 },
  { s: 'Geography', q: 'The Prime Meridian (0° longitude) passes through:', o: ['Paris', 'Greenwich', 'Lagos', 'Cairo'], a: 1 },
  { s: 'Geography', q: 'The capital of Ghana is:', o: ['Accra', 'Lome', 'Abidjan', 'Kumasi'], a: 0 },
  { s: 'Geography', q: "The largest ocean on the Earth's surface is the:", o: ['Atlantic', 'Pacific', 'Indian', 'Arctic'], a: 1 },
  { s: 'Geography', q: 'The layer of the atmosphere in which all weather phenomena occur is the:', o: ['troposphere', 'stratosphere', 'mesosphere', 'thermosphere'], a: 0 },
  { s: 'Geography', q: 'The rocky outermost layer of the Earth is the:', o: ['core', 'mantle', 'crust', 'magma'], a: 2 },
  { s: 'Geography', q: 'On a map scale of 1 : 100,000, 1 cm represents:', o: ['100 m', '1 km', '10 km', '100 km'], a: 1 },
  { s: 'Geography', q: 'Which of these is a cash crop grown in Nigeria?', o: ['Cassava', 'Yam', 'Cocoa', 'Maize'], a: 2 },
  { s: 'Geography', q: 'The instrument used to measure rainfall is the:', o: ['anemometer', 'barometer', 'rain gauge', 'seismometer'], a: 2 },
  { s: 'Geography', q: 'The imaginary line of latitude 23½° N is the:', o: ['Tropic of Cancer', 'Arctic Circle', 'Tropic of Capricorn', 'Equator'], a: 0 },
  { s: 'Geography', q: 'The capital of Kenya is:', o: ['Kampala', 'Nairobi', 'Kigali', 'Dar es Salaam'], a: 1 },

  /* --- Literature-in-English --- */
  { s: 'Literature-in-English', q: 'Who wrote "Things Fall Apart"?', o: ['Wole Soyinka', 'Chinua Achebe', 'Ngugi wa Thiong\'o', 'Ben Okri'], a: 1 },
  { s: 'Literature-in-English', q: 'The protagonist of "Things Fall Apart" is:', o: ['Obierika', 'Okonkwo', 'Ekwefi', 'Nwoye'], a: 1 },
  { s: 'Literature-in-English', q: '"The wind whispered through the trees" is an example of:', o: ['simile', 'hyperbole', 'personification', 'alliteration'], a: 2 },
  { s: 'Literature-in-English', q: 'A poem of fourteen lines is a:', o: [' ode', 'elegy', 'sonnet', 'ballad'], a: 2 },
  { s: 'Literature-in-English', q: 'A comparison using "like" or "as" is a:', o: ['metaphor', 'simile', 'irony', 'synecdoche'], a: 1 },
  { s: 'Literature-in-English', q: 'Who wrote "The Lion and the Jewel"?', o: ['Christopher Okigbo', 'Wole Soyinka', 'J.P. Clark', 'Flora Nwapa'], a: 1 },
  { s: 'Literature-in-English', q: 'The author of "The Road Not Taken" is:', o: ['Robert Frost', 'William Wordsworth', 'Alfred Tennyson', 'Pablo Neruda'], a: 0 },
  { s: 'Literature-in-English', q: 'A prose narrative long enough to be published as a book is a:', o: ['novel', 'epic', 'lyric', 'proverb'], a: 0 },
  { s: 'Literature-in-English', q: 'Who wrote "Arrow of God"?', o: ['Wole Soyinka', 'Chinua Achebe', 'Flora Nwapa', 'Ben Okri'], a: 1 },
  { s: 'Literature-in-English', q: 'A play written mainly to make its audience laugh is a:', o: ['tragedy', 'ode', 'comedy', 'elegy'], a: 2 },
  { s: 'Literature-in-English', q: 'In "All the world\'s a stage", the comparison of the world to a stage is a:', o: ['simile', 'metaphor', 'personification', 'irony'], a: 1 },
  { s: 'Literature-in-English', q: 'A short story that teaches a moral lesson, often with animals as characters, is a:', o: ['ballad', 'fable', 'lyric', 'epic'], a: 1 },
  { s: 'Literature-in-English', q: 'Who wrote "Ake: The Years of Childhood"?', o: ['Wole Soyinka', 'Chinua Achebe', 'Christopher Okigbo', 'J.P. Clark'], a: 0 },
  { s: 'Literature-in-English', q: 'The repetition of initial consonant sounds in neighbouring words, as in "big brown bear", is:', o: ['assonance', 'alliteration', 'euphemism', 'onomatopoeia'], a: 1 },
  { s: 'Literature-in-English', q: 'Exaggeration for effect, as in "I have told you a million times", is:', o: ['simile', 'irony', 'hyperbole', 'litotes'], a: 2 },
  { s: 'Literature-in-English', q: 'The central or main character of a novel or play is the:', o: ['antagonist', 'foil', 'narrator', 'protagonist'], a: 3 },
  { s: 'Literature-in-English', q: 'Who wrote "Purple Hibiscus"?', o: ['Flora Nwapa', 'Chimamanda Ngozi Adichie', 'Buchi Emecheta', 'Zainab Alkali'], a: 1 },
  { s: 'Literature-in-English', q: 'A poem written in honour of or lamenting the dead is an:', o: ['ode', 'ballad', 'elegy', 'sonnet'], a: 2 },

  /* --- History --- */
  { s: 'History', q: 'Nigeria gained independence in:', o: ['1957', '1960', '1963', '1970'], a: 1 },
  { s: 'History', q: 'The amalgamation of the Northern and Southern Protectorates took place in:', o: ['1900', '1914', '1946', '1954'], a: 1 },
  { s: 'History', q: 'The first indigenous Governor-General of Nigeria was:', o: ['Nnamdi Azikiwe', 'Tafawa Balewa', 'John Macpherson', 'Nwafor Orizu'], a: 0 },
  { s: 'History', q: 'The Nigerian Civil War was fought between:', o: ['1966–1968', '1967–1970', '1970–1973', '1964–1966'], a: 1 },
  { s: 'History', q: 'The Sokoto Caliphate was founded by:', o: ['Usman dan Fodio', 'Muhammad Bello', 'Aliyu Bida', 'Attahiru Ahmadu'], a: 0 },
  { s: 'History', q: 'The first political party in Nigeria was the:', o: ['NCNC', 'AG', 'NPC', 'UMBC'], a: 0 },
  { s: 'History', q: 'Nigeria\'s capital moved from Lagos to Abuja in:', o: ['1979', '1986', '1991', '1999'], a: 2 },
  { s: 'History', q: 'The military coup that ended the First Republic occurred in:', o: ['1964', '1966', '1967', '1975'], a: 1 },
  { s: 'History', q: 'Nigeria gained independence from:', o: ['France', 'Britain', 'Portugal', 'Belgium'], a: 1 },
  { s: 'History', q: 'The nationalist popularly known as "Zik of West Africa" was:', o: ['Ahmadu Bello', 'Obafemi Awolowo', 'Nnamdi Azikiwe', 'Herbert Macaulay'], a: 2 },
  { s: 'History', q: 'The Action Group (AG) was founded in:', o: ['1944', '1951', '1960', '1966'], a: 1 },
  { s: 'History', q: 'The ancient city of Benin, famous for its bronze works, is in present-day:', o: ['Ghana', 'Benin Republic', 'Nigeria', 'Cameroon'], a: 2 },
  { s: 'History', q: 'The first military coup in Nigeria took place in:', o: ['1964', '1965', '1966', '1967'], a: 2 },
  { s: 'History', q: 'The Lancaster House Conference that paved the way for Nigeria\'s independence was held in:', o: ['Lagos', 'London', 'Accra', 'Abuja'], a: 1 },
  { s: 'History', q: 'The leader of the secessionist Republic of Biafra was:', o: ['Yakubu Gowon', 'Odumegwu Ojukwu', 'Olusegun Obasanjo', 'Murtala Mohammed'], a: 1 },
  { s: 'History', q: 'The Maitatsine uprising, which began in Kano, took place in:', o: ['1966', '1973', '1980', '1985'], a: 2 },
  { s: 'History', q: 'Nigeria replaced the British pound with the naira in:', o: ['1960', '1966', '1973', '1979'], a: 2 },
  { s: 'History', q: 'The Nok culture of ancient Nigeria is best known for its:', o: ['bronze heads', 'stone walls', 'terracotta sculptures', 'rock paintings'], a: 2 },

  /* --- Commerce --- */
  { s: 'Commerce', q: 'A written promise to pay a sum of money at a future date is a:', o: ['cheque', 'promissory note', 'invoice', 'bill of lading'], a: 1 },
  { s: 'Commerce', q: 'Insurance of goods against loss while being carried by sea is:', o: ['fire insurance', 'marine insurance', 'life insurance', 'burglary insurance'], a: 1 },
  { s: 'Commerce', q: 'A person who sells goods on behalf of another for a commission is an:', o: ['agent', 'broker', 'merchant', 'wholesaler'], a: 0 },
  { s: 'Commerce', q: 'A market with very few sellers is an:', o: ['perfect competition', 'oligopoly', 'monopoly', 'monopsony'], a: 1 },
  { s: 'Commerce', q: 'The Nigerian Stock Exchange is now known as the:', o: ['NSE', 'NGX', 'CBN', 'SEC'], a: 1 },
  { s: 'Commerce', q: 'Buying and selling of goods without changing their form is:', o: ['production', 'trade', 'distribution', 'retailing'], a: 1 },
  { s: 'Commerce', q: 'A document that shows the description and price of goods sent is the:', o: ['invoice', 'receipt', 'order', 'quotation'], a: 0 },
  { s: 'Commerce', q: 'The reward for an entrepreneur is:', o: ['wage', 'rent', 'profit', 'interest'], a: 2 },
  { s: 'Commerce', q: 'The document issued by a shipping company that serves as a receipt for goods carried by sea is the:', o: ['invoice', 'bill of lading', 'receipt', 'prospectus'], a: 1 },
  { s: 'Commerce', q: 'A person who brings buyers and sellers together without taking possession of the goods is a:', o: ['broker', 'wholesaler', 'retailer', 'manufacturer'], a: 0 },
  { s: 'Commerce', q: 'The exchange of goods for goods without using money is called:', o: ['retailing', 'barter', 'commission agency', 'hawking'], a: 1 },
  { s: 'Commerce', q: 'A cheque that bears a date later than the date of presentation for payment is a:', o: ['stale cheque', 'crossed cheque', 'post-dated cheque', 'bearer cheque'], a: 2 },
  { s: 'Commerce', q: 'New issues of shares are bought and sold for the first time in the:', o: ['secondary market', 'primary market', 'money market', 'discount market'], a: 1 },
  { s: 'Commerce', q: 'A document that shows how many shares an individual holds in a company is the:', o: ['prospectus', 'share certificate', 'memorandum of association', 'income statement'], a: 1 },
  { s: 'Commerce', q: 'The collection of duties on imported goods is the responsibility of the:', o: ['Central Bank', 'Nigeria Customs Service', 'SEC', 'NDIC'], a: 1 },
  { s: 'Commerce', q: 'Trade discount is normally granted to:', o: ['wholesalers and retailers', 'bank customers', 'government', 'insurance policy holders'], a: 0 },
  { s: 'Commerce', q: 'The instrument used to withdraw money from a bank account is a:', o: ['cheque', 'invoice', 'receipt', 'order'], a: 0 },
  { s: 'Commerce', q: 'Which of these is a function of a warehouse?', o: ['issuing cheques', 'storing goods', 'printing money', 'insuring lives'], a: 1 },

  /* --- Further Mathematics --- */
  { s: 'Further Mathematics', q: 'Find the determinant of the matrix [[2, 3], [1, 4]].', o: ['5', '7', '11', '−5'], a: 0 },
  { s: 'Further Mathematics', q: 'A matrix has 2 rows and 3 columns. Its order is:', o: ['2 × 3', '3 × 2', '3 × 3', '6 × 1'], a: 0 },
  { s: 'Further Mathematics', q: 'Differentiate y = x³ with respect to x.', o: ['x²', '3x²', '3x', '2x'], a: 1 },
  { s: 'Further Mathematics', q: 'Evaluate ∫ 2x dx.', o: ['x² + C', '2x² + C', 'x²/2 + C', '2 + C'], a: 0 },
  { s: 'Further Mathematics', q: 'Find the 5th term of the arithmetic progression 2, 5, 8, ...', o: ['14', '17', '11', '12'], a: 0 },
  { s: 'Further Mathematics', q: 'Find the sum to infinity of the geometric progression with first term 6 and common ratio 1/2.', o: ['18', '12', '6', '24'], a: 1 },
  { s: 'Further Mathematics', q: 'Find the coefficient of x² in the expansion of (1 + x)⁴.', o: ['4', '6', '1', '16'], a: 1 },
  { s: 'Further Mathematics', q: 'The angle between the unit vectors i and j is:', o: ['0°', '45°', '90°', '180°'], a: 2 },
  { s: 'Further Mathematics', q: 'Find the magnitude of the vector 3i + 4j.', o: ['5', '7', '12', '25'], a: 0 },
  { s: 'Further Mathematics', q: 'The mean of 2, 4, 6, 8 and 10 is:', o: ['5', '6', '7', '8'], a: 1 },
  { s: 'Further Mathematics', q: 'The standard deviation of the values 2, 4, 6, 8 and 10 is:', o: ['2.83', '3.16', '4.00', '2.00'], a: 0 },
  { s: 'Further Mathematics', q: 'The mode of 3, 5, 3, 7, 5 and 3 is:', o: ['5', '7', '3', '4'], a: 2 },

  /* --- Agricultural Science --- */
  { s: 'Agricultural Science', q: 'The largest of the soil particles is:', o: ['clay', 'silt', 'sand', 'loam'], a: 2 },
  { s: 'Agricultural Science', q: 'The soil type with the highest water-holding capacity is:', o: ['sand', 'clay', 'gravel', 'loamy sand'], a: 1 },
  { s: 'Agricultural Science', q: 'The type of root system found in maize is the:', o: ['tap root', 'fibrous root', 'tuberous root', 'carnivorous root'], a: 1 },
  { s: 'Agricultural Science', q: 'The cutting down and clearing of forests is called:', o: ['afforestation', 'reforestation', 'deforestation', 'erosion control'], a: 2 },
  { s: 'Agricultural Science', q: 'Which of these is a leguminous crop?', o: ['Maize', 'Groundnut', 'Cassava', 'Yam'], a: 1 },
  { s: 'Agricultural Science', q: 'The rearing of fish is called:', o: ['apiculture', 'sericulture', 'pisciculture', 'arboriculture'], a: 2 },
  { s: 'Agricultural Science', q: 'Manure is best described as:', o: ['a chemical salt', 'organic matter from plant or animal sources', 'a synthetic fertiliser', 'an insecticide'], a: 1 },
  { s: 'Agricultural Science', q: 'The common insect pest that attacks stored grains in Nigeria is the:', o: ['weevil', 'tsetse fly', 'aphid', 'nematode'], a: 0 },
  { s: 'Agricultural Science', q: 'Irrigation may be defined as the:', o: ['natural supply of water by rainfall', 'artificial application of water to crops', 'drainage of excess water from farmland', 'flooding of farmland before planting'], a: 1 },
  { s: 'Agricultural Science', q: 'Which of these is NOT required for photosynthesis in crops?', o: ['Light', 'Chlorophyll', 'Carbon dioxide', 'Oxygen'], a: 3 },

  /* --- Principles of Accounts --- */
  { s: 'Principles of Accounts', q: 'The bookkeeping system in which every transaction has a debit and a credit entry is called:', o: ['single entry', 'double entry', 'cost accounting', 'incomplete records'], a: 1 },
  { s: 'Principles of Accounts', q: 'The book of original entry used to record credit purchases is the:', o: ['sales journal', 'purchases journal', 'cash book', 'general journal'], a: 1 },
  { s: 'Principles of Accounts', q: 'The main purpose of a trial balance is to:', o: ['ascertain the net profit of a business', 'check the arithmetical accuracy of ledger accounts', 'determine the market value of assets', 'prepare the cash flow statement'], a: 1 },
  { s: 'Principles of Accounts', q: 'The accounting equation is:', o: ['Assets = Capital + Liabilities', 'Assets = Liabilities − Capital', 'Capital = Assets + Liabilities', 'Assets = Revenue − Liabilities'], a: 0 },
  { s: 'Principles of Accounts', q: 'Depreciation of an asset is:', o: ['a sudden loss of stock', 'the gradual decrease in the value of a fixed asset', 'an increase in the value of an asset', 'a payment made to creditors'], a: 1 },
  { s: 'Principles of Accounts', q: 'The method of depreciation that charges the same amount every year is the:', o: ['reducing balance method', 'straight-line method', 'annuity method', 'revaluation method'], a: 1 },
  { s: 'Principles of Accounts', q: 'An amount owed to the business by a customer is described as a:', o: ['creditor', 'debtor', 'loan', 'discount'], a: 1 },
  { s: 'Principles of Accounts', q: 'The cash book is best described as:', o: ['a ledger account', 'a book of original entry', 'a final account', 'a trial balance'], a: 1 },
  { s: 'Principles of Accounts', q: 'Value Added Tax (VAT) is:', o: ['a direct tax on personal income', 'an indirect tax on goods and services', 'a tax on exports only', 'a tax on company profits'], a: 1 },
  { s: 'Principles of Accounts', q: 'The balance sheet of a business shows its:', o: ['performance over a period of time', 'financial position at a particular date', 'cash received during the week', 'sales made on credit'], a: 1 }
];
