/* Worked solutions for Physics — keyed by the exact question text. */
window.SOLUTIONS = window.SOLUTIONS || {};
window.SOLUTIONS['Physics'] = {
  'The SI unit of force is the:': { t: 'Units and measurement', e: 'By Newton second law F = ma, so 1 N = 1 kg m/s^2 and the SI unit of force is the newton.' },
  'A body of mass 5 kg accelerates at 2 m/s^2. The force applied is:': { t: 'Units and measurement', e: 'F = ma = 5 x 2 = 10 N.' },
  'Which of the following is a base quantity in the SI system?': { t: 'Units and measurement', e: 'Length is one of the seven SI base quantities, while force, velocity and energy are all derived quantities.' },
  'The dimension of work is:': { t: 'Units and measurement', e: 'Work = force x distance = MLT^-2 x L, which gives ML^2T^-2.' },
  'The SI unit of pressure is the:': { t: 'Units and measurement', e: 'Pressure = force/area, so its SI unit is N/m^2 (the pascal).' },
  'Correct 4.5678 to three significant figures:': { t: 'Units and measurement', e: 'The fourth significant figure is 7, so the third figure is rounded up and 4.5678 becomes 4.57.' },
  'Find the circumference of a circle of radius 7 cm. (Take pi = 22/7)': { t: 'Units and measurement', e: 'C = 2 pi r = 2 x 22/7 x 7 = 44 cm.' },
  'A vernier caliper has 10 vernier scale divisions spanning 9 main scale divisions of 1 mm each. Its least count is:': { t: 'Units and measurement', e: 'One vernier division = 9/10 mm = 0.9 mm, so the least count = 1 mm - 0.9 mm = 0.1 mm.' },
  'The dimension of velocity is:': { t: 'Units and measurement', e: 'Velocity = displacement/time = L/T, so its dimension is LT^-1.' },
  'Which of the following is a scalar quantity?': { t: 'Units and measurement', e: 'Speed has magnitude only, whereas momentum, force and acceleration also need a direction, so they are vectors.' },
  'The derived SI unit of frequency is the:': { t: 'Units and measurement', e: 'Frequency counts cycles per second, so its unit is the hertz (Hz).' },
  'One horsepower is equivalent to:': { t: 'Units and measurement', e: 'One mechanical horsepower is defined as approximately 746 W.' },
  'The number of significant figures in 0.00450 is:': { t: 'Units and measurement', e: 'Leading zeros never count, so the significant figures are 4, 5 and the final zero, giving 3.' },
  'A speed of 72 km/h is equal to:': { t: 'Units and measurement', e: 'Divide by 3.6 to convert km/h to m/s: 72/3.6 = 20 m/s.' },
  'A car starts from rest and reaches a speed of 20 m/s in 5 s. Its acceleration is:': { t: 'Motion and forces', e: 'a = (v - u)/t = (20 - 0)/5 = 4 m/s^2.' },
  'A stone falls freely from rest. The distance it covers in 2 s (take g = 10 m/s^2) is:': { t: 'Motion and forces', e: 's = 1/2 gt^2 = 1/2 x 10 x 2^2 = 1/2 x 10 x 4 = 20 m.' },
  'A body falls freely from rest. Its velocity after 3 s (take g = 10 m/s^2) is:': { t: 'Motion and forces', e: 'v = gt = 10 x 3 = 30 m/s.' },
  'A runner covers 100 m in 10 s and another 100 m in 20 s. The average speed for the whole journey is:': { t: 'Motion and forces', e: 'Average speed = total distance/total time = 200/(10 + 20) = 200/30 = 6.7 m/s.' },
  'A projectile is fired at 20 m/s at an angle of 30 degrees to the horizontal. Its range on level ground (take g = 10 m/s^2) is:': { t: 'Motion and forces', e: 'R = u^2 sin(2 x 30 degrees)/g = 400 x sin 60 degrees/10 = 400 x 0.866/10 = 34.6 m.' },
  'A ball is projected at 30 m/s at 30 degrees to the horizontal. Its time of flight (take g = 10 m/s^2) is:': { t: 'Motion and forces', e: 'T = 2u sin(theta)/g = 2 x 30 x sin 30 degrees/10 = 2 x 30 x 0.5/10 = 3 s.' },
  'Which of the following is a vector quantity?': { t: 'Motion and forces', e: 'Displacement has both magnitude and direction, while speed, mass and temperature have magnitude only.' },
  'A stone is thrown vertically upward at 30 m/s. The maximum height reached (take g = 10 m/s^2) is:': { t: 'Motion and forces', e: 'At the top the velocity is zero, so h = u^2/(2g) = 30^2/20 = 900/20 = 45 m.' },
  'The slope of a distance-time graph represents:': { t: 'Motion and forces', e: 'Slope = distance travelled/time taken, which is the speed of the body.' },
  'The area under a velocity-time graph represents:': { t: 'Motion and forces', e: 'Area = velocity x time, and distance travelled per unit time multiplied by time gives the displacement.' },
  'A body has an initial velocity of 10 m/s and decelerates uniformly at 2 m/s^2. Its velocity after 5 s is:': { t: 'Motion and forces', e: 'v = u - at = 10 - 2 x 5 = 10 - 10 = 0 m/s, so the body just comes to rest.' },
  'A body starts from rest and accelerates at 2 m/s^2 for 4 s. The distance covered is:': { t: 'Motion and forces', e: 's = 1/2 at^2 = 1/2 x 2 x 4^2 = 16 m.' },
  'A body of mass 5 kg rests on a rough horizontal surface. If the coefficient of friction is 0.4 and g = 10 m/s^2, the minimum force needed to just move it is:': { t: 'Motion and forces', e: 'The pull must just overcome limiting friction, so F = mu mg = 0.4 x 5 x 10 = 20 N.' },
  'The resultant of two perpendicular forces of 3 N and 4 N is:': { t: 'Motion and forces', e: 'R = sqrt(3^2 + 4^2) = sqrt(9 + 16) = sqrt(25) = 5 N.' },
  'A force of 10 N is applied at a distance of 0.5 m from a pivot. The moment of the force about the pivot is:': { t: 'Motion and forces', e: 'Moment = force x perpendicular distance = 10 x 0.5 = 5 Nm.' },
  'The tendency of a body to remain at rest or to continue in uniform motion unless acted on by an external force is called:': { t: 'Motion and forces', e: 'This resistance to any change in the state of motion of a body is called inertia.' },
  'The impulse of a force has the unit:': { t: 'Motion and forces', e: 'Impulse = force x time, so its unit is N s, which is the same as kg m/s.' },
  'The momentum of a body of mass 4 kg moving at 6 m/s is:': { t: 'Motion and forces', e: 'p = mv = 4 x 6 = 24 kg m/s.' },
  'A car of mass 1500 kg moving at 20 m/s is brought to rest in 10 s. The magnitude of the average braking force is:': { t: 'Motion and forces', e: 'F = change in momentum/time = (1500 x 20 - 0)/10 = 30000/10 = 3000 N.' },
  'A ball of mass 0.5 kg moving at 10 m/s is brought to rest in 0.25 s. The average force acting on it is:': { t: 'Motion and forces', e: 'F = mu/t = (0.5 x 10)/0.25 = 5/0.25 = 20 N.' },
  'The work done by a force of 25 N moving through a distance of 4 m is:': { t: 'Work energy and power', e: 'W = Fs = 25 x 4 = 100 J.' },
  'The kinetic energy of a body of mass 2 kg moving at 3 m/s is:': { t: 'Work energy and power', e: 'KE = 1/2 mv^2 = 1/2 x 2 x 3^2 = 9 J.' },
  'The gravitational potential energy of a body of mass 10 kg at a height of 5 m (take g = 10 m/s^2) is:': { t: 'Work energy and power', e: 'PE = mgh = 10 x 10 x 5 = 500 J.' },
  'An engine lifts a load of 500 N through a height of 3 m in 10 s. The power developed is:': { t: 'Work energy and power', e: 'Work done = 500 x 3 = 1500 J, so power = 1500/10 = 150 W.' },
  'A machine uses 500 J of energy and does 400 J of useful work. Its efficiency is:': { t: 'Work energy and power', e: 'Efficiency = useful output/input = 400/500 = 0.8, which is 80%.' },
  'A spring of force constant 200 N/m is stretched by 0.15 m. The energy stored in it is:': { t: 'Work energy and power', e: 'E = 1/2 kx^2 = 1/2 x 200 x 0.15^2 = 100 x 0.0225 = 2.25 J.' },
  'The SI unit of power is the:': { t: 'Work energy and power', e: 'Power = energy/time, so its SI unit is the watt (W), and 1 W = 1 J/s.' },
  'A machine has a velocity ratio of 5 and an efficiency of 80%. Its mechanical advantage is:': { t: 'Work energy and power', e: 'Efficiency = MA/VR, so MA = efficiency x VR = 0.80 x 5 = 4.' },
  'Which of the following forces is a conservative force?': { t: 'Work energy and power', e: 'Gravity is conservative because the work done depends only on the start and end positions, unlike friction or air resistance.' },
  'In an electric lamp, electrical energy is converted mainly into:': { t: 'Work energy and power', e: 'The lamp filament converts electrical energy mainly into heat energy, with some of it appearing as light.' },
  'A force of 10 N acts perpendicular to the direction of a displacement of 2 m. The work done by the force is:': { t: 'Work energy and power', e: 'W = Fs cos(theta) with theta = 90 degrees, and cos 90 degrees = 0, so W = 10 x 2 x 0 = 0 J.' },
  'The SI unit of temperature is the:': { t: 'Heat and thermodynamics', e: 'The kelvin (K) is the SI base unit of temperature; Celsius and Fahrenheit are not SI units.' },
  'A temperature of 27 degrees C expressed in kelvin is:': { t: 'Heat and thermodynamics', e: 'K = degrees C + 273 = 27 + 273 = 300 K.' },
  'A temperature of 300 K expressed in degrees Celsius is:': { t: 'Heat and thermodynamics', e: 'degrees C = K - 273 = 300 - 273 = 27 degrees C.' },
  'The quantity of heat needed to raise the temperature of 2 kg of water through 10 degrees C (specific heat capacity 4200 J/kg K) is:': { t: 'Heat and thermodynamics', e: 'Q = mc delta T = 2 x 4200 x 10 = 84000 J.' },
  'The energy required to melt 2 kg of ice completely (specific latent heat of fusion 3.36 x 10^5 J/kg) is:': { t: 'Heat and thermodynamics', e: 'Q = mL = 2 x 3.36 x 10^5 = 6.72 x 10^5 J, since melting happens at constant temperature.' },
  'The temperature of a body is a measure of the:': { t: 'Heat and thermodynamics', e: 'Temperature measures the average kinetic energy of the molecules, not their total energy.' },
  'Which of the following expands the most when heated through the same temperature change?': { t: 'Heat and thermodynamics', e: 'Gases have by far the largest expansion coefficients, so for the same temperature rise a gas expands much more than a liquid or a solid.' },
  'A bimetallic strip bends when heated because the two metals have different:': { t: 'Heat and thermodynamics', e: 'The two metals expand by different amounts because their coefficients of linear expansion differ, so the bonded strip curves.' },
  'A vacuum flask reduces heat loss by preventing:': { t: 'Heat and thermodynamics', e: 'The vacuum stops conduction and convection by removing the air, while the silvered walls reflect radiation back inside.' },
  'The unit of heat capacity is:': { t: 'Heat and thermodynamics', e: 'Heat capacity = heat supplied/temperature rise, so its unit is J/K.' },
  'The specific heat capacity of a substance is the heat required to raise the temperature of:': { t: 'Heat and thermodynamics', e: 'By definition it is the heat needed to raise 1 kg of the substance by 1 degree C (or 1 K).' },
  'Which of the following is the best conductor of heat?': { t: 'Heat and thermodynamics', e: 'Copper is a metal with free electrons that transfer energy rapidly, so it conducts far better than glass, rubber or wood.' },
  'A steel rod 2.0 m long is heated through 50 K. If its coefficient of linear expansion is 1.2 x 10^-5 K^-1, the increase in length is:': { t: 'Heat and thermodynamics', e: 'delta L = L x alpha x delta T = 2.0 x 1.2 x 10^-5 x 50 = 1.2 x 10^-3 m = 1.2 mm.' },
  'A gas at constant volume has a pressure of 100 kPa at 27 degrees C. Its pressure at 127 degrees C is:': { t: 'Heat and thermodynamics', e: 'At constant volume P/T is constant. T1 = 27 + 273 = 300 K and T2 = 127 + 273 = 400 K, so P2 = 100 x 400/300 = 133.3 kPa.' },
  'A gas occupies 0.50 m^3 at a pressure of 200 kPa. Its volume at 400 kPa, temperature kept constant, is:': { t: 'Heat and thermodynamics', e: 'Boyle law P1V1 = P2V2 gives V2 = 200 x 0.50/400 = 0.25 m^3.' },
  'A gas occupies 0.30 m^3 at 27 degrees C at constant pressure. Its volume at 127 degrees C is:': { t: 'Heat and thermodynamics', e: 'Charles law V/T is constant: T1 = 300 K, T2 = 400 K, so V2 = 0.30 x 400/300 = 0.40 m^3.' },
  'A wave has a frequency of 50 Hz and a wavelength of 4 m. Its speed is:': { t: 'Waves and sound', e: 'Wave speed v = f x lambda = 50 x 4 = 200 m/s.' },
  'The wavelength of a sound wave of frequency 170 Hz travelling at 340 m/s is:': { t: 'Waves and sound', e: 'lambda = v/f = 340/170 = 2 m.' },
  'A wave completes one vibration in 0.05 s. Its frequency is:': { t: 'Waves and sound', e: 'The period is 0.05 s, so f = 1/T = 1/0.05 = 20 Hz.' },
  'Sound waves in air are:': { t: 'Waves and sound', e: 'The air molecules oscillate parallel to the direction of travel, producing compressions and rarefactions, so sound in air is longitudinal.' },
  'The wavelength of a wave is the distance between:': { t: 'Waves and sound', e: 'By definition the wavelength is the distance between two consecutive points in phase, for example from one crest to the next crest.' },
  'Which of the following waves does not require a medium for its propagation?': { t: 'Waves and sound', e: 'Light is an electromagnetic wave and travels through empty space, whereas sound, water and string waves need a material medium.' },
  'The speed of light in vacuum is:': { t: 'Waves and sound', e: 'Light in vacuum travels at about 3 x 10^8 m/s.' },
  'When a wave passes from air into glass, its frequency:': { t: 'Waves and sound', e: 'Frequency is fixed by the source and does not change on refraction, even though the speed and wavelength both decrease.' },
  'A wave travels at 200 m/s and has a wavelength of 5 m. Its period is:': { t: 'Waves and sound', e: 'f = v/lambda = 200/5 = 40 Hz, so T = 1/f = 1/40 = 0.025 s.' },
  'The amplitude of a sound wave determines its:': { t: 'Waves and sound', e: 'Greater amplitude carries more energy, so the sound is louder; pitch is set by frequency instead.' },
  'The number of complete waves passing a fixed point per second is the:': { t: 'Waves and sound', e: 'That is the definition of frequency, and it is measured in hertz.' },
  'The approximate range of frequencies audible to the human ear is:': { t: 'Waves and sound', e: 'A healthy human ear responds to frequencies from about 20 Hz up to about 20,000 Hz.' },
  'A sound of frequency 25,000 Hz is described as:': { t: 'Waves and sound', e: 'It lies above the 20,000 Hz upper limit of hearing, so it is ultrasonic.' },
  'According to the principle of superposition, the resultant displacement of two waves meeting at a point is the:': { t: 'Waves and sound', e: 'Superposition states that the resultant displacement is the algebraic sum of the separate displacements at that point.' },
  'The approximate speed of sound in air at room temperature is:': { t: 'Waves and sound', e: 'Sound in air near room temperature travels at about 340 m/s.' },
  'An observer hears an echo 2 s after shouting at a cliff. The distance of the cliff (speed of sound = 340 m/s) is:': { t: 'Waves and sound', e: 'The sound travels to the cliff and back in 2 s, so the distance d = 340 x 2/2 = 340 m.' },
  'The pitch of a musical note depends mainly on the sound wave:': { t: 'Waves and sound', e: 'Pitch is determined by frequency: the higher the frequency, the higher the pitch.' },
  'Sound waves cannot travel through:': { t: 'Waves and sound', e: 'Sound needs particles to vibrate, so it cannot pass through a vacuum.' },
  'Sound travels fastest in:': { t: 'Waves and sound', e: 'In solids the particles are closely packed and transmit vibrations quickly, so sound travels faster in steel than in water or air.' },
  'SONAR makes use of:': { t: 'Waves and sound', e: 'SONAR emits ultrasonic pulses underwater and times the returning echo to find distances and depths.' },
  'The loudness of a sound depends mainly on its:': { t: 'Waves and sound', e: 'Loudness is governed by the amplitude (and intensity) of the wave, not by its frequency.' },
  'Resonance occurs when the frequency of the driving force equals the:': { t: 'Waves and sound', e: 'When the driving frequency matches the natural frequency of the body, the amplitude of vibration builds up; this is resonance.' },
  'When sound travels from air into water, its speed:': { t: 'Waves and sound', e: 'Water is denser and more elastic than air, so sound travels faster in water than in air.' },
  'Two tuning forks vibrate at 250 Hz and 252 Hz. The beat frequency heard is:': { t: 'Waves and sound', e: 'Beat frequency = |252 - 250| = 2 Hz.' },
  'The SI unit of frequency is the:': { t: 'Waves and sound', e: 'Frequency is measured in hertz (Hz), where 1 Hz means one complete vibration per second.' },
  'The time taken for one complete vibration of a wave is called its:': { t: 'Waves and sound', e: 'The time for one full vibration is the period T, which is the reciprocal of the frequency.' },
  'The intensity of sound obeys the inverse square law. When the distance from the source is doubled, the intensity becomes:': { t: 'Waves and sound', e: 'Intensity is proportional to 1/r^2, so doubling r reduces it by a factor of 2^2 = 4, leaving one quarter.' },
  'Sound produced by irregular and random vibrations is called:': { t: 'Waves and sound', e: 'Random vibrations give a jumble of unwanted frequencies, which is noise rather than music.' },
  'The repetition of sound caused by reflection from a hard surface is called an:': { t: 'Waves and sound', e: 'When sound reflects off a hard surface and reaches the listener again, the repeated sound is heard as an echo.' },
  'The bending of light as it passes from one medium into another is called:': { t: 'Optics', e: 'A change of speed at the boundary makes the light change direction, and this bending is called refraction.' },
  'The refractive index of a medium is 1.5. If the speed of light in vacuum is 3 x 10^8 m/s, its speed in the medium is:': { t: 'Optics', e: 'n = c/v, so v = c/n = 3 x 10^8/1.5 = 2.0 x 10^8 m/s.' },
  'The law of reflection states that the angle of incidence is equal to the:': { t: 'Optics', e: 'The law of reflection gives angle of incidence = angle of reflection, both measured from the normal.' },
  'Light travelling from an optically rarer medium into a denser medium bends:': { t: 'Optics', e: 'The light slows down on entering the denser medium, so it bends towards the normal.' },
  'The critical angle for a medium of refractive index 1.414 is approximately:': { t: 'Optics', e: 'sin C = 1/n = 1/1.414 = 0.707, and sin 45 degrees = 0.707, so C = 45 degrees.' },
  'Total internal reflection can occur when light travels:': { t: 'Optics', e: 'It must go from a denser to a rarer medium and strike the boundary at an angle greater than the critical angle, so all the light reflects back.' },
  'A converging lens is:': { t: 'Optics', e: 'A convex lens is thicker in the middle and brings parallel rays towards a focus, so it converges light.' },
  'A concave mirror of focal length 10 cm has an object placed 30 cm in front of it. The image is formed:': { t: 'Optics', e: '1/v + 1/u = 1/f gives 1/v = 1/10 - 1/30 = (3 - 1)/30 = 2/30, so v = 15 cm, a real image 15 cm in front of the mirror.' },
  'An object 4 cm tall forms an image 12 cm tall. The magnification produced is:': { t: 'Optics', e: 'm = image height/object height = 12/4 = 3.' },
  'A convex lens of focal length 20 cm has a power of:': { t: 'Optics', e: 'P = 1/f with f in metres = 1/0.20 = 5 D.' },
  'Short sightedness (myopia) is corrected using a:': { t: 'Optics', e: 'A short-sighted eye focuses in front of the retina, so a concave lens diverges the rays and moves the image back onto the retina.' },
  'Long sightedness (hypermetropia) is corrected using a:': { t: 'Optics', e: 'A long-sighted eye cannot focus near objects, so a convex lens adds convergence and brings the image onto the retina.' },
  'The near point of a normal human eye is at a distance of:': { t: 'Optics', e: 'A normal eye can see an object clearly only when it is at least about 25 cm away.' },
  'The splitting of white light into its colours by a prism is called:': { t: 'Optics', e: 'Each colour is refracted by a different amount, so the prism spreads white light into a spectrum; this is dispersion.' },
  'Which colour of light is deviated least by a glass prism?': { t: 'Optics', e: 'Red light has the longest wavelength and is slowed the least by glass, so it is deviated least.' },
  'A photographic camera uses a:': { t: 'Optics', e: 'A camera uses a convex (converging) lens to form a real, inverted image on the film or sensor.' },
  'A convex lens of focal length 15 cm forms an image of an object placed 30 cm from the lens. The image distance is:': { t: 'Optics', e: '1/v = 1/f - 1/u = 1/15 - 1/30 = (2 - 1)/30 = 1/30, so v = 30 cm.' },
  'Two lenses of powers 2 D and 3 D are placed in contact. The power of the combination is:': { t: 'Optics', e: 'Powers of thin lenses in contact simply add: P = 2 + 3 = 5 D.' },
  'Diffraction of a wave is most pronounced when the size of the slit is comparable with the wave:': { t: 'Optics', e: 'Strong spreading (diffraction) occurs when the opening is about the same size as the wavelength.' },
  'The image formed by a plane mirror is:': { t: 'Optics', e: 'A plane mirror always gives a virtual, erect image the same size as the object, standing behind the mirror.' },
  'The power of a lens of focal length 0.25 m is:': { t: 'Optics', e: 'P = 1/f = 1/0.25 = 4 D.' },
  'Which of the following travels at the speed of light in vacuum?': { t: 'Optics', e: 'Radio waves are electromagnetic waves, and all electromagnetic waves travel at 3 x 10^8 m/s in vacuum.' },
  'Light may be regarded as a:': { t: 'Optics', e: 'Its oscillations are perpendicular to the direction of travel and it needs no medium, so light is a transverse electromagnetic wave.' },
  'A real image can be formed by a:': { t: 'Optics', e: 'A real image is formed where rays actually meet, which a converging convex lens or a concave mirror can produce; a plane mirror cannot.' },
  'Outside a bar magnet, the magnetic field lines run from the:': { t: 'Electricity and magnetism', e: 'Field lines leave the north pole and enter the south pole outside the magnet.' },
  'Which instrument is used to detect a very small electric current?': { t: 'Electricity and magnetism', e: 'A galvanometer is a sensitive instrument built to detect and show small currents.' },
  'Fleming left-hand rule is used to determine the direction of force in an:': { t: 'Electricity and magnetism', e: 'The left-hand rule gives the force on a current-carrying conductor in a field, which is the working principle of the electric motor.' },
  'Fleming right-hand rule is used in a:': { t: 'Electricity and magnetism', e: 'The right-hand rule gives the direction of the induced current when a conductor cuts magnetic field lines, as happens in a generator.' },
  'According to Faraday law of electromagnetic induction, the induced EMF is proportional to the rate of change of:': { t: 'Electricity and magnetism', e: 'Faraday law states that the induced EMF equals the rate of change of magnetic flux linkage.' },
  'A conductor of length 0.2 m carrying a current of 4 A is placed at right angles to a uniform field of flux density 0.5 T. The force on it is:': { t: 'Electricity and magnetism', e: 'F = BIL = 0.5 x 4 x 0.2 = 0.4 N.' },
  'Soft iron is used for the core of an electromagnet because it:': { t: 'Electricity and magnetism', e: 'Soft iron is easily magnetised when the current flows and loses its magnetism as soon as the current stops.' },
  'A dynamo converts:': { t: 'Electricity and magnetism', e: 'A dynamo spins a coil in a magnetic field to drive a current, converting mechanical energy into electrical energy.' },
  'The magnetic field inside a long solenoid carrying a steady current is:': { t: 'Electricity and magnetism', e: 'Inside an ideal long solenoid the field is uniform in strength and parallel to the axis.' },
  'The SI unit of electrical resistance is the:': { t: 'Electricity and magnetism', e: 'From R = V/I, resistance is measured in ohms (Ohm).' },
  'A current of 2 A flows through a resistor of 5 Ohm. The potential difference across the resistor is:': { t: 'Electricity and magnetism', e: 'V = IR = 2 x 5 = 10 V.' },
  'The current flowing through a 4 Ohm resistor connected to a 12 V supply is:': { t: 'Electricity and magnetism', e: 'I = V/R = 12/4 = 3 A.' },
  'A potential difference of 6 V produces a current of 0.5 A in a wire. The resistance of the wire is:': { t: 'Electricity and magnetism', e: 'R = V/I = 6/0.5 = 12 Ohm.' },
  'The effective resistance of a 2 Ohm resistor connected in parallel with a 3 Ohm resistor is:': { t: 'Electricity and magnetism', e: '1/R = 1/2 + 1/3 = 5/6, so R = 6/5 = 1.2 Ohm.' },
  'Resistors of 2 Ohm, 3 Ohm and 5 Ohm are connected in series. The total resistance is:': { t: 'Electricity and magnetism', e: 'Resistances in series simply add: 2 + 3 + 5 = 10 Ohm.' },
  'Three resistors each of 6 Ohm are connected in parallel. Their effective resistance is:': { t: 'Electricity and magnetism', e: 'Equal resistors in parallel give R/n, so R = 6/3 = 2 Ohm.' },
  'An appliance operates at 10 V and draws a current of 2 A. The power it consumes is:': { t: 'Electricity and magnetism', e: 'P = VI = 10 x 2 = 20 W.' },
  'A current of 3 A flows through a 2 Ohm resistor. The power dissipated as heat is:': { t: 'Electricity and magnetism', e: 'P = I^2 R = 3^2 x 2 = 9 x 2 = 18 W.' },
  'A 60 W lamp is used for 2 hours. The energy it consumes is:': { t: 'Electricity and magnetism', e: 'E = Pt = 60 x 2 = 120 Wh, and 120 Wh/1000 = 0.12 kWh.' },
  'Household appliances such as lamps and sockets are connected in:': { t: 'Electricity and magnetism', e: 'In parallel each appliance gets the full supply voltage and can be switched off without stopping the others.' },
  'The main function of a fuse in an electric circuit is to:': { t: 'Electricity and magnetism', e: 'A fuse melts and breaks the circuit when the current rises above a safe value, protecting the wiring.' },
  'A semiconductor commonly used in the manufacture of transistors is:': { t: 'Electronics', e: 'Silicon is a semiconductor whose conductivity can be controlled by doping, so it is used to make transistors.' },
  'A semiconductor diode conducts electric current:': { t: 'Electronics', e: 'A diode has a p-n junction that passes current easily in the forward direction only.' },
  'An n-type semiconductor is produced by doping pure silicon with a:': { t: 'Electronics', e: 'A pentavalent impurity such as arsenic donates spare electrons, so electrons become the majority carriers and the material is n-type.' },
  'The majority charge carriers in a p-type semiconductor are:': { t: 'Electronics', e: 'Doping with a trivalent impurity creates vacancies (holes), and these holes are the majority charge carriers in p-type silicon.' },
  'A transistor can be used as a:': { t: 'Electronics', e: 'A transistor can amplify a weak signal or be switched on and off, so it works as an amplifier or a switch.' },
  'The output of an OR logic gate is 1 when:': { t: 'Electronics', e: 'The OR gate gives output 1 whenever at least one of its inputs is 1.' },
  'The output of an AND logic gate is 1 only when:': { t: 'Electronics', e: 'The AND gate gives output 1 only when both inputs are 1.' },
  'Rectification is the conversion of:': { t: 'Electronics', e: 'A rectifier uses diodes to convert alternating current (AC) into direct current (DC).' },
  'The resistance of a light dependent resistor (LDR) decreases when:': { t: 'Electronics', e: 'Brighter light releases more charge carriers in the LDR, so its resistance falls as light intensity increases.' },
  'An alpha particle is:': { t: 'Radiation', e: 'An alpha particle is a helium nucleus containing 2 protons and 2 neutrons.' },
  'A beta particle is:': { t: 'Radiation', e: 'A beta particle is a fast-moving electron emitted when a neutron in the nucleus changes into a proton.' },
  'Which of the following radiations is the most penetrating?': { t: 'Radiation', e: 'Gamma rays have no charge and very short wavelengths, so they pass through far more material than alpha or beta particles.' },
  'The half-life of a radioactive substance is the time taken for:': { t: 'Radiation', e: 'By definition it is the time needed for half of the nuclei present at the start to decay.' },
  'Carbon-14 is mainly used for:': { t: 'Radiation', e: 'Carbon-14 has a half-life of about 5730 years, so the amount left is used to date ancient organic archaeological specimens.' },
  'Nuclear fission is the:': { t: 'Radiation', e: 'Fission is the splitting of a heavy nucleus such as uranium into lighter fragments, releasing energy.' },
  'Nuclear fusion is the:': { t: 'Radiation', e: 'Fusion is the joining together of light nuclei under enormous temperature to form a heavier nucleus, releasing energy.' },
  'The SI unit of radioactivity is the:': { t: 'Radiation', e: 'The becquerel (Bq) is the SI unit of activity, and 1 Bq = 1 decay per second.' },
  'Radioactive decay of a given nucleus is:': { t: 'Radiation', e: 'No one can predict when a single nucleus will decay, so the decay is random and spontaneous, even though large numbers decay at a steady average rate.' },
  'The atomic number of an element is the number of:': { t: 'Radiation', e: 'The atomic number Z counts the protons in the nucleus, and it is the protons that define the element.' },
  'Isotopes of an element have the same:': { t: 'Radiation', e: 'Isotopes have the same number of protons (atomic number) but different numbers of neutrons, so their mass numbers differ.' },
  'Hooke law states that within the elastic limit, the extension of a spring is:': { t: 'Materials', e: 'Hooke law: extension is directly proportional to the applied load, written F = kx.' },
  'A spring of force constant 100 N/m is stretched by 0.10 m. The force required is:': { t: 'Materials', e: 'F = kx = 100 x 0.10 = 10 N.' },
  'Strain is defined as:': { t: 'Materials', e: 'Strain is the deformation per unit original dimension, so for a wire it is the extension divided by the original length.' },
  'Young modulus is the ratio of:': { t: 'Materials', e: 'Young modulus = tensile stress/tensile strain, that is (force/area) divided by (extension/length).' },
  'A spring of force constant 50 N/m is stretched by 0.20 m. The elastic potential energy stored is:': { t: 'Materials', e: 'E = 1/2 kx^2 = 1/2 x 50 x 0.20^2 = 25 x 0.04 = 1 J.' },
  'Which of the following materials is brittle?': { t: 'Materials', e: 'Glass snaps with little or no permanent deformation, which is exactly what brittle means, whereas copper, steel and lead bend before breaking.' },
  'A force of 100 N acts on an area of 0.5 m^2. The pressure exerted is:': { t: 'Fluids', e: 'P = F/A = 100/0.5 = 200 Pa.' },
  'The pressure exerted by a liquid of density 1000 kg/m^3 at a depth of 5 m (take g = 10 m/s^2) is:': { t: 'Fluids', e: 'P = rho g h = 1000 x 10 x 5 = 50000 Pa.' },
  'Atmospheric pressure at sea level is approximately:': { t: 'Fluids', e: 'One atmosphere is about 1.013 x 10^5 Pa, so the value is approximately 10^5 Pa.' },
  'A hydraulic press works on the:': { t: 'Fluids', e: 'Pascal principle says pressure applied to an enclosed liquid is transmitted equally everywhere, so a small force on a small piston gives a large force on a large one.' },
  'The density of a body of mass 2 kg and volume 0.5 m^3 is:': { t: 'Fluids', e: 'rho = mass/volume = 2/0.5 = 4 kg/m^3.' },
  'According to Archimedes principle, the upthrust on a body immersed in a fluid is equal to the:': { t: 'Fluids', e: 'Archimedes principle states that the upthrust equals the weight of the fluid displaced by the body.' },
  'A body floats on the surface of a liquid when its density is:': { t: 'Fluids', e: 'A less dense body can displace a weight of liquid equal to its own weight before it is fully submerged, so it floats.' },
  'An iron nail sinks in water because the density of iron is:': { t: 'Fluids', e: 'Iron is denser than water, so the nail cannot displace its own weight of water and it sinks.' },
  'A body of mass 2 kg moves in a circle of radius 5 m at 10 m/s. The centripetal force required is:': { t: 'Motion and forces', e: 'F = mv^2/r = 2 x 10^2/5 = 2 x 100/5 = 40 N.' },
  'A body moving in a circle of radius 5 m at a speed of 10 m/s has a centripetal acceleration of:': { t: 'Motion and forces', e: 'a = v^2/r = 10^2/5 = 100/5 = 20 m/s^2.' },
  'A body moves in a circle of radius 5 m at a constant speed of 10 m/s. The time for one revolution is approximately:': { t: 'Motion and forces', e: 'T = 2 pi r/v = 2 x 3.14 x 5/10 = 31.4/10 = 3.14 s.' },
  'The weight of a body of mass 5 kg on the moon (g = 1.6 m/s^2) is approximately:': { t: 'Motion and forces', e: 'W = mg = 5 x 1.6 = 8 N.' },
  'The mass of a body on the moon compared with its mass on the earth is:': { t: 'Motion and forces', e: 'Mass is the amount of matter in the body and does not change with location, so it stays the same.' },
  'The escape velocity from the surface of the earth is about:': { t: 'Motion and forces', e: 'Escape velocity is the minimum launch speed needed to escape gravity without further thrust, about 11.2 km/s.' },
  'If the distance between two masses is halved while each mass is doubled, the gravitational force between them becomes:': { t: 'Motion and forces', e: 'F = G m1 m2/r^2. Doubling both masses multiplies F by 4, and halving r makes r^2 four times smaller, so F is multiplied by 4 x 4 = 16 times.' },
  'The value of g is maximum at the:': { t: 'Motion and forces', e: 'The earth bulges at the equator and is flattest at the poles, so the surface lies closest to the centre at the poles and g is greatest there.' },
  'A simple pendulum of length 1 m (take g = 10 m/s^2) has a period of approximately:': { t: 'Waves and sound', e: 'T = 2 pi sqrt(L/g) = 2 x 3.14 x sqrt(1/10) = 6.28 x 0.316 = 1.99 s, which is about 2 s.' },
  'In simple harmonic motion, the acceleration of the particle is:': { t: 'Waves and sound', e: 'SHM obeys a = -(omega^2)x, so the acceleration is proportional to the displacement and always points back towards the equilibrium position.' },
  'A transformer has 100 turns in its primary coil and 500 turns in its secondary coil. If the primary is supplied with 60 V, the secondary voltage is:': { t: 'Electricity and magnetism', e: 'Vs/Vp = Ns/Np, so Vs = 60 x 500/100 = 300 V.' }
};
